### ISSUE TITLE
test flake: Agent tests leak `github.com/robfig/cron/v3.(*Cron).run`

### ISSUE THREAD

**Issue by mafredri** [coder/coder#10289]
Some test in the `agent` package is leaving `github.com/robfig/cron/v3.(*Cron).run` around, suggesting not everything is properly stopped/terminated before agent exits.

https://github.com/coder/coder/actions/runs/6533683002/job/17739359218?pr=10285

```
goleak: Errors on successful test run: found unexpected goroutines:
[Goroutine 11052 in state select, with github.com/robfig/cron/v3.(*Cron).run on top of the stack:
goroutine 11052 [select]:
github.com/robfig/cron/v3.(*Cron).run(0xc00661e280)
	/home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:263 +0x1290
created by github.com/robfig/cron/v3.(*Cron).Start
	/home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:222 +0x145
]
FAIL	github.com/coder/coder/v2/agent	98.158s
```

**Comment by mafredri** [comment]
@kylecarbs any idea? I didn't take a look yet, but perhaps we need a check to see that cron tasks have stopped/run to completion when shutting down?
