### ISSUE TITLE
test flake: TestServer/TracerNoLeak

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder#10443]
Goleak is apparently failing to parse some traces?

```
panic: Failed to parse stack trace: parse function: no function found: "...additional frames elided..."
goroutine 14699 [running]:
go.uber.org/goleak/internal/stack.getStackBuffer(0x31?)
	/home/runner/go/pkg/mod/go.uber.org/goleak@v1.3.0/internal/stack/stacks.go:240 +0x65
go.uber.org/goleak/internal/stack.getStacks(0xd0?)
	/home/runner/go/pkg/mod/go.uber.org/goleak@v1.3.0/internal/stack/stacks.go:84 +0x45
go.uber.org/goleak/internal/stack.All(...)
	/home/runner/go/pkg/mod/go.uber.org/goleak@v1.3.0/internal/stack/stacks.go:229
go.uber.org/goleak.Find({0x0, 0x0, 0x0})
	/home/runner/go/pkg/mod/go.uber.org/goleak@v1.3.0/leaks.go:65 +0x1f4
github.com/coder/coder/v2/cli_test.TestServer.func20(0xc00e26c820)
	/home/runner/actions-runner/_work/coder/coder/cli/server_test.go:888 +0x225
testing.tRunner(0xc00e26c820, 0x55e2d30)
	/opt/hostedtoolcache/go/1.20.10/x64/src/testing/testing.go:1576 +0x217
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.20.10/x64/src/testing/testing.go:1629 +0x806
```

c.f. https://github.com/coder/coder/actions/runs/6705698344/job/18220674788

**Comment by spikecurtis** [comment]
fixed by #10444
