### ISSUE TITLE
health page is not accebale

### ISSUE THREAD

**Issue by matifali** [coder/coder#10818]
Version: v2.4.0
```console
TypeError: Cannot read properties of null (reading 'length')
    at https://REDACTED/assets/HealthPage-d7e89de3.js:1:1256
    at Array.some (<anonymous>)
    at Q (https://REDACTED/assets/HealthPage-d7e89de3.js:1:1201)
    at o2 (https://REDACTED/assets/index-9e9407c0.js:45:19538)
    at S3 (https://REDACTED/assets/index-9e9407c0.js:47:44055)
    at b3 (https:/REDACTED/assets/index-9e9407c0.js:47:39787)
    at CN (https://REDACTED/assets/index-9e9407c0.js:47:39715)
    at Ch (https://REDACTED/assets/index-9e9407c0.js:47:39568)
    at Jv (https://REDACTED/assets/index-9e9407c0.js:47:35933)
    at g3 (https://REDACTED/assets/index-9e9407c0.js:47:34882)
```

**Comment by matifali** [comment]
Seems to be resolved on`main`. Closing.
