### ISSUE TITLE
If there is a slight network outage, a Coder server with the tunnel crashes

### ISSUE THREAD

**Issue by bpmct** [coder/coder#10867]
## Background

If no [access URL](https://coder.com/docs/v2/latest/cli/server#--access-url) is specified for a Coder server, a public tunnel is used:

```sh
➜  ~ coder server
Coder v2.3.3+e491217 - Your Self-Hosted Remote Development Platform
Started HTTP listener at http://127.0.0.1:3000
Using built-in PostgreSQL (/Users/benpotter/Library/Application Support/coderv2/postgres)
Opening tunnel so workspaces can connect to your deployment. For production scenarios, specify an external access URL

View the Web UI: https://ul2585fdundn2.pit-1.try.coder.app
```

This tunnel is necessary so external workspaces (e.g. AWS instances) can reach the Coder server.

## Problem

If I briefly disconnect my laptop from the internet or if there is a sketchy internet connection, the server will crash.

```sh
2023-11-25 22:54:40.819 [erro]  net.devtunnel.wireguard_device: peer(9i3o…UMXM) - Failed to send data packets: write udp4 0.0.0.0:51470->74.118.138.247:55551: sendmsg: network is unreachable
2023-11-25 22:54:44.905 [warn]  net.devtunnel: periodically re-register tunnel ...
    error= do:
               github.com/coder/wgtunnel/tunnelsdk.(*Client).Request
                   /home/runner/go/pkg/mod/github.com/coder/wgtunnel@v0.1.12/tunnelsdk/client.go:67
             - Post "https://pit-1.try.coder.app/api/v2/clients": context deadline exceeded
panic: non-positive interval for Ticker.Reset

goroutine 67 [running]:
time.(*Ticker).Reset(0x104e14586?, 0x1f?)
	/opt/hostedtoolcache/go/1.20.10/x64/src/time/tick.go:55 +0x94
github.com/coder/wgtunnel/tunnelsdk.(*Client).LaunchTunnel.func2()
	/home/runner/go/pkg/mod/github.com/coder/wgtunnel@v0.1.12/tunnelsdk/tunnel.go:250 +0x90
created by github.com/coder/wgtunnel/tunnelsdk.(*Client).LaunchTunnel
	/home/runner/go/pkg/mod/github.com/coder/wgtunnel@v0.1.12/tunnelsdk/tunnel.go:231 +0x770
```

This occurs commonly when doing demos on conference Wi-Fi. We have a local demo environment with Docker+Kubernetes but also (when the Wi-Fi is good) we would love to demo cloud use cases such as AWS.

## Proposal

Change the behavior to do the following: 

- Do not crash the server, periodically try to reconnect in the background every 5 seconds
- Show a health check that the tunnel cannot be reached

**Comment by matifali** [comment]
> Show a health check that the tunnel cannot be reached

We could make this health check part of the existing ACCESS URL health check too.

**Comment by coadler** [comment]
yeah i'll take a looksie
