### ISSUE TITLE
healthcheck: If no wsproxy is configured `/health/workspace-proxy` gives "Something went wrong..."

### ISSUE THREAD

**Issue by matifali** [coder/coder#11087]
```console
TypeError: Cannot read properties of null (reading 'map')
    at S (https://coder.example.com/assets/WorkspaceProxyPage-201bda33.js:1:644)
    at AR (https://coder.example.com/assets/index-7b1b046c.js:45:19540)
    at c$ (https://coder.example.com/assets/index-7b1b046c.js:47:3139)
    at qz (https://coder.example.com/assets/index-7b1b046c.js:47:44585)
    at Wz (https://coder.example.com/assets/index-7b1b046c.js:47:39787)
    at GQ (https://coder.example.com/assets/index-7b1b046c.js:47:39715)
    at Tx (https://coder.example.com/assets/index-7b1b046c.js:47:39568)
    at x$ (https://coder.example.com/assets/index-7b1b046c.js:47:35933)
    at jz (https://coder.example.com/assets/index-7b1b046c.js:47:34882)
    at P (https://coder.example.com/assets/index-7b1b046c.js:32:1605)
```

**Comment by johnstcn** [comment]
@BrunoQuaresma this is now fixed on the BE but shows a blank page in the FE if you have no proxies.

**Comment by BrunoQuaresma** [comment]
Fixed by https://github.com/coder/coder/pull/11101
