### ISSUE TITLE
flake: enterprise/tailnet 

### ISSUE THREAD

**Issue by sreya** [coder/coder#11094]
Seen on [main](https://github.com/coder/coder/actions/runs/7128630318/job/19410972756)

```
=== Failed
=== FAIL: enterprise/tailnet  (0.00s)
PASS
goleak: Errors on successful test run: found unexpected goroutines:
[Goroutine 2373 in state chan send, with github.com/coder/coder/v2/enterprise/tailnet.(*querier).mappingQuery on top of the stack:
goroutine 2373 [chan send]:
github.com/coder/coder/v2/enterprise/tailnet.(*querier).mappingQuery(0xc000af81c0, {0xd0, 0xec, 0x53, 0x40, 0xc6, 0x3c, 0x4a, 0x8c, 0x81, ...})
	/home/runner/actions-runner/_work/coder/coder/enterprise/tailnet/pgcoord.go:944 +0x805
github.com/coder/coder/v2/enterprise/tailnet.(*querier).query(0xc0000c9da0?, {{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...})
	/home/runner/actions-runner/_work/coder/coder/enterprise/tailnet/pgcoord.go:892 +0x6c
github.com/coder/coder/v2/enterprise/tailnet.(*querier).worker.func1()
	/home/runner/actions-runner/_work/coder/coder/enterprise/tailnet/pgcoord.go:881 +0x2e
github.com/cenkalti/backoff/v4.RetryNotifyWithTimer.func1()
	/home/runner/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.2.1/retry.go:18 +0x1b
github.com/cenkalti/backoff/v4.doRetryNotify[...](0xc0000c9ed8?, {0x7f124cd4c500, 0xc000647ec0}, 0x0, {0x0, 0x0?})
	/home/runner/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.2.1/retry.go:88 +0x152
github.com/cenkalti/backoff/v4.RetryNotifyWithTimer(0x0?, {0x7f124cd4c500?, 0xc000647ec0?}, 0x1fb7fa7a5f196281?, {0x0?, 0x0?})
	/home/runner/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.2.1/retry.go:61 +0x65
github.com/cenkalti/backoff/v4.RetryNotify(...)
	/home/runner/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.2.1/retry.go:49
github.com/cenkalti/backoff/v4.Retry(...)
	/home/runner/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.2.1/retry.go:38
github.com/coder/coder/v2/enterprise/tailnet.(*querier).worker(0xc000af81c0)
	/home/runner/actions-runner/_work/coder/coder/enterprise/tailnet/pgcoord.go:880 +0x1f0
created by github.com/coder/coder/v2/enterprise/tailnet.newQuerier.func1
	/home/runner/actions-runner/_work/coder/coder/enterprise/tailnet/pgcoord.go:797 +0x7f
]
```

**Comment by sreya** [comment]
This already got fixed
