### ISSUE TITLE
flake: TestAgent_WriteVSCodeConfigs

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder#11226]
https://github.com/coder/coder/runs/19666833200

Test times out after 10 minutes due to a deadlock in shutting down the agent

```
goroutine 2555 [semacquire, 9 minutes]:
sync.runtime_Semacquire(0xc0006ae1b0?)
	/opt/hostedtoolcache/go/1.21.5/x64/src/runtime/sema.go:62 +0x25
sync.(*WaitGroup).Wait(0xc0006ae1a8)
	/opt/hostedtoolcache/go/1.21.5/x64/src/sync/waitgroup.go:116 +0xa5
github.com/coder/coder/v2/agent/agentscripts.(*Runner).Close(0xc0006ae100)
	/home/runner/actions-runner/_work/coder/coder/agent/agentscripts/agentscripts.go:320 +0x19e
github.com/coder/coder/v2/agent.(*agent).Close(0xc004a0b200)
	/home/runner/actions-runner/_work/coder/coder/agent/agent.go:1498 +0x439
github.com/coder/coder/v2/agent_test.TestAgent_WriteVSCodeConfigs(0xc005b456c0)
	/home/runner/actions-runner/_work/coder/coder/agent/agent_test.go:1870 +0x160a
testing.tRunner(0xc005b456c0, 0x27ceba0)
	/opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1595 +0x262
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1648 +0x846
```

**Comment by Emyrk** [comment]
this unit test exercises the bug: https://github.com/coder/coder/pull/11243/commits/278252100a0379b3d9f9fbe2a0137436d1daec47
