### ISSUE TITLE
flake: TestProvision_Cancel: text file busy

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#11232]
Seen here: https://github.com/coder/coder/actions/runs/7221152894/job/19675544052?pr=11231

Logs:

```
=== FAIL: provisioner/terraform  (0.00s)
panic: test timed out after 10m0s
running tests:
	TestProvision_Cancel (9m58s)
	TestProvision_Cancel/Cancel_plan (9m58s)

goroutine 742 [running]:
testing.(*M).startAlarm.func1()
	/opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:2259 +0x3b9
created by time.goFunc
	/opt/hostedtoolcache/go/1.21.5/x64/src/time/sleep.go:176 +0x2d

goroutine 1 [chan receive, 9 minutes]:
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1561 +0x489
testing.tRunner(0xc000582b60, 0xc0003efc38)
	/opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1601 +0x138
testing.runTests(0xc0000d9720?, {0x2827a20, 0x12, 0x12}, {0x418dbf?, 0xc0003efcf8?, 0x283dce0?})
	/opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:2052 +0x445
testing.(*M).Run(0xc0000d9720)
	/opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1925 +0x636
main.main()
	_testmain.go:117 +0x1bf

goroutine 68 [chan receive, 9 minutes]:
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1561 +0x489
testing.tRunner(0xc000602820, 0x1a395c0)
	/opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1601 +0x138
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1648 +0x3ad

goroutine 129 [sync.Cond.Wait, 9 minutes]:
sync.runtime_notifyListWait(0xc0005152e8, 0x2)
	/opt/hostedtoolcache/go/1.21.5/x64/src/runtime/sema.go:527 +0x159
sync.(*Cond).Wait(0x2?)
	/opt/hostedtoolcache/go/1.21.5/x64/src/sync/cond.go:70 +0x85
storj.io/drpc/drpcstream.(*packetBuffer).Get(0xc0005152d0)
	/home/runner/go/pkg/mod/storj.io/drpc@v0.0.33-0.20230420154621-9716137f6037/drpcstream/pktbuf.go:65 +0x8b
storj.io/drpc/drpcstream.(*Stream).MsgRecv(0xc000515200, {0x1883420, 0xc000[382](https://github.com/coder/coder/actions/runs/7221152894/job/19675544052?pr=11231#step:5:383)500}, {0x1c36258, 0x2889ee0})
	/home/runner/go/pkg/mod/storj.io/drpc@v0.0.33-0.20230420154621-9716137f6037/drpcstream/stream.go:477 +0x105
github.com/coder/coder/v2/provisionersdk/proto.(*drpcProvisioner_SessionClient).Recv(0xc000740070)
	/home/runner/actions-runner/_work/coder/coder/provisionersdk/proto/provisioner_drpc.pb.go:83 +0x93
github.com/coder/coder/v2/provisioner/terraform_test.TestProvision_Cancel.func1(0xc0006a8000)
	/home/runner/actions-runner/_work/coder/coder/provisioner/terraform/provision_test.go:183 +0x9c2
testing.tRunner(0xc0006a8000, 0xc00056acb0)
	/opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1595 +0xff
created by testing.(*T).Run in goroutine 68
	/opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1648 +0x3ad

goroutine 230 [chan receive, 9 minutes]:
github.com/valyala/fasthttp/fasthttputil.(*InmemoryListener).Accept(0xc00050b650?)
	/home/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.51.0/fasthttputil/inmemory_listener.go:50 +0x2b
storj.io/drpc/drpcserver.(*Server).Serve(0xc0002b6100, {0x1c485c0, 0xc0002aa0f0}, {0x1c45060?, 0xc0003820c0})
	/home/runner/go/pkg/mod/storj.io/drpc@v0.0.33-0.20230420154621-9716137f6037/drpcserver/server.go:87 +0x1a5
github.com/coder/coder/v2/provisionersdk.Serve({0x1c485c0?, 0xc0002aa0f0}, {0x1c44fd0?, 0xc0004f40a0}, 0x427625?)
	/home/runner/actions-runner/_work/coder/coder/provisionersdk/serve.go:86 +0x865
github.com/coder/coder/v2/provisioner/terraform.Serve({0x1c485c0, 0xc0002aa0f0}, 0xc000118e70)
	/home/runner/actions-runner/_work/coder/coder/provisioner/terraform/serve.go:98 +0x513
github.com/coder/coder/v2/provisioner/terraform_test.setupProvisioner.func2()
	/home/runner/actions-runner/_work/coder/coder/provisioner/terraform/provision_test.go:55 +0x352
created by github.com/coder/coder/v2/provisioner/terraform_test.setupProvisioner in goroutine 129
	/home/runner/actions-runner/_work/coder/coder/provisioner/terraform/provision_test.go:54 +0x358

goroutine 231 [chan receive, 9 minutes]:
storj.io/drpc/drpcserver.(*Server).Serve.func1({0x1c49430?, 0xc00050b650?})
	/home/runner/go/pkg/mod/storj.io/drpc@v0.0.33-0.20230420154621-9716137f6037/drpcserver/server.go:82 +0x3a
storj.io/drpc/drpcctx.(*Tracker).track(0xc00050b650, 0xc00050b470?)
	/home/runner/go/pkg/mod/storj.io/drpc@v0.0.33-0.20230420154621-9716137f6037/drpcctx/tracker.go:35 +0x25
created by storj.io/drpc/drpcctx.(*Tracker).Run in goroutine 230
	/home/runner/go/pkg/mod/storj.io/drpc@v0.0.33-0.20230420154621-9716137f6037/drpcctx/tracker.go:30 +0x79

goroutine 232 [chan receive, 9 minutes]:
github.com/coder/coder/v2/provisionersdk.(*Session).handleRequests(0xc0004f4320)
	/home/runner/actions-runner/_work/coder/coder/provisionersdk/session.go:122 +0x107
github.com/coder/coder/v2/provisionersdk.(*protoServer).Session(0xc0004f41e0, {0x1c4ea10, 0xc000740080})
	/home/runner/actions-runner/_work/coder/coder/provisionersdk/session.go:93 +0xb2d
github.com/coder/coder/v2/provisionersdk/proto.(*DRPCProvisionerDescription).Method.DRPCProvisionerDescription.Method.func1({0x16bc8c0?, 0xc0004f41e0}, {0xc0005e00a0?, 0x20?}, {0x18feb80?, 0xc000515440}, {0x2889ee0?, 0x0?})
	/home/runner/actions-runner/_work/coder/coder/provisionersdk/proto/provisioner_drpc.pb.go:113 +0xb9
storj.io/drpc/drpcmux.(*Mux).HandleRPC(0x0?, {0x1c4a8c0, 0xc000515440}, {0xc0005e00a0, 0x20})
	/home/runner/go/pkg/mod/storj.io/drpc@v0.0.33-0.20230420154621-9716137f6037/drpcmux/handle_rpc.go:33 +0x20d
github.com/coder/coder/v2/coderd/tracing.(*DRPCHandler).HandleRPC(0xc0003bdf80, {0x1c4a8c0, 0xc000515440}, {0xc0005e00a0, 0x20})
	/home/runner/actions-runner/_work/coder/coder/coderd/tracing/drpc.go:23 +0x223
storj.io/drpc/drpcserver.(*Server).handleRPC(0xc00023afc0?, 0x1c48588?, {0xc0005e00a0?, 0x2889ee0?})
	/home/runner/go/pkg/mod/storj.io/drpc@v0.0.33-0.20230420154621-9716137f6037/drpcserver/server.go:124 +0x36
storj.io/drpc/drpcserver.(*Server).ServeOne(0xc0002b6100, {0x1c49430, 0xc00050b650}, {0x7f35cccdd088?, 0xc00028a098?})
	/home/runner/go/pkg/mod/storj.io/drpc@v0.0.33-0.20230420154621-9716137f6037/drpcserver/server.go:66 +0x1d2
storj.io/drpc/drpcserver.(*Server).Serve.func2({0x1c49430, 0xc00050b650})
	/home/runner/go/pkg/mod/storj.io/drpc@v0.0.33-0.20230420154621-9716137f6037/drpcserver/server.go:114 +0x59
storj.io/drpc/drpcctx.(*Tracker).track(0xc00050b650, 0x0?)
	/home/runner/go/pkg/mod/storj.io/drpc@v0.0.33-0.20230420154621-9716137f6037/drpcctx/tracker.go:35 +0x25
created by storj.io/drpc/drpcctx.(*Tracker).Run in goroutine 230
	/home/runner/go/pkg/mod/storj.io/drpc@v0.0.33-0.20230420154621-9716137f6037/drpcctx/tracker.go:30 +0x79

goroutine 233 [select, 9 minutes]:
github.com/valyala/fasthttp/fasthttputil.(*pipeConn).readNextByteBuffer(0xc00028a098, 0x1)
	/home/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.51.0/fasthttputil/pipeconns.go:188 +0x1b1
github.com/valyala/fasthttp/fasthttputil.(*pipeConn).read(0xc00028a098, {0xc0006bf000, 0x1000, 0xc000580800?}, 0x8e?)
	/home/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.51.0/fasthttputil/pipeconns.go:165 +0x34
github.com/valyala/fasthttp/fasthttputil.(*pipeConn).Read(0x0?, {0xc0006bf000?, 0x0?, 0x0?})
	/home/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.51.0/fasthttputil/pipeconns.go:148 +0x7b
storj.io/drpc/drpcwire.(*Reader).ReadPacketUsing(0xc00062a8a0, {0xc0005e0080?, 0x4?, 0x20?})
	/home/runner/go/pkg/mod/storj.io/drpc@v0.0.33-0.20230420154621-9716137f6037/drpcwire/reader.go:96 +0x4eb
storj.io/drpc/drpcmanager.(*Manager).manageReader(0xc00023afc0)
	/home/runner/go/pkg/mod/storj.io/drpc@v0.0.33-0.20230420154621-9716137f6037/drpcmanager/manager.go:226 +0xfb
created by storj.io/drpc/drpcmanager.NewWithOptions in goroutine 232
	/home/runner/go/pkg/mod/storj.io/drpc@v0.0.33-0.20230420154621-9716137f6037/drpcmanager/manager.go:118 +0x416

goroutine 234 [select, 9 minutes]:
storj.io/drpc/drpcmanager.(*Manager).manageStream(0xc00023afc0, {0x1c48588, 0xc00050b680}, 0xc000515440)
	/home/runner/go/pkg/mod/storj.io/drpc@v0.0.33-0.20230420154621-9716137f6037/drpcmanager/manager.go:326 +0xf1
storj.io/drpc/drpcmanager.(*Manager).manageStreams(0xc00023afc0)
	/home/runner/go/pkg/mod/storj.io/drpc@v0.0.33-0.20230420154621-9716137f6037/drpcmanager/manager.go:315 +0x85
created by storj.io/drpc/drpcmanager.NewWithOptions in goroutine 232
	/home/runner/go/pkg/mod/storj.io/drpc@v0.0.33-0.20230420154621-9716137f6037/drpcmanager/manager.go:119 +0x456

goroutine 235 [select, 9 minutes]:
github.com/valyala/fasthttp/fasthttputil.(*pipeConn).readNextByteBuffer(0xc00028a000, 0x1)
	/home/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.51.0/fasthttputil/pipeconns.go:188 +0x1b1
github.com/valyala/fasthttp/fasthttputil.(*pipeConn).read(0xc00028a000, {0xc000750000, 0x1000, 0xc000580800?}, 0x8e?)
	/home/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.51.0/fasthttputil/pipeconns.go:165 +0x34
github.com/valyala/fasthttp/fasthttputil.(*pipeConn).Read(0x0?, {0xc000750000?, 0x0?, 0x0?})
	/home/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.51.0/fasthttputil/pipeconns.go:148 +0x7b
storj.io/drpc/drpcwire.(*Reader).ReadPacketUsing(0xc00062aae0, {0xc00062f200?, 0x5a?, 0x60?})
	/home/runner/go/pkg/mod/storj.io/drpc@v0.0.33-0.20230420154621-9716137f6037/drpcwire/reader.go:96 +0x4eb
storj.io/drpc/drpcmanager.(*Manager).manageReader(0xc00023b340)
	/home/runner/go/pkg/mod/storj.io/drpc@v0.0.33-0.20230420154621-9716137f6037/drpcmanager/manager.go:226 +0xfb
created by storj.io/drpc/drpcmanager.NewWithOptions in goroutine 129
	/home/runner/go/pkg/mod/storj.io/drpc@v0.0.33-0.20230420154621-9716137f6037/drpcmanager/manager.go:118 +0x416

goroutine 236 [select, 9 minutes]:
storj.io/drpc/drpcmanager.(*Manager).manageStream(0xc00023b340, {0x1c485c0, 0xc0002aa0f0}, 0xc000515200)
	/home/runner/go/pkg/mod/storj.io/drpc@v0.0.33-0.20230420154621-9716137f6037/drpcmanager/manager.go:326 +0xf1
storj.io/drpc/drpcmanager.(*Manager).manageStreams(0xc00023b340)
	/home/runner/go/pkg/mod/storj.io/drpc@v0.0.33-0.20230420154621-9716137f6037/drpcmanager/manager.go:315 +0x85
created by storj.io/drpc/drpcmanager.NewWithOptions in goroutine 129
	/home/runner/go/pkg/mod/storj.io/drpc@v0.0.33-0.20230420154621-9716137f6037/drpcmanager/manager.go:119 +0x456

goroutine 237 [select, 9 minutes]:
github.com/coder/coder/v2/codersdk/drpc.(*memDRPC).NewStream.func1()
	/home/runner/actions-runner/_work/coder/coder/codersdk/drpc/transport.go:121 +0x9c
created by github.com/coder/coder/v2/codersdk/drpc.(*memDRPC).NewStream in goroutine 129
	/home/runner/actions-runner/_work/coder/coder/codersdk/drpc/transport.go:120 +0x2f6

goroutine 238 [sync.Cond.Wait, 9 minutes]:
sync.runtime_notifyListWait(0xc000515528, 0x4)
	/opt/hostedtoolcache/go/1.21.5/x64/src/runtime/sema.go:527 +0x159
sync.(*Cond).Wait(0xc000114e08?)
	/opt/hostedtoolcache/go/1.21.5/x64/src/sync/cond.go:70 +0x85
storj.io/drpc/drpcstream.(*packetBuffer).Get(0xc000515510)
	/home/runner/go/pkg/mod/storj.io/drpc@v0.0.33-0.20230420154621-9716137f6037/drpcstream/pktbuf.go:65 +0x8b
storj.io/drpc/drpcstream.(*Stream).MsgRecv(0xc000515440, {0x189a900, 0xc000382400}, {0x1c36258, 0x2889ee0})
	/home/runner/go/pkg/mod/storj.io/drpc@v0.0.33-0.20230420154621-9716137f6037/drpcstream/stream.go:477 +0x105
github.com/coder/coder/v2/provisionersdk/proto.(*drpcProvisioner_SessionStream).Recv(0xc000740080)
	/home/runner/actions-runner/_work/coder/coder/provisionersdk/proto/provisioner_drpc.pb.go:142 +0x93
github.com/coder/coder/v2/provisionersdk.(*Session).requestReader.func1()
	/home/runner/actions-runner/_work/coder/coder/provisionersdk/session.go:101 +0xe5
created by github.com/coder/coder/v2/provisionersdk.(*Session).requestReader in goroutine 232
	/home/runner/actions-runner/_work/coder/coder/provisionersdk/session.go:98 +0xca
FAIL	github.com/coder/coder/v2/provisioner/terraform	600.035s

=== FAIL: provisioner/terraform TestProvision_Cancel (unknown)
    t.go:84: 2023-12-15 10:59:20.418 [info]  unpacking template source archive  session_id=43bb9686-0ded-446e-95f4-5ae62e6d5295  size_bytes=0
    t.go:84: 2023-12-15 10:59:20.421 [info]  clean stale Terraform plugins  cache_path=/tmp/TestProvision_CancelCancel_init1027[392](https://github.com/coder/coder/actions/runs/7221152894/job/19675544052?pr=11231#step:5:393)714/002
    t.go:84: 2023-12-15 10:59:20.[421](https://github.com/coder/coder/actions/runs/7221152894/job/19675544052?pr=11231#step:5:422) [debu]  running initialization
    t.go:84: 2023-12-15 10:59:20.421 [debu]  executor: starting command  args="[init -no-color -input=false]"
    t.go:84: 2023-12-15 10:59:20.421 [debu]  executing terraform command  binary_path=/tmp/TestProvision_CancelCancel_init1027392714/001/terraform  args="[init -no-color -input=false]"
    provision_test.go:186: &{level:DEBUG output:"init_start"}
    t.go:84: 2023-12-15 10:59:20.427 [debu]  canceledOrComplete closed
    t.go:84: 2023-12-15 10:59:20.427 [debu]  executor: interrupted command  args="[/tmp/TestProvision_CancelCancel_init1027392714/001/terraform init -no-color -input=false]"  error=<nil>
    t.go:84: 2023-12-15 10:59:20.427 [debu]  graceful context done
    t.go:84: 2023-12-15 10:59:20.427 [debu]  executor: command done  args="[init -no-color -input=false]"  error="exit status 1"
    t.go:84: 2023-12-15 10:59:20.427 [debu]  executor: closing writers  error="exit status 1"
    t.go:84: 2023-12-15 10:59:20.427 [debu]  init failed  error="exit status 1"
--- PASS: TestProvision_Cancel/Cancel_init (0.01s)
    t.go:84: 2023-12-15 10:59:20.[422](https://github.com/coder/coder/actions/runs/7221152894/job/19675544052?pr=11231#step:5:423) [info]  unpacking template source archive  session_id=461bfe0d-c0cd-45b8-958f-d9e[457](https://github.com/coder/coder/actions/runs/7221152894/job/19675544052?pr=11231#step:5:458)c07e93  size_bytes=0
    provision_test.go:186: &{error:"fork/exec /tmp/TestProvision_CancelCancel_plan3731309765/001/terraform: text file busy"}
    t.go:84: 2023-12-15 10:59:20.422 [debu]  graceful context done
    t.go:84: 2023-12-15 10:59:20.422 [debu]  kill context done
    t.go:84: 2023-12-15 10:59:20.422 [debu]  canceledOrComplete closed

=== FAIL: provisioner/terraform TestProvision_Cancel/Cancel_plan (unknown)
    t.go:84: 2023-12-15 10:59:20.422 [info]  unpacking template source archive  session_id=[461](https://github.com/coder/coder/actions/runs/7221152894/job/19675544052?pr=11231#step:5:462)bfe0d-c0cd-45b8-958f-d9e457c07e93  size_bytes=0
    provision_test.go:186: &{error:"fork/exec /tmp/TestProvision_CancelCancel_plan3731309765/001/terraform: text file busy"}
    t.go:84: 2023-12-15 10:59:20.422 [debu]  graceful context done
    t.go:84: 2023-12-15 10:59:20.422 [debu]  kill context done
    t.go:84: 2023-12-15 10:59:20.422 [debu]  canceledOrComplete closed
```

**Comment by johnstcn** [comment]
Popped up again here: https://github.com/coder/coder/actions/runs/7450422695/job/20269291400

**Comment by mafredri** [comment]
Popped up here too: https://github.com/coder/coder/actions/runs/7667128076/job/20896333135?pr=11825

Tests time out but the text file busy error is in the logs: `fork/exec /tmp/TestProvision_CancelCancel_plan1932857750/001/terraform: text file busy`.
