### ISSUE TITLE
data race: coderd/provisionerdserver TestFailJob

### ISSUE THREAD

**Issue by mtojek** [coder/coder#11578]
Seen [here](https://github.com/coder/coder/actions/runs/7490479990/job/20389452906?pr=11549)

```
=== FAIL: coderd/provisionerdserver TestFailJob (unknown)
==================
WARNING: DATA RACE
Write at 0x00c0005e8130 by goroutine 28:
  runtime.closechan()
      /opt/hostedtoolcache/go/1.21.5/x64/src/runtime/chan.go:357 +0x0
  github.com/coder/coder/v2/coderd/provisionerdserver_test.TestHeartbeat()
      /home/runner/actions-runner/_work/coder/coder/coderd/provisionerdserver/provisionerdserver_test.go:137 +0x3eb
  testing.tRunner()
      /opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1595 +0x261
  testing.(*T).Run.func1()
      /opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1648 +0x44

Previous read at 0x00c0005e8130 by goroutine 50:
  runtime.chansend()
      /opt/hostedtoolcache/go/1.21.5/x64/src/runtime/chan.go:160 +0x0
  github.com/coder/coder/v2/coderd/provisionerdserver_test.TestHeartbeat.func1()
      /home/runner/actions-runner/_work/coder/coder/coderd/provisionerdserver/provisionerdserver_test.go:113 +0xb2
  github.com/coder/coder/v2/coderd/provisionerdserver.(*server).heartbeat()
      /home/runner/actions-runner/_work/coder/coder/coderd/provisionerdserver/provisionerdserver.go:267 +0x88
  github.com/coder/coder/v2/coderd/provisionerdserver.(*server).heartbeatLoop()
      /home/runner/actions-runner/_work/coder/coder/coderd/provisionerdserver/provisionerdserver.go:245 +0x308
  github.com/coder/coder/v2/coderd/provisionerdserver.NewServer.func1()
      /home/runner/actions-runner/_work/coder/coder/coderd/provisionerdserver/provisionerdserver.go:216 +0x33

Goroutine 28 (running) created at:
  testing.(*T).Run()
      /opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1648 +0x845
  testing.runTests.func1()
      /opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:2054 +0x84
  testing.tRunner()
      /opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1595 +0x261
  testing.runTests()
      /opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:2052 +0x8ad
  testing.(*M).Run()
      /opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1925 +0xcd7
  go.uber.org/goleak.VerifyTestMain()
      /home/runner/go/pkg/mod/go.uber.org/goleak@v1.2.1/testmain.go:53 +0x64
  github.com/coder/coder/v2/coderd/provisionerdserver_test.TestMain()
      /home/runner/actions-runner/_work/coder/coder/coderd/provisionerdserver/acquirer_test.go:28 +0x316
  main.main()
      _testmain.go:83 +0x303

Goroutine 50 (running) created at:
  github.com/coder/coder/v2/coderd/provisionerdserver.NewServer()
      /home/runner/actions-runner/_work/coder/coder/coderd/provisionerdserver/provisionerdserver.go:216 +0x1213
  github.com/coder/coder/v2/coderd/provisionerdserver_test.setup()
      /home/runner/actions-runner/_work/coder/coder/coderd/provisionerdserver/provisionerdserver_test.go:1793 +0x118a
  github.com/coder/coder/v2/coderd/provisionerdserver_test.TestHeartbeat()
      /home/runner/actions-runner/_work/coder/coder/coderd/provisionerdserver/provisionerdserver_test.go:118 +0x251
  testing.tRunner()
      /opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1595 +0x261
  testing.(*T).Run.func1()
      /opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1648 +0x44
==================
panic: send on closed channel

goroutine 68 [running]:
github.com/coder/coder/v2/coderd/provisionerdserver_test.TestHeartbeat.func1({0x2adb120, 0xc000640150})
	/home/runner/actions-runner/_work/coder/coder/coderd/provisionerdserver/provisionerdserver_test.go:113 +0xb3
github.com/coder/coder/v2/coderd/provisionerdserver.(*server).heartbeat(0xc0001ec000, {0x2adb120, 0xc000640150})
	/home/runner/actions-runner/_work/coder/coder/coderd/provisionerdserver/provisionerdserver.go:267 +0x89
github.com/coder/coder/v2/coderd/provisionerdserver.(*server).heartbeatLoop(0xc0001ec000)
	/home/runner/actions-runner/_work/coder/coder/coderd/provisionerdserver/provisionerdserver.go:245 +0x309
created by github.com/coder/coder/v2/coderd/provisionerdserver.NewServer in goroutine 52
	/home/runner/actions-runner/_work/coder/coder/coderd/provisionerdserver/provisionerdserver.go:216 +0x1214
```

**Comment by kylecarbs** [comment]
The line numbers changed in this file, so reason to believe this may be fixed. Closing!
