### ISSUE TITLE
panic returned when running `coder external-auth access-token`

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#12126]
reproduced on `2.7.0`, and `2.8.2` - see below:

```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/coder/coder/v2/cli.(*RootCmd).externalAuthAccessToken.func1(0x14000858a00)
        /home/runner/actions-runner/_work/coder/coder/cli/externalauth.go:74 +0x52c
github.com/coder/coder/v2/cli.(*RootCmd).Command.func6.1(0x0?)
        /home/runner/actions-runner/_work/coder/coder/cli/root.go:293 +0xc0
github.com/coder/coder/v2/cli/clibase.(*Invocation).run(0x14000858a00, 0x14000849cc8)
        /home/runner/actions-runner/_work/coder/coder/cli/clibase/cmd.go:428 +0xd00
github.com/coder/coder/v2/cli/clibase.(*Invocation).run(0x14000858200, 0x14000849cc8)
        /home/runner/actions-runner/_work/coder/coder/cli/clibase/cmd.go:365 +0x8b8
github.com/coder/coder/v2/cli/clibase.(*Invocation).run(0x14000858200, 0x14000849cc8)
        /home/runner/actions-runner/_work/coder/coder/cli/clibase/cmd.go:365 +0x8b8
github.com/coder/coder/v2/cli/clibase.(*Invocation).Run(0x14000849df0?)
        /home/runner/actions-runner/_work/coder/coder/cli/clibase/cmd.go:518 +0xb8
github.com/coder/coder/v2/cli.(*RootCmd).RunMain(0x1400084cd80, {0x1400092efc0, 0x2a, 0x48})
        /home/runner/actions-runner/_work/coder/coder/cli/root.go:140 +0x198
main.main()
        /home/runner/actions-runner/_work/coder/coder/enterprise/cmd/coder/main.go:11 +0x40
```

**Comment by kylecarbs** [comment]
You'll need to specify a provider by ID and it will work, but yeah this is jank.
