### ISSUE TITLE
Having issues with DNS queries against my set up in AWS EKS route53 hosted zone subdomain from domain at godaddy

### ISSUE THREAD

**Issue by washbert** [coder/coder#12287]
**Version**
v2.8.3+01c6266

**Path**
`/deployment/general`

**Error**
```
Error: User is not authenticated.
    at si (https://coder.realdecoy.com/assets/index-635f8de7.js:264:2648)
    at A7e (https://coder.realdecoy.com/assets/index-635f8de7.js:264:8733)
    at eO (https://coder.realdecoy.com/assets/index-635f8de7.js:45:19551)
    at tK (https://coder.realdecoy.com/assets/index-635f8de7.js:47:44101)
    at ZV (https://coder.realdecoy.com/assets/index-635f8de7.js:47:39819)
    at qfe (https://coder.realdecoy.com/assets/index-635f8de7.js:47:39745)
    at sv (https://coder.realdecoy.com/assets/index-635f8de7.js:47:39596)
    at RA (https://coder.realdecoy.com/assets/index-635f8de7.js:47:35959)
    at z3 (https://coder.realdecoy.com/assets/index-635f8de7.js:47:36764)
    at Ll (https://coder.realdecoy.com/assets/index-635f8de7.js:45:3288)
```

**Comment by bpmct** [comment]
👋🏼 Sorry we missed this. If this happens again? Can you submit a request on https://discord.gg/coder or reopen?
