### ISSUE TITLE
Coder Owner Workspaces Access Issue

### ISSUE THREAD

**Issue by tiaden** [coder/coder#13011]
In previous versions, I don't remember the version number but I was able to access regular user workspaces from vscode using the extension. I cannot do that in coder v2.9.2 or v2.10.1 with the environment variable 
 CODER_DISABLE_OWNER_WORKSPACE_ACCESS=false.  see logs below

`[18:38:16.312] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[18:38:16.493] > [?9001h[?1004h
[18:38:16.494] Got some output, clearing connection timeout
[18:38:16.576] > ]0;C:\WINDOWS\System32\cmd.exe
[18:38:17.555] > Encountered an error running "coder vscodessh", see "coder vscodessh --help" for more information
> error: Trace=[find workspace and agent: ]
> Resource not found or you do not have access to this resource
[18:38:17.575] > The process tried to write to a nonexistent pipe.
[18:38:18.832] "install" terminal command done
[18:38:18.832] Install terminal quit with output: Resource not found or you do not have access to this resource
[18:38:18.832] Received install output: Resource not found or you do not have access to this resource
[18:38:18.833] Failed to parse remote port from server output
[18:38:18.834] Resolver error: Error: 
    at g.Create (c:\Users\matif\.vscode\extensions\ms-vscode-remote.remote-ssh-0.110.1\out\extension.js:2:499181)
    at t.handleInstallOutput (c:\Users\matif\.vscode\extensions\ms-vscode-remote.remote-ssh-0.110.1\out\extension.js:2:496503)
    at t.tryInstall (c:\Users\matif\.vscode\extensions\ms-vscode-remote.remote-ssh-0.110.1\out\extension.js:2:620043)
    at async c:\Users\matif\.vscode\extensions\ms-vscode-remote.remote-ssh-0.110.1\out\extension.js:2:579901
    at async t.withShowDetailsEvent (c:\Users\matif\.vscode\extensions\ms-vscode-remote.remote-ssh-0.110.1\out\extension.js:2:583207)
    at async k (c:\Users\matif\.vscode\extensions\ms-vscode-remote.remote-ssh-0.110.1\out\extension.js:2:576866)
    at async t.resolve (c:\Users\matif\.vscode\extensions\ms-vscode-remote.remote-ssh-0.110.1\out\extension.js:2:580578)
    at async c:\Users\matif\.vscode\extensions\ms-vscode-remote.remote-ssh-0.110.1\out\extension.js:2:846687
[18:38:18.838] ------`

**Comment by kylecarbs** [comment]
I fixed this and I believe it's released in 2.10+.

**Comment by kylecarbs** [comment]
Hmm, maybe it didn't make it to 2.10. I'll check in a bit!

**Comment by bpmct** [comment]
Hey, moving to vscode-coder repo where we can give it more attention. cc @stirby
