### ISSUE TITLE
vscode desktop not working

### ISSUE THREAD

**Issue by samar-elsayed** [coder/coder#13272]
when I try to click on vscode desktop

![image](https://github.com/coder/coder/assets/22873802/773997b8-1578-45c6-9321-71f4a7dff780)

![image](https://github.com/coder/coder/assets/22873802/e54588c8-a36a-421a-b722-ae8d73d0ede2)

nothing is happening and no proxy is used 

![image](https://github.com/coder/coder/assets/22873802/844fad1f-d036-4cc2-88fd-157a9d974aca)

**Comment by kylecarbs** [comment]
Odd.

Can you run the "Coder: Show Logs" command?

**Comment by samar-elsayed** [comment]
it gives me no logs 

![image](https://github.com/coder/coder/assets/22873802/e09e19d6-3f55-45f6-a41e-1c1193391089)

this output appears after canceling the ssh 

```
[15:05:45.456] Log Level: 2
[15:05:45.535] VS Code version: 1.86.0
[15:05:45.535] Remote-SSH version: remote-ssh@0.108.0
[15:05:45.535] win32 x64
[15:05:47.267] SSH Resolver called for "ssh-remote+coder-vscode--samar--Integration-workspace", attempt 1
[15:05:47.268] "remote.SSH.useLocalServer": false
[15:05:47.268] "remote.SSH.useExecServer": false
[15:05:47.268] "remote.SSH.showLoginTerminal": false
[15:05:47.269] "remote.SSH.remotePlatform": {"coder-vscode--samar--Integration-workspace":"linux"}
[15:05:47.269] "remote.SSH.path": undefined
[15:05:47.269] "remote.SSH.configFile": D:\.ssh\config
[15:05:47.269] "remote.SSH.useFlock": true
[15:05:47.269] "remote.SSH.lockfilesInTmp": false
[15:05:47.269] "remote.SSH.localServerDownload": auto
[15:05:47.270] "remote.SSH.remoteServerListenOnSocket": false
[15:05:47.270] "remote.SSH.showLoginTerminal": false
[15:05:47.270] "remote.SSH.defaultExtensions": []
[15:05:47.270] "remote.SSH.loglevel": 2
[15:05:47.270] "remote.SSH.enableDynamicForwarding": true
[15:05:47.270] "remote.SSH.enableRemoteCommand": false
[15:05:47.271] "remote.SSH.serverPickPortsFromRange": {}
[15:05:47.271] "remote.SSH.serverInstallPath": {}
[15:05:47.279] SSH Resolver called for host: coder-vscode--samar--Integration-workspace
[15:05:47.279] Setting up SSH remote "coder-vscode--samar--Integration-workspace"
[15:05:47.284] Using commit id "05047486b6df5eb8d44b2ecd70ea3bdf775fd937" and quality "stable" for server
[15:05:47.287] Install and start server if needed
[15:05:47.292] Checking ssh with "C:\Windows\system32\ssh.exe -V"
[15:05:47.293] Got error from ssh: spawn C:\Windows\system32\ssh.exe ENOENT
[15:05:47.293] Checking ssh with "C:\Windows\ssh.exe -V"
[15:05:47.294] Got error from ssh: spawn C:\Windows\ssh.exe ENOENT
[15:05:47.294] Checking ssh with "C:\Windows\System32\Wbem\ssh.exe -V"
[15:05:47.295] Got error from ssh: spawn C:\Windows\System32\Wbem\ssh.exe ENOENT
[15:05:47.295] Checking ssh with "C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[15:05:47.296] Got error from ssh: spawn C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[15:05:47.296] Checking ssh with "C:\Windows\System32\OpenSSH\ssh.exe -V"
[15:05:47.350] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[15:05:47.355] Using SSH config file "D:\.ssh\config"
[15:05:47.355] Running script with connection command: "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 53304 -F "D:\.ssh\config" "coder-vscode--samar--Integration-workspace" bash
[15:05:47.358] Terminal shell path: C:\Windows\System32\cmd.exe
[15:05:47.669] > ]0;C:\Windows\System32\cmd.exe
[15:05:47.669] Got some output, clearing connection timeout
[15:06:22.104] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[15:06:23.841] "install" terminal command done
[15:06:23.841] Install terminal quit with output: ]0;C:\Windows\System32\cmd.exe
[15:06:23.841] Received install output: ]0;C:\Windows\System32\cmd.exe
[15:06:23.843] Failed to parse remote port from server output
[15:06:23.846] Resolver error: Error: 
	at g.Create (c:\Users\samar.elsayed\.vscode\extensions\ms-vscode-remote.remote-ssh-0.108.0\out\extension.js:2:460245)
	at t.handleInstallOutput (c:\Users\samar.elsayed\.vscode\extensions\ms-vscode-remote.remote-ssh-0.108.0\out\extension.js:2:457567)
	at t.tryInstall (c:\Users\samar.elsayed\.vscode\extensions\ms-vscode-remote.remote-ssh-0.108.0\out\extension.js:2:581100)
	at async c:\Users\samar.elsayed\.vscode\extensions\ms-vscode-remote.remote-ssh-0.108.0\out\extension.js:2:540958
	at async t.withShowDetailsEvent (c:\Users\samar.elsayed\.vscode\extensions\ms-vscode-remote.remote-ssh-0.108.0\out\extension.js:2:544264)
	at async k (c:\Users\samar.elsayed\.vscode\extensions\ms-vscode-remote.remote-ssh-0.108.0\out\extension.js:2:537923)
	at async t.resolve (c:\Users\samar.elsayed\.vscode\extensions\ms-vscode-remote.remote-ssh-0.108.0\out\extension.js:2:541635)
	at async c:\Users\samar.elsayed\.vscode\extensions\ms-vscode-remote.remote-ssh-0.108.0\out\extension.js:2:807794
[15:06:23.856] ------
```

**Comment by samar-elsayed** [comment]
# ------------START-CODER-----------
# This section is managed by coder. DO NOT EDIT.
#
# You should not hand-edit this section unless you are removing it, all
# changes will be lost when running "coder config-ssh".
#
Host coder.Integration-workspace
       HostName coder.Integration-workspace
       ConnectTimeout=0
       StrictHostKeyChecking=no
       UserKnownHostsFile=/dev/null
       LogLevel ERROR
       ProxyCommand /tmp/coder.VgspzZ/coder --global-config /root/.config/coderv2 ssh --stdio Integration-workspace
Host coder.Integration-workspace.main
       HostName coder.Integration-workspace.main
       ConnectTimeout=0
       StrictHostKeyChecking=no
       UserKnownHostsFile=/dev/null
       LogLevel ERROR
       ProxyCommand /tmp/coder.VgspzZ/coder --global-config /root/.config/coderv2 ssh --stdio Integration-workspace.main
# ------------END-CODER------------

# --- START CODER VSCODE ---
Host coder-vscode--*
  ConnectTimeout 0
  LogLevel ERROR
  ProxyCommand "c:\Users\samar.elsayed\AppData\Roaming\Code\User\globalStorage\coder.coder-remote\bin\coder-windows-amd64.exe" vscodessh --network-info-dir "c:\Users\samar.elsayed\AppData\Roaming\Code\User\globalStorage\coder.coder-remote\net" --log-dir "c:\Users\samar.elsayed\AppData\Roaming\Code\User\globalStorage\coder.coder-remote\log" --session-token-file "c:\Users\samar.elsayed\AppData\Roaming\Code\User\globalStorage\coder.coder-remote\session_token" --url-file "c:\Users\samar.elsayed\AppData\Roaming\Code\User\globalStorage\coder.coder-remote\url" %h
  SetEnv  CODER_SSH_SESSION_TYPE=vscode
  StrictHostKeyChecking no
  UserKnownHostsFile /dev/null
# --- END CODER VSCODE ---

**Comment by kylecarbs** [comment]
Can you try adding additional `\` to the `ProxyCommand` in the `START CODER VSCODE` section?

**Comment by kylecarbs** [comment]
Nah, I mean:
```
ProxyCommand "c:\\Users\\samar.elsayed\\AppData\\Roaming\\Code\\User\\globalStorage\\coder.coder-remote\\bin\\coder-windows-amd64.exe" vscodessh --network-info-dir "c:\\Users\\samar.elsayed\\AppData\\Roaming\\Code\\User\\globalStorage\\coder.coder-remote\\net" --log-dir "c:\\Users\\samar.elsayed\\AppData\\Roaming\\Code\\User\\globalStorage\\coder.coder-remote\\log" --session-token-file "c:\\Users\\samar.elsayed\\AppData\\Roaming\\Code\\User\\globalStorage\\coder.coder-remote\\session_token" --url-file "c:\\Users\\samar.elsayed\\AppData\\Roaming\\Code\\User\\globalStorage\\coder.coder-remote\\url" %h
```

**Comment by samar-elsayed** [comment]
I tried that but everytime I click on vscode desktop, it gets overwritten and returns to its original shape

**Comment by aksharbarot** [comment]
+1

**Comment by samar-elsayed** [comment]
@kylecarbs 

my last ssh trial, it stops at debug1: **Local version string SSH-2.0-OpenSSH_for_Windows_8.1** and then nothing happens
Do you know what could be the reason ? 
```
debug1: C:\\Users\\samar.elsayed/.ssh/config line 18: Applying options for 10.90.7.66
debug1: Executing proxy command: exec D:\\coder_2.9.4_windows_amd64\\coder.exe --global-config C:\\Users\\samar.elsayed\\AppData\\Roaming\\coderv2 ssh --stdio Integration-workspace
debug1: identity file C:\\Users\\samar.elsayed/.ssh/id_rsa type 0
debug1: identity file C:\\Users\\samar.elsayed/.ssh/id_rsa-cert type -1
debug1: identity file C:\\Users\\samar.elsayed/.ssh/id_dsa type -1
debug1: identity file C:\\Users\\samar.elsayed/.ssh/id_dsa-cert type -1
debug1: identity file C:\\Users\\samar.elsayed/.ssh/id_ecdsa type -1
debug1: identity file C:\\Users\\samar.elsayed/.ssh/id_ecdsa-cert type -1
debug1: identity file C:\\Users\\samar.elsayed/.ssh/id_ed25519 type -1
debug1: identity file C:\\Users\\samar.elsayed/.ssh/id_ed25519-cert type -1
debug1: identity file C:\\Users\\samar.elsayed/.ssh/id_xmss type -1
debug1: identity file C:\\Users\\samar.elsayed/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_8.1
```

**Comment by bpmct** [comment]
Moving this to the `vscode-coder` repository
