### ISSUE TITLE
Connect to Coder workspace with JetBrains Gateway error

### ISSUE THREAD

**Issue by capjiang** [coder/coder#13776]
After I deployed Coder on a private server, I used Docker Containers in the Starter Templates as the server, and I was able to use functions such as VS code Desktop normally below. 
However, when I used the gateway to connect, an error always occurred at "Connecting to Coder workspace.." when downloading IU-242.19533.56. 
<img width="589" alt="Snipaste_2024-07-03_09-07-33" src="https://github.com/coder/coder/assets/95555443/c0cbe7dd-12e2-4346-afd6-c85922930073">
error
<img width="330" alt="Snipaste_2024-07-02_16-29-30" src="https://github.com/coder/coder/assets/95555443/70235f82-5b82-4b97-b52a-816061f3f1a9">

>https://coder.com/docs/ides/gateway#manually-configuring-a-jetbrains-gateway-connection
An error also occurred when I used the manual installation of ideaIU. 
`./remote-dev-server.sh registerBackendLocationForGateway`
<img width="1905" alt="Snipaste_2024-07-03_09-49-59" src="https://github.com/coder/coder/assets/95555443/e7c3ffab-f7e5-4c2d-9d7c-74f8b63a4551">

Is this bug due to the Docker Template not being supported, and is it necessary to use a specific Template?

**Comment by ammario** [comment]
cc @code-asher

**Comment by code-asher** [comment]
> However, when I used the gateway to connect, an error always occurred at "Connecting to Coder workspace.." when downloading IU-242.19533.56

If you run that `curl` command on the workspace, does it also error?  I wonder if `jetbrains.com` is not accessible from your workspace.  There might be more information in the logs if you can upload them.

> An error also occurred when I used the manual installation of ideaIU.

What error shows in the Gateway UI?  Or could you upload the full logs?  I am not sure the error in the screenshot is related.

**Comment by capjiang** [comment]
Thank you for your help. Here is the log of Gateway.
```
2024-07-03 16:01:14,555 [3082876]   WARN - #c.j.g.s.RemoteCredentialsEx - Timeout of PT10M expired while waiting for '/bin/bash -lc echo\ REMOTE_EXEC_OUTPUT_MARKER_\ \&\&\ curl\ -fSL\ --output\ /home/jzj-admin/.cache/JetBrains/RemoteDev/dist/ideaIU-2024.1.4.tar.gz\ https://download.jetbrains.com/idea/ideaIU-2024.1.4.tar.gz' to terminate, forcefully terminating...
2024-07-03 16:01:14,773 [3083094]   WARN - #c.j.g.s.GoHighLevelHostAccessor - An error occurred while execution command: '/bin/bash -lc echo\ REMOTE_EXEC_OUTPUT_MARKER_\ \&\&\ curl\ -fSL\ --output\ /home/jzj-admin/.cache/JetBrains/RemoteDev/dist/ideaIU-2024.1.4.tar.gz\ https://download.jetbrains.com/idea/ideaIU-2024.1.4.tar.gz'
Exit code: 255
Stderr: ''
Stdout: '  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   138  100   138    0     0    444      0 --:--:-- --:--:-- --:--:--   443
  0 1266M    0 6077k    0     0  3573k      0  0:06:02  0:00:01  0:06:01 3573k
  0 1266M    0 6108k    0     0  2719k      0  0:07:57  0:00:02  0:07:55 59839
......
 81 1266M   81 1037M    0     0  1779k      0  0:12:09  0:09:57  0:02:12 1659k
 82 1266M   82 1039M    0     0  1780k      0  0:12:08  0:09:58  0:02:10 1750k
 82 1266M   82 1041M    0     0  1780k      0  0:12:08  0:09:59  0:02:09 1868k'
2024-07-03 16:01:14,780 [3083101] SEVERE - CoderRemoteConnectionHandle - Failed to connect (will not retry)
com.jetbrains.gateway.ssh.RemoteCommandException: Command "/bin/bash -lc echo\ REMOTE_EXEC_OUTPUT_MARKER_\ \&\&\ curl\ -fSL\ --output\ /home/jzj-admin/.cache/JetBrains/RemoteDev/dist/ideaIU-2024.1.4.tar.gz\ https://download.jetbrains.com/idea/ideaIU-2024.1.4.tar.gz" failed with exit code 255}
	at com.jetbrains.gateway.ssh.GoHighLevelHostAccessor.awaitWithStreamsTracking(GoHighLevelHostAccessor.kt:681)
	at com.jetbrains.gateway.ssh.GoHighLevelHostAccessor.access$awaitWithStreamsTracking(GoHighLevelHostAccessor.kt:38)
	at com.jetbrains.gateway.ssh.GoHighLevelHostAccessor$awaitWithStreamsTracking$1.invokeSuspend(GoHighLevelHostAccessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at com.intellij.openapi.rd.util.CoroutineProgressContext$Companion$create$task$1$3.invokeSuspend(BackgroundProgressCoroutineUtil.kt:289)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.intellij.openapi.rd.util.CoroutineProgressContext$Companion$create$task$1.invoke(BackgroundProgressCoroutineUtil.kt:285)
	at com.intellij.openapi.rd.util.CoroutineProgressContext$Companion$create$task$1.invoke(BackgroundProgressCoroutineUtil.kt:275)
	at com.intellij.openapi.rd.util.CoroutineProgressContext$Companion$createBackgroundable$1$1.run(BackgroundProgressCoroutineUtil.kt:308)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:477)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:133)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:528)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:250)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:100)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:221)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:46)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:220)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:202)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:100)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:250)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:500)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
2024-07-03 16:01:14,785 [3083106] SEVERE - CoderRemoteConnectionHandle - JetBrains Gateway 2024.1.2  Build #GW-241.17011.87
2024-07-03 16:01:14,786 [3083107] SEVERE - CoderRemoteConnectionHandle - JDK: 17.0.11; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2024-07-03 16:01:14,786 [3083107] SEVERE - CoderRemoteConnectionHandle - OS: Windows 11
2024-07-03 16:01:14,786 [3083107] SEVERE - CoderRemoteConnectionHandle - Last Action: 
2024-07-03 16:02:04,217 [3132538]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities com.intellij.platform.workspace.jps.entities.SdkEntity to files
2024-07-03 16:02:04,218 [3132539]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities com.intellij.platform.workspace.jps.entities.LibraryEntity to files
2024-07-03 16:02:04,225 [3132546]   INFO - #c.i.a.o.PathMacrosImpl - Saved path macros: {}
2024-07-03 16:02:04,300 [3132621]   INFO - #c.i.u.s.SvgCacheManager - SVG icon cache is closed
2024-07-03 16:02:04,312 [3132633]   INFO - #o.j.i.BuiltInServer - web server stopped
2024-07-03 16:02:04,317 [3132638]   INFO - #c.i.o.v.i.l.NativeFileWatcherImpl - Watcher terminated with exit code 0
2024-07-03 16:02:04,334 [3132655]   INFO - #c.i.s.i.s.sshj - Disconnected - BY_APPLICATION
2024-07-03 16:02:04,351 [3132672]   WARN - #c.i.s.ProxyCommand - Process[pid=23844, exitValue=1] exited with code 1
2024-07-03 16:02:04,362 [3132683]   INFO - #c.i.p.s.SerializationManagerImpl - Start shutting down C:\Users\capji\AppData\Local\JetBrains\JetBrainsGateway2024.1\index\rep.names
2024-07-03 16:02:04,362 [3132683]   INFO - #c.i.p.s.SerializationManagerImpl - Finished shutting down C:\Users\capji\AppData\Local\JetBrains\JetBrainsGateway2024.1\index\rep.names
2024-07-03 16:02:04,365 [3132686]   INFO - #c.i.u.i.FileBasedIndexImpl - Index dispose started
2024-07-03 16:02:04,408 [3132729]   INFO - #c.i.p.s.StubIndexImpl - StubIndexExtension-s were unloaded
2024-07-03 16:02:04,411 [3132732]   INFO - #c.i.u.i.FileBasedIndexImpl - Index dispose completed in 44ms.
2024-07-03 16:02:04,422 [3132743]   INFO - #c.i.o.v.n.p.PersistentFSImpl - VFS dispose started
2024-07-03 16:02:04,425 [3132746]   INFO - #c.i.o.v.n.p.FSRecordsImpl - VFS closing
2024-07-03 16:02:04,472 [3132793]   INFO - #c.i.o.v.n.p.PersistentFSImpl - VFS dispose completed in 49 ms.
2024-07-03 16:02:04,473 [3132794]   INFO - #c.i.o.f.i.FileTypeDetectionService - 0 auto-detected files. Detection took 0 ms
2024-07-03 16:02:04,486 [3132807]   INFO - #c.i.p.i.b.AppStarter - ------------------------------------------------------ IDE SHUTDOWN ------------------------------------------------------
```

**Comment by capjiang** [comment]
Thank you. I was able to successfully connect to the Coder IDE backend after manually starting the IDE backend. There may have been an error in the previous steps.
I'm sorry to take up your time, and I really appreciate your help.

**Comment by code-asher** [comment]
No worries!  I am glad you got it working.
