### ISSUE TITLE
Owner Can't Access Member Workspace via VS Code Desktop

### ISSUE THREAD

**Issue by aemorales2** [coder/coder#14220]
Howdy

We're using coder 2.10.3 with an envbox template and recently noticed that the owner role can't access a member role's workspace using the vs code desktop or the code-server. We were able to resolve the latter using the CODER_DANGEROUS_ALLOW_PATH_APP_SITE_OWNER_ACCESS env variable mentioned in the docs, but have not found a solution for VS Code Desktop.  The owner role can still access their own workspaces with VS Code Desktop. 

I've read through the newer version release notes but if this is addressed there I have missed it. Below are the logs I see on the vs coder output window when attempting to access a member role's workspace logged in as an owner role. 

If anyone can point me to a way to resolve this or something that says this is expected with our current version+ I'd greatly appreciate you for it. 

```
[15:06:04.289] Running script with connection command: "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 57159 "coder-vscode.coder.mydomain.com--membername--not-my-workspace" bash
[15:06:04.290] Terminal shell path: C:\Windows\System32\cmd.exe
[15:06:04.535] > ]0;C:\Windows\System32\cmd.exe
[15:06:04.535] Got some output, clearing connection timeout
[15:06:04.772] > Encountered an error running "coder vscodessh", see "coder vscodessh --help" for
>  more information
> error: Trace=[find workspace and agent: ]
> Resource not found or you do not have access to this resource
[15:06:04.795] > kex_exchange_identification: Connection closed by remote host
> The process tried to write to a nonexistent pipe.
> 
[15:06:06.060] "install" terminal command done
[15:06:06.061] Install terminal quit with output: kex_exchange_identification: Connection closed by remote host
[15:06:06.061] Received install output: kex_exchange_identification: Connection closed by remote host
[15:06:06.062] Failed to parse remote port from server output
[15:06:06.063] Resolver error: Error: 
	at m.Create (c:\Users\aemor\.vscode\extensions\ms-vscode-remote.remote-ssh-0.113.1\out\extension.js:2:501230)
	at t.handleInstallOutput (c:\Users\aemor\.vscode\extensions\ms-vscode-remote.remote-ssh-0.113.1\out\extension.js:2:498552)
	at t.tryInstall (c:\Users\aemor\.vscode\extensions\ms-vscode-remote.remote-ssh-0.113.1\out\extension.js:2:623316)
	at async c:\Users\aemor\.vscode\extensions\ms-vscode-remote.remote-ssh-0.113.1\out\extension.js:2:582788
	at async t.withShowDetailsEvent (c:\Users\aemor\.vscode\extensions\ms-vscode-remote.remote-ssh-0.113.1\out\extension.js:2:586054)
	at async k (c:\Users\aemor\.vscode\extensions\ms-vscode-remote.remote-ssh-0.113.1\out\extension.js:2:579675)
	at async t.resolve (c:\Users\aemor\.vscode\extensions\ms-vscode-remote.remote-ssh-0.113.1\out\extension.js:2:583465)
	at async c:\Users\aemor\.vscode\extensions\ms-vscode-remote.remote-ssh-0.113.1\out\extension.js:2:851126
[15:06:06.070] ------
```

**Comment by aemorales2** [comment]
After more attempts we found that we can use an owner role to connect to vscode but needed to manually update the .ssh/config file to include an entry for the workspace we're trying to access.

```
Host coder.membername.not-my-workspace.main
	HostName coder.membername.not-my-workspace.main
	ConnectTimeout=0
	StrictHostKeyChecking=no
	UserKnownHostsFile=/dev/null
	LogLevel ERROR
	ProxyCommand C:\Users\aemor\Documents\toolbox\coder\2.10.3\bin\coder.exe --global-config C:\Users\aemor\AppData\Roaming\coderv2 ssh --stdio membername/not-my-workspace.main
```

After this step we open VS Code and use the command palette to access `Remote-SSH: Connect to Host...` and select the host we manually added above: `coder.membername.not-my-workspace.main`. 

This will connect as expected. This is a workaround for what we're facing but I'll leave this thread open since we cannot get this working from the UI.

**Comment by aemorales2** [comment]
I see the "waiting for info" tag on this but I'm not sure what information is required from my side of things. Please let me know what I can provide to help.

**Comment by matifali** [comment]
It looks like this was reported previously in https://github.com/coder/vscode-coder/issues/289, which was fixed. @aemorales2, can you confirm what version of Coder and [vscode-coder](https://github.com/coder/vscode-coder) extension are you on?
cc: @code-asher

**Comment by aemorales2** [comment]
thanks for the link, looks like I need to upgrade. We are on 2.10.3
