### ISSUE TITLE
coder login command results in i/o timeout error when not using a proxy

### ISSUE THREAD

**Issue by MVMartinov19** [coder/coder#14719]
I encountered an issue today when attempting to run the following command:

```coder login "https://URL"```

The result was the following error message:

```
Encountered an error running "coder login", see "coder login --help" for more information
error: Failed to check server "https://URL" for first user, is the URL correct and is coder accessible from your browser? Error - has initial user: Get "https://URL/api/v2/users/first": dial tcp URL:443: i/o timeout
```

**Root Cause**
The issue arises because, without a proxy, there is no access to the internet. Only when connected through a proxy is there internet access, which allows the system to reach the Coder instance.

While HTTP requests made from JetBrains Gateway's `CoderCLIManager`,

`CoderCLIManager - GET 200 https://URL/bin/coder-windows-amd64.exe` are successful, it's important to note that JetBrains Gateway uses the system's Proxy settings.

**Question**
Is there a way for the Coder CLI to use proxy settings from Windows, or alternatively, can a proxy be configured for Coder CLI to make requests via HTTP or another type of proxy? This would ensure that Coder CLI can function properly in environments where direct internet access is restricted without a proxy.

Without proxy settings in Coder CLI, requests timeout due to the lack of direct internet access.

**Environment**
OS: Windows 10

Would appreciate any guidance on configuring proxy settings for Coder CLI.

**Comment by MVMartinov19** [comment]
Hey,
We configured it with system wide environment variables, it worked, but we came to another problem. We have authenticated successfully from the coder cli, but now when it is retrieving IDEs from the Remote Workspaces, it hangs on "Establishing SSH connection to the remote worker..." on JetBrains Gateway and in the logs there is:

```
2024-09-18 22:29:10,893 [ 347920]   WARN - #c.i.s.i.s.sshj - Failed to connect. Brief info: SSH connection to coder@coder-jetbrains--salmon-leopon-26.main--coder.codingburgas.org--bg:22
 * With altered connection settings:
  - authMethods: PublicKey(privateKeys=[C:\Users\ssivanov19\.ssh\id_rsa, C:\Users\ssivanov19\.ssh\id_dsa, C:\Users\ssivanov19\.ssh\id_ecdsa, C:\Users\ssivanov19\.ssh\id_ed25519, C:\Users\ssivanov19\.ssh\id_xmss], agent=ALL), Password, KeyboardInteractive
  - ciphers: [chacha20-poly1305@openssh.com, aes128-ctr, aes192-ctr, aes256-ctr, aes128-gcm@openssh.com, aes256-gcm@openssh.com]
  - connectTimeout: PT0S
  - environmentVariables: [Certain(name=CODER_SSH_SESSION_TYPE, value=JetBrains)]
  - hostKeyAlgorithms: [ecdsa-sha2-nistp256-cert-v01@openssh.com, ecdsa-sha2-nistp384-cert-v01@openssh.com, ecdsa-sha2-nistp521-cert-v01@openssh.com, ssh-ed25519-cert-v01@openssh.com, rsa-sha2-512-cert-v01@openssh.com, rsa-sha2-256-cert-v01@openssh.com, ssh-rsa-cert-v01@openssh.com, ecdsa-sha2-nistp256, ecdsa-sha2-nistp384, ecdsa-sha2-nistp521, ssh-ed25519, rsa-sha2-512, rsa-sha2-256, ssh-rsa]
  - hostKeyVerifier: OpenSSH-like host key verifier (knownHostsFile=[C:\dev\null, C:\Program Files (x86)\JetBrains\JetBrains Gateway 2024.1.2\jbr\bin\__PROGRAMDATA__\ssh\ssh_known_hosts, C:\Program Files (x86)\JetBrains\JetBrains Gateway 2024.1.2\jbr\bin\__PROGRAMDATA__\ssh\ssh_known_hosts2], strictHostKeyChecking=NO, hashKnownHosts=false)
  - kexAlgorithms: [curve25519-sha256, curve25519-sha256@libssh.org, ecdh-sha2-nistp256, ecdh-sha2-nistp384, ecdh-sha2-nistp521, diffie-hellman-group-exchange-sha256, diffie-hellman-group16-sha512, diffie-hellman-group18-sha512, diffie-hellman-group14-sha256, diffie-hellman-group14-sha1]
  - macs: [umac-64-etm@openssh.com, umac-128-etm@openssh.com, hmac-sha2-256-etm@openssh.com, hmac-sha2-512-etm@openssh.com, hmac-sha1-etm@openssh.com, umac-64@openssh.com, umac-128@openssh.com, hmac-sha2-256, hmac-sha2-512, hmac-sha1]
  - proxyConfig: Command(command=C:\Users\ssivanov19\AppData\Local\coder-gateway\coder.codingburgas.org\coder-windows-amd64.exe --global-config C:\Users\ssivanov19\AppData\Local\coder-gateway\coder.codingburgas.org\config --url https://coder.codingburgas.org ssh --stdio --usage-app=disable salmon-leopon-26.main)
  - user: coder
 * With auth agent pageant
java.lang.InterruptedException
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
	at com.intellij.ssh.impl.sshj.SshjConnectionUtilKt.get(SshjConnectionUtil.kt:266)
	at com.intellij.ssh.impl.sshj.SshjConnectionUtilKt.get$default(SshjConnectionUtil.kt:262)
	at com.intellij.ssh.impl.sshj.SshjConnectionUtilKt.setUpSessionForSshJ(SshjConnectionUtil.kt:228)
	at com.intellij.ssh.impl.SshConnection.doSshjSshConnection(SshConnection.kt:239)
	at com.intellij.ssh.impl.SshConnection.access$doSshjSshConnection(SshConnection.kt:28)
	at com.intellij.ssh.impl.SshConnection$createSshSessionForSshj$1.invoke(SshConnection.kt:232)
	at com.intellij.ssh.impl.SshConnection$createSshSessionForSshj$1.invoke(SshConnection.kt:229)
	at com.intellij.ssh.Ssh.wrapBlockingSshCall(ssh.kt:396)
	at com.intellij.ssh.Ssh.wrapBlockingSshCall$default(ssh.kt:377)
	at com.intellij.ssh.impl.SshConnection.createSshSessionForSshj(SshConnection.kt:229)
	at com.intellij.ssh.impl.SshConnection.access$createSshSessionForSshj(SshConnection.kt:28)
	at com.intellij.ssh.impl.SshConnection$createSession$1.invoke(SshConnection.kt:217)
	at com.intellij.ssh.impl.SshConnection$createSession$1.invoke(SshConnection.kt:214)
	at com.intellij.ssh.Ssh.wrapBlockingSshCall(ssh.kt:396)
	at com.intellij.ssh.Ssh.wrapBlockingSshCall$default(ssh.kt:377)
	at com.intellij.ssh.impl.SshConnection.createSession(SshConnection.kt:214)
	at com.intellij.ssh.impl.SshConnection.access$createSession(SshConnection.kt:28)
	at com.intellij.ssh.impl.SshConnection$openChannel$1.invoke(SshConnection.kt:95)
	at com.intellij.ssh.impl.SshConnection$openChannel$1.invoke(SshConnection.kt:57)
	at com.intellij.ssh.Ssh.wrapBlockingSshCall(ssh.kt:396)
	at com.intellij.ssh.Ssh.wrapBlockingSshCall$default(ssh.kt:377)
	at com.intellij.ssh.impl.SshConnection.openChannel(SshConnection.kt:57)
	at com.intellij.ssh.SshConnectionService.exec(SshConnectionService.kt:217)
	at com.intellij.ssh.ExecBuilder.execute(ssh.kt:222)
	at com.intellij.ssh.ExecBuilder.execute$default(ssh.kt:216)
	at com.jetbrains.gateway.ssh.deploy.impl.SshCommandExecutor$executeCommand$process$1.invoke(SshCommandExecutor.kt:66)
	at com.jetbrains.gateway.ssh.deploy.impl.SshCommandExecutor$executeCommand$process$1.invoke(SshCommandExecutor.kt:60)
	at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:52)
	at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
	at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:44)
	at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invoke(Interruptible.kt)
	at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invoke(Interruptible.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at kotlinx.coroutines.InterruptibleKt.runInterruptible(Interruptible.kt:43)
	at com.jetbrains.gateway.ssh.deploy.impl.SshCommandExecutor.executeCommand(SshCommandExecutor.kt:60)
	at com.jetbrains.gateway.ssh.deploy.HostCommandExecutor.executeCommand$default(HostCommandExecutor.kt:58)
	at com.jetbrains.gateway.ssh.deploy.ExtensionsKt.executeAndWait(Extensions.kt:88)
	at com.jetbrains.gateway.ssh.deploy.ExtensionsKt.executeAndWait(Extensions.kt:121)
	at com.jetbrains.gateway.ssh.deploy.ExtensionsKt.executeAndWait$default(Extensions.kt:120)
	at com.jetbrains.gateway.ssh.deploy.ShellFacade$Companion.getDeployTargetOs(ShellFacade.kt:302)
	at com.jetbrains.gateway.ssh.deploy.ShellFacade$Companion.fromExecutor(ShellFacade.kt:229)
	at com.jetbrains.gateway.ssh.HighLevelHostAccessor$Companion.create(HighLevelHostAccessor.kt:72)
	at com.jetbrains.gateway.ssh.HighLevelHostAccessor$Companion.create(HighLevelHostAccessor.kt:68)
	at com.coder.gateway.views.steps.CoderWorkspaceProjectIDEStepView.createRemoteExecutor(CoderWorkspaceProjectIDEStepView.kt:323)
	at com.coder.gateway.views.steps.CoderWorkspaceProjectIDEStepView.access$createRemoteExecutor(CoderWorkspaceProjectIDEStepView.kt:86)
	at com.coder.gateway.views.steps.CoderWorkspaceProjectIDEStepView$init$1$ides$4.invokeSuspend(CoderWorkspaceProjectIDEStepView.kt:218)
	at com.coder.gateway.views.steps.CoderWorkspaceProjectIDEStepView$init$1$ides$4.invoke(CoderWorkspaceProjectIDEStepView.kt)
	at com.coder.gateway.views.steps.CoderWorkspaceProjectIDEStepView$init$1$ides$4.invoke(CoderWorkspaceProjectIDEStepView.kt)
	at com.coder.gateway.util.RetryKt.suspendingRetryWithExponentialBackOff(Retry.kt:54)
	at com.coder.gateway.util.RetryKt.suspendingRetryWithExponentialBackOff$default(Retry.kt:40)
	at com.coder.gateway.views.steps.CoderWorkspaceProjectIDEStepView$init$1.invokeSuspend(CoderWorkspaceProjectIDEStepView.kt:207)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

From what I see from the Performance Monitor Network Activity, the coder-windows-amd64.exe app is trying again to connect to external IP without the proxy. The first connection is to the proxy and the second connection is external CF IP.
<img width="1050" alt="image" src="https://github.com/user-attachments/assets/38405cc8-e66f-42d6-be59-fe24146320ea">

**Comment by deansheather** [comment]
Can you check that Jetbrains has the correct environment variables set? I would expect the IDE to pass down it's environment to the coder subprocess when launching it. You can view env vars of running processes with a [python oneliner](https://superuser.com/a/1756391) or with Process Explorer

cc @code-asher

**Comment by code-asher** [comment]
Yup, I tested just now (with `mitmproxy`) and can confirm setting **both** `http_proxy` and `https_proxy` in the environment where Gateway is ran will make Gateway, the plugin, and the Coder cli all use the proxy (as long as "auto-detect proxy settings" is enabled in Gateway).

Although, I am having a different problem where the `ssh` command hangs forever when I use my proxy.  :confused:  (Same when I run `ssh` on the command line.)  Seems like a different problem than this though.

**Comment by code-asher** [comment]
I tested on Linux though, maybe there is something odd about Gateway on Windows when it tries to ssh.  One thing to test is whether ssh works on the command line for you, I think the two instances in your screenshot are one from the binary being directly executed and the other indirect from Gateway trying to ssh.

For example, I check `~/.ssh/config` to find the host name Gateway is using and run:

```
https_proxy=http://localhost:8080 ssh coder-jetbrains--dev27.dev--dev.coder.com
```

This is not a perfect test because Gateway does not shell out to `ssh`, rather it has a Java implementation of ssh, but it might indicate something at least.
