### ISSUE TITLE
Create workspace via Web UI using the `do-linux` template results in error

### ISSUE THREAD

**Issue by mafredri** [coder/coder#2161]
Steps to reproduce:

1. `coder templates create do-linux -d ~/src/coder/examples/templates/do-linux`
2. Open web UI to create a new workspace (`/workspaces/new`)
3. Select `do-linux`
4. Error

Some value is expected to have `.length` but is null instead.

Adding both backend and frontend labels as I did not investigate if the type contract is broken by the API or not.

At least one response from the API (`/api/v2/templateversions/[uuid]/schema`) has `validation_contains` set to `null`. Ideally it would be an empty array as I don't think the distinction matters.

```
======================= STACK TRACE ========================

Cannot read properties of null (reading 'length')
    at X (http://localhost:4000/bundle.5d728432d907df1db6f6.js:1:6936)
    at aa (http://localhost:4000/bundle.43fdb3edbbcc5a08d2e9.js:2:651913)
    at Vs (http://localhost:4000/bundle.43fdb3edbbcc5a08d2e9.js:2:703962)
    at Au (http://localhost:4000/bundle.43fdb3edbbcc5a08d2e9.js:2:691236)
    at Tu (http://localhost:4000/bundle.43fdb3edbbcc5a08d2e9.js:2:691164)
    at Cu (http://localhost:4000/bundle.43fdb3edbbcc5a08d2e9.js:2:691027)
    at gu (http://localhost:4000/bundle.43fdb3edbbcc5a08d2e9.js:2:688014)
    at http://localhost:4000/bundle.43fdb3edbbcc5a08d2e9.js:2:637835
    at t.unstable_runWithPriority (http://localhost:4000/bundle.43fdb3edbbcc5a08d2e9.js:2:753812)
    at Vi (http://localhost:4000/bundle.43fdb3edbbcc5a08d2e9.js:2:637612)

============================================================
```

**Comment by vapurrmaid** [comment]
Relates to and possibly duplicates #1977

**Comment by misskniss** [comment]
@mafredri are you able to repro this? If so will you shoe Kira what you see? We still want to bring this in for this week if possible.
