### ISSUE TITLE
code-server 4.4.0 does not change themes / update the settings.json

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#2286]
in the `coder` template, i've opened code-server and clicked `Color Theme` to change the IDE theme (as shown below).

![Screen Shot 2022-06-13 at 11 23 56 AM](https://user-images.githubusercontent.com/9683576/173399981-44d4f46c-2207-4cc8-9d3d-75d91e007439.png)

nothing happens, and the `settings.json` file is not changed at all. i don't believe this is a code-server specific issue, because it works as expected in Coder Classic (with the same version `4.4.0`).

## Steps to Reproduce

1. Create workspace using `coder` template
2. Open code-server in browser
3. Command Palette > Color Theme > new color

### Expected

Changes themes.

###  Actual

Doesn't.

### Video

https://user-images.githubusercontent.com/3806031/173402535-030afd99-2c16-474e-9308-c79bf8415ad7.mov

### Logs

```javascript
  ERR Unable to resolve nonexistent file '/home/coder/.vscode-server/extensions': Error: Unable to resolve nonexistent file '/home/coder/.vscode-server/extensions'
    at d.resolve (/usr/lib/code-server/lib/vscode/out/vs/server/node/server.main.js:80:19769)
    at async i.scanExtensionsInLocation (/usr/lib/code-server/lib/vscode/out/vs/server/node/server.main.js:138:85457)
    at async Promise.all (index 1)
    at async i.scanUserExtensions (/usr/lib/code-server/lib/vscode/out/vs/server/node/server.main.js:138:81230)
    at async Promise.all (index 2)
    at async i.scanExtensions (/usr/lib/code-server/lib/vscode/out/vs/server/node/server.main.js:138:80970)
```

**Comment by jsjoeio** [comment]
I was able to reproduce this.

**Comment by jsjoeio** [comment]
cc @misskniss

**Comment by kylecarbs** [comment]
Certainly related to #2779

**Comment by kylecarbs** [comment]
Tracking this in #2779!
