### ISSUE TITLE
JetBrains Gateway 2022.2 EAP fails to connect over SSH

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder#2755]
relates to #1580 

@mark-theshark was unable to get this working on macOS Big Sur and Monterey

@f0ssel had trouble on Windows (logs in #1580)

**Comment by spikecurtis** [comment]
I'm also having problems on MacOS

```
2022-07-01 12:34:16,029 [ 113339]   WARN - #c.i.s.i.s.sshj - Failed to connect. Brief info: SSH connection to coder@coder.dogfood:22
 * With altered connection settings:
  - authMethods: PublicKey(privateKeys=[/Users/spike/.ssh/id_rsa, /Users/spike/.ssh/id_dsa, /Users/spike/.ssh/id_ecdsa, /Users/spike/.ssh/id_ed25519, /Users/spike/.ssh/id_xmss], agent=ALL), Password, KeyboardInteractive
  - connectTimeout: PT10S
  - hostKeyVerifier: OpenSSH-like host key verifier (knownHostsFile=[/dev/null], strictHostKeyChecking=NO, hashKnownHosts=false)
  - proxyConfig: Command(command="/Users/spike/bin/coder" --global-config "/Users/spike/Library/Application Support/coderv2" ssh --stdio dogfood)
  - user: coder
 * With auth agent ssh-agent[/private/tmp/com.apple.launchd.wkUzOjhAWF/Listeners]
net.schmizz.sshj.transport.TransportException: Timeout expired
	at net.schmizz.sshj.transport.TransportException$1.chain(TransportException.java:33)
	at net.schmizz.sshj.transport.TransportException$1.chain(TransportException.java:27)
	at net.schmizz.concurrent.Promise.retrieve(Promise.java:139)
	at net.schmizz.concurrent.Event.await(Event.java:105)
	at net.schmizz.sshj.transport.KeyExchanger.waitForDone(KeyExchanger.java:148)
	at net.schmizz.sshj.transport.KeyExchanger.startKex(KeyExchanger.java:143)
	at net.schmizz.sshj.transport.TransportImpl.doKex(TransportImpl.java:254)
	at net.schmizz.sshj.SSHClient.doKex(SSHClient.java:825)
	at net.schmizz.sshj.SSHClient.onConnect(SSHClient.java:813)
	at net.schmizz.sshj.SocketClient.connect(SocketClient.java:69)
	at com.intellij.ssh.impl.sshj.SshjConnectionUtilKt.connectPlatform(SshjConnectionUtil.kt:835)
	at com.intellij.ssh.impl.sshj.SshjConnectionUtilKt.access$connectPlatform(SshjConnectionUtil.kt:1)
	at com.intellij.ssh.impl.sshj.SshjConnectionUtilKt$setUpSessionForSshJ$8.run(SshjConnectionUtil.kt:223)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.util.concurrent.TimeoutException: Timeout expired
	... 19 more
2022-07-01 12:34:16,038 [ 113348]   INFO - #c.i.s.i.s.sshj - Disconnected - BY_APPLICATION
2022-07-01 12:34:16,043 [ 113353]   WARN - #c.i.s.ProxyCommand - Process[pid=67757, exitValue=143] exited with code 143
2022-07-01 12:34:16,046 [ 113356]   WARN - #c.i.s.u.u.SshCredentialsEditorEx - net.schmizz.sshj.transport.TransportException: Timeout expired
com.intellij.ssh.SshException: net.schmizz.sshj.transport.TransportException: Timeout expired
	at com.intellij.ssh.impl.sshj.SshjConnectionUtilKt.setUpSessionForSshJ(SshjConnectionUtil.kt:253)
	at com.intellij.ssh.impl.SshConnection.doSshjSshConnection(SshConnection.kt:211)
	at com.intellij.ssh.impl.SshConnection.access$doSshjSshConnection(SshConnection.kt:27)
	at com.intellij.ssh.impl.SshConnection$createSshSessionForSshj$1.invoke(SshConnection.kt:204)
	at com.intellij.ssh.impl.SshConnection$createSshSessionForSshj$1.invoke(SshConnection.kt:27)
	at com.intellij.ssh.Ssh.wrapBlockingSshCall(ssh.kt:386)
	at com.intellij.ssh.Ssh.wrapBlockingSshCall$default(ssh.kt:369)
	at com.intellij.ssh.impl.SshConnection.createSshSessionForSshj(SshConnection.kt:201)
	at com.intellij.ssh.impl.SshConnection.access$createSshSessionForSshj(SshConnection.kt:27)
	at com.intellij.ssh.impl.SshConnection$checkCanAuthenticate$1.invoke(SshConnection.kt:136)
	at com.intellij.ssh.impl.SshConnection$checkCanAuthenticate$1.invoke(SshConnection.kt:27)
	at com.intellij.ssh.Ssh.wrapBlockingSshCall(ssh.kt:386)
	at com.intellij.ssh.Ssh.wrapBlockingSshCall$default(ssh.kt:369)
	at com.intellij.ssh.impl.SshConnection.checkCanAuthenticate(SshConnection.kt:131)
	at com.intellij.ssh.SshConnectionService.checkCanAuthenticate(SshConnectionService.kt:210)
	at com.intellij.ssh.Ssh.checkCanAuthenticate(ssh.kt:255)
	at com.intellij.ssh.Ssh.access$checkCanAuthenticate(ssh.kt:1)
	at com.intellij.ssh.ConnectionBuilder.checkCanAuthenticate(ssh.kt:107)
	at com.intellij.ssh.ui.unified.SshCredentialsEditorEx$1.lambda$actionPerformed$0(SshCredentialsEditorEx.java:72)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:297)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: net.schmizz.sshj.transport.TransportException: Timeout expired
	at net.schmizz.sshj.transport.TransportException$1.chain(TransportException.java:33)
	at net.schmizz.sshj.transport.TransportException$1.chain(TransportException.java:27)
	at net.schmizz.concurrent.Promise.retrieve(Promise.java:139)
	at net.schmizz.concurrent.Event.await(Event.java:105)
	at net.schmizz.sshj.transport.KeyExchanger.waitForDone(KeyExchanger.java:148)
	at net.schmizz.sshj.transport.KeyExchanger.startKex(KeyExchanger.java:143)
	at net.schmizz.sshj.transport.TransportImpl.doKex(TransportImpl.java:254)
	at net.schmizz.sshj.SSHClient.doKex(SSHClient.java:825)
	at net.schmizz.sshj.SSHClient.onConnect(SSHClient.java:813)
	at net.schmizz.sshj.SocketClient.connect(SocketClient.java:69)
	at com.intellij.ssh.impl.sshj.SshjConnectionUtilKt.connectPlatform(SshjConnectionUtil.kt:835)
	at com.intellij.ssh.impl.sshj.SshjConnectionUtilKt.access$connectPlatform(SshjConnectionUtil.kt:1)
	at com.intellij.ssh.impl.sshj.SshjConnectionUtilKt$setUpSessionForSshJ$8.run(SshjConnectionUtil.kt:223)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	... 7 more
Caused by: java.util.concurrent.TimeoutException: Timeout expired
	... 19 more
```

**Comment by mafredri** [comment]
This issue is also being tracked on the JetBrains issue tracker: https://youtrack.jetbrains.com/issue/IDEA-297742

**Comment by spikecurtis** [comment]
I think we should close this in favor of #3125 since the EAP is no longer distributed, and the JetBrains issue appears to be fixed.
