### ISSUE TITLE
Crash while clicking Workspaces -- loading chunk 116 failed

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder#3234]
Hit after clicking "Workspaces" on top navbar on Dogfood
[Coder v0.8.1-devel+6f93acd9](https://github.com/coder/coder/commit/6f93acd9641878d7f9df228fcfb9c00366eb36fc)

```
======================= STACK TRACE ========================

Loading chunk 116 failed.
(missing: https://dev.coder.com/bundle.d9398e33aad865ac95e7.js)
(missing: https://dev.coder.com/bundle.d9398e33aad865ac95e7.js)
    at o.f.j (https://dev.coder.com/bundle.c74df17e017a3a4fe749.js:2:919379)
    at https://dev.coder.com/bundle.c74df17e017a3a4fe749.js:2:916515
    at Array.reduce (<anonymous>)
    at o.e (https://dev.coder.com/bundle.c74df17e017a3a4fe749.js:2:916493)
    at https://dev.coder.com/bundle.c74df17e017a3a4fe749.js:2:1308984
    at M (https://dev.coder.com/bundle.c74df17e017a3a4fe749.js:2:739476)
    at Hs (https://dev.coder.com/bundle.c74df17e017a3a4fe749.js:2:696527)
    at Al (https://dev.coder.com/bundle.c74df17e017a3a4fe749.js:2:683224)
    at kl (https://dev.coder.com/bundle.c74df17e017a3a4fe749.js:2:683152)
    at Cl (https://dev.coder.com/bundle.c74df17e017a3a4fe749.js:2:683015)

============================================================
```

**Comment by kylecarbs** [comment]
I believe this was fixed by parsing the errors properly.
