### ISSUE TITLE
Installation instructions on NixOS

### ISSUE THREAD

**Issue by GuillaumeDesforges** [coder/coder#3719]
For now, the most advertised way to install coder is using the magic installer.

I would like to install it on my NixOS machine, so I can't use it.

**Comment by GuillaumeDesforges** [comment]
I'm trying to package it.

I think it's easier to split building the parts separately.
For now, just trying to build `site` fails:

```nix
{ mkYarnPackage
, fetchFromGitHub
, runCommand
}:
let 
  version = "0.8.7";

  repoSrc = fetchFromGitHub {
    owner = "coder";
    repo = "coder";
    rev = "v${version}";
    sha256 = "0gQRr//we02YwBYspU8Y0/lvn38ylOorlKbva/R7nfM=";
  };
in
mkYarnPackage rec {
  pname = "coder";
  inherit version;
  src = runCommand (repoSrc.name + "-site") {} ''
    mkdir $out
    cp -R ${repoSrc}/site/* $out
  '';
}
```

gives

```
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/dfmgjr05250w227wnx79pbpssb6vkm6d-source-site
source root is source-site
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
@nix { "action": "setPhase", "phase": "buildPhase" }
building
no Makefile, doing nothing
@nix { "action": "setPhase", "phase": "installPhase" }
installing
fixup_bin: Processing  coder-v2
node:internal/fs/utils:345
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/nix/store/rxdf5ksm53s30y4l3r6bw7d0q86ms9fp-coder-v2-0.8.7/libexec/coder-v2/node_modules/coder-v2/package.json'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at processPackage (/nix/store/7nscwnnsi2mcx4wmm9b1scbpm2ksir3p-fixup_bin.js:19:37)
    at /nix/store/7nscwnnsi2mcx4wmm9b1scbpm2ksir3p-fixup_bin.js:52:3
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/nix/store/7nscwnnsi2mcx4wmm9b1scbpm2ksir3p-fixup_bin.js:51:22)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/nix/store/rxdf5ksm53s30y4l3r6bw7d0q86ms9fp-coder-v2-0.8.7/libexec/coder-v2/node_modules/coder-v2/package.json'
}
```

**Comment by kylecarbs** [comment]
There isn't a `package.json` at the root, it's in `site/package.json`. If I read this error correctly, it's looking at the wrong dir.

**Comment by GuillaumeDesforges** [comment]
> There isn't a `package.json` at the root, it's in `site/package.json`. If I read this error correctly, it's looking at the wrong dir.

Thanks for your fast response.

In the Nix derivation I've specified, I'm trying indeed to build only the fronted. To that end, I specify to `mkYarnPackage` a `src` which only contains the `site/` directory:

```nix
src = runCommand (repoSrc.name + "-site") {} ''
    mkdir $out
    cp -R ${repoSrc}/site/* $out
  '';
```

I can build this and inspect: it only contains the content of `site/`.

Now, the output folder has:

```
$ l /nix/store/rxdf5ksm53s30y4l3r6bw7d0q86ms9fp-coder-v2-0.8.7/libexec/coder-v2/node_modules/
total 12K
drwxr-xr-x 2 nixbld1 nixbld 4.0K Aug 27 15:53 .
drwxr-xr-x 4 nixbld1 nixbld 4.0K Aug 27 15:53 ..
lrwxrwxrwx 1 nixbld1 nixbld   13 Aug 27 15:53 coder-v2 -> deps/coder-v2
-rw-r--r-- 1 nixbld1 nixbld  206 Aug 27 15:53 .yarn-integrity
```

and `coder-v2 -> deps/coder-v2` seems to be broken (it's displayed in red on ls).

**Comment by kylecarbs** [comment]
@GuillaumeDesforges another Coder user has created a Nix flake here: https://github.com/denbeigh2000/coder-flake. Let me know if that works!
