### ISSUE TITLE
Strange crash with http api

### ISSUE THREAD

**Issue by geiseri** [coder/coder#4874]
I am not sure what causes this crash, it seems to happen overnight.  I think it might be when my computer goes to sleep and I have a code-server instance open.  I am still trying to look for a pattern though.  Here is the backtrace:

```
coder_1     | 2022-11-03 03:09:35.061 [INFO]    (coderd.tailnet)        <./tailnet/conn.go:456> (*Conn).sendNode.func1 sending node     {"node": {"id": 3717680930837363476, "as_of": "2022-11-03T03:09:35.061114673Z", "key": "nodekey:357255ce83fb4d8cfb02c20e8b0d93353932fb320e5857533e3843819b80eb56", "disco": "discokey:54607573a3873ca46a0d91ef5c03ad9bed60c7d36286f1885fb9558b4899a914", "preferred_derp": 999, "derp_latency": {"999-v4": 0.02779241}, "addresses": ["fd7a:115c:a1e0:45f2:befb:d885:755b:d41d/128"], "allowed_ips": ["fd7a:115c:a1e0:45f2:befb:d885:755b:d41d/128"], "endpoints": ["98.115.106.14:48278", "172.19.0.4:48278"]}}
coder_1     | 2022-11-03 03:10:50.080 [INFO]    (coderd.tailnet)        <./tailnet/conn.go:200> NewConn.func3   wireguard status        {"status": "\u0026{AsOf:2022-11-03 03:10:50.080217801 +0000 UTC m=+47136.287668416 Peers:[{TxBytes:1501192 RxBytes:6059288 LastHandshake:2022-11-03 03:10:00.071864476 +0000 UTC NodeKey:nodekey:86a9d7a643e782c82e56ecd37788ed7f8be5d3382f5bc0ee5d72570c3d36c933}] LocalAddrs:[{Addr:98.115.106.14:48278 Type:stun} {Addr:172.19.0.4:48278 Type:local}] DERPs:1}", "err": null}
coder_1     | 2022-11-03 03:10:50.080 [INFO]    (coderd.tailnet)        <./tailnet/conn.go:456> (*Conn).sendNode.func1 sending node     {"node": {"id": 3717680930837363476, "as_of": "2022-11-03T03:10:50.080217801Z", "key": "nodekey:357255ce83fb4d8cfb02c20e8b0d93353932fb320e5857533e3843819b80eb56", "disco": "discokey:54607573a3873ca46a0d91ef5c03ad9bed60c7d36286f1885fb9558b4899a914", "preferred_derp": 999, "derp_latency": {"999-v4": 0.02779241}, "addresses": ["fd7a:115c:a1e0:45f2:befb:d885:755b:d41d/128"], "allowed_ips": ["fd7a:115c:a1e0:45f2:befb:d885:755b:d41d/128"], "endpoints": ["98.115.106.14:48278", "172.19.0.4:48278"]}}
coder_1     | panic: runtime error: invalid memory address or nil pointer dereference
coder_1     | [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x6831b6]
coder_1     |
coder_1     | goroutine 3970823 [running]:
coder_1     | bufio.(*Writer).Flush(0xc0002481c0)
coder_1     |   /opt/hostedtoolcache/go/1.19.2/x64/src/bufio/bufio.go:629 +0x56
coder_1     | net/http.(*response).Flush(0xc00026c540)
coder_1     |   /opt/hostedtoolcache/go/1.19.2/x64/src/net/http/server.go:1706 +0x3a
coder_1     | github.com/coder/coder/coderd/tracing.(*StatusWriter).Flush(0x7f46c50717c0?)
coder_1     |   /home/runner/work/coder/coder/coderd/tracing/status_writer.go:81 +0x35
coder_1     | github.com/coder/coder/coderd/httpapi.ServerSentEventSender.func1()
coder_1     |   /home/runner/work/coder/coder/coderd/httpapi/httpapi.go:206 +0x202
coder_1     | created by github.com/coder/coder/coderd/httpapi.ServerSentEventSender
coder_1     |   /home/runner/work/coder/coder/coderd/httpapi/httpapi.go:191 +0x37d
traefik_1   | 2022/11/03 03:22:22 reverseproxy.go:490: httputil: ReverseProxy read error during body copy: unexpected EOF
```

I have included the trafik note because it looks like it was with the HTTP reverse proxy.   One thing I did note is that there seems to be  regular traffic at least every minute or two.  In this case it seems like the delay is almost 20min.  I am not sure if that is around the time of my desktop going to sleep, but its possible.   Sorry for yet another vague "something happened" report :(

**Comment by coadler** [comment]
This should be fixed in https://github.com/coder/coder/pull/4821 and included in the latest release!

**Comment by geiseri** [comment]
haha!  talk about turnaround ;)
