### ISSUE TITLE
flaky: wsconncache found unexpected goroutines

### ISSUE THREAD

**Issue by mtojek** [coder/coder#5302]
Spotted in:
https://github.com/coder/coder/actions/runs/3628078862/jobs/6119057615
https://github.com/coder/coder/actions/runs/3638729490/jobs/6141276331

```
goleak: Errors on successful test run: found unexpected goroutines:
[Goroutine 1128 in state chan receive, with gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*listenContext).performHandshake on top of the stack:
goroutine 1128 [chan receive]:
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*listenContext).performHandshake(0xc000cd23c0?, 0xc0002d90e0?, {0x4c4, 0x5, 0x1, 0x9e8cbd32, 0x0, 0x1, 0x0}, 0xc00072ab10, ...)
	/home/runner/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20220817001344-846276b3dbc5/pkg/tcpip/transport/tcp/accept.go:318 +0x248
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*ForwarderRequest).CreateEndpoint(0xc001057d80, 0x30?)
	/home/runner/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20220817001344-846276b3dbc5/pkg/tcpip/transport/tcp/forwarder.go:158 +0x127
tailscale.com/wgengine/netstack.(*Impl).acceptTCP.func2({0x0, 0x0, 0xc000012108?})
	/home/runner/go/pkg/mod/github.com/coder/tailscale@v1.1.1-0.202211[172](https://github.com/coder/coder/actions/runs/3628078862/jobs/6119057615#step:9:173)04504-2d6503f027c3/wgengine/netstack/netstack.go:812 +0x67
tailscale.com/wgengine/netstack.(*Impl).acceptTCP(0xc00019b680, 0xc001057d80)
	/home/runner/go/pkg/mod/github.com/coder/tailscale@v1.1.1-0.20221117204504-2d6503f027c3/wgengine/netstack/netstack.go:900 +0xa56
created by gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*Forwarder).HandlePacket
	/home/runner/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20220817001344-846276b3dbc5/pkg/tcpip/transport/tcp/forwarder.go:97 +0x390
]
FAIL	github.com/coder/coder/coderd/wsconncache	2.438s

DONE 2510 tests, 19 skipped, 1 failure in 55.687s
Error: Process completed with exit code 1.
```

**Comment by mtojek** [comment]
I investigated this problem a bit, but unfortunately, didn't manage to reproduce it locally on OSX or Linux.

It seems that `tailscale` prepares the `gvisor` transport to process the request, but I can't confirm what kind of request is it. I presume that `tailscale` routine might be already closed, but `gvisor` routine hangs on [channel](https://github.com/google/gvisor/blob/master/pkg/tcpip/transport/tcp/accept.go#L315-L318).

If we consider [another issue](https://github.com/google/gvisor/issues/837), I don't think that this is something we can solve.

**Comment by mtojek** [comment]
Let's reopen it if https://github.com/coder/coder/pull/5348 doesn't help.
