### ISSUE TITLE
devcontainer support

### ISSUE THREAD

**Issue by bpmct** [coder/coder#5559]
There is a neat way to [use Coder with the devcontainer CLI](https://github.com/bpmct/coder-templates/blob/1287f9acac0635e8b725d0eadd59d3daabc600a3/gcp-devcontainer/main.tf#L110-L132), but it would be great if the Coder agent had first class support for running workspaces via a devcontainer.

---

> **Note**: We now have docs on using our [Devcontainers Alpha](https://coder.com/docs/v2/latest/templates/devcontainers).

**Comment by kylecarbs** [comment]
To do this, we can create a `devcontainer` Terraform provider.

For Docker, we can use the `devcontainers/cli` repository to build as expected.

For Kubernetes, we can generate a manifest from the devcontainer syntax and utilize Kaniko to dynamically build images. This allows us to place the user inside the image. Kaniko operates by maintaining an empty rootfs within a container and storing its contents in `/kaniko`. This approach is ideal for our needs as it enables dynamic image building. However, it is important to note that not all options in Kubernetes may be supported (especially privileged ones). Despite this limitation, this should work for the majority of use cases.

**Comment by ammario** [comment]
This feature would ease the transition from local to remote development. We should be able to implement at the terraform-level, similar to #5314.

**Comment by ammario** [comment]
Per @kylecarbs, release ETA is end of next week.

**Comment by cguentherTUChemnitz** [comment]
Let me shortly describe a scenario here, where this would help alot in my eyes.

We have several projects with different tooling and setups. Vscode is able to bundle this very nicely directly in the project using .devcontainers and .vscode/settings inside every project bringing up an pre-configured environment in the same way for every developer. This approach still has the problem, that every developer needs a machine with good docker support and performance. But especially for app-development this kind-off falls apart, since we have pre-packaged android environments, but need to run for ios on baremetal macos system. MacOS seems to have crappy docker performance using docker-desktop compared to native docker support of linux, espacially when filesystem translations between host-os filesystem apfs and docker-desktop internal filesystem (e.g. ext4) comes into play (which is the case of the mapped project folder in devcontainers). So this meens at the moment, that we need 2 distinct machines for app-development per developer. One for macOS based for ios development and one for everything else, where the devcointer approach works nice. 

In my eyes this problem can be more or less completely avoided, when coder runs on a baremetal linux machine and is able to open git projects in vscode with devcontainer support on project level. Then the app-developer can use just the browser accessing coder for every development task except ios dev, avoiding buy, setup and maintenance of a second machine per developer.

Is that scope of the devcontainer support idea here in coder?

**Comment by bodiroga** [comment]
> Per @kylecarbs, release ETA is end of next week.

Has there been any progress around this? 😉

**Comment by Tirzono** [comment]
Looks like there has been some work done in #8256 to add documentation how to work with devcontainers in templates.

**Comment by bpmct** [comment]
Yep! You can try this today by following those docs. We're tightening our integration with GitHub to make it easier to work with private repos, which is why it is labeled as `alpha` but it all works today.

**Comment by bpmct** [comment]
Feedback is also welcome here or on the [envbuilder](https://github.com/coder/envbuilder) repo!

**Comment by Shocktrooper** [comment]
@bpmct Can we add instructions/examples on how to use devcontainers with rootless container variants like rootless podman. We want to allow for devcontainers but don't want to give user controlled pods privileged mode.

**Comment by xangelix** [comment]
are the `customizations.vscode.settings` and `customizations.vscode.extensions` fields planned to be supported?
I believe this is all that is needed for gitpod feature parity other than user-level environment variables which are unrelated to devcontainers.

**Comment by Shocktrooper** [comment]
> are the `customizations.vscode.settings` and `customizations.vscode.extensions` fields planned to be supported? I believe this is all that is needed for gitpod feature parity other than user-level environment variables which are unrelated to devcontainers.

@xangelix Couldn't you just use the dotfile capability that already exists to inject user level env vars among other things?

**Comment by juanbits** [comment]
i have a selfhosted coder-oss, how i can use the devcontainers functionality?

**Comment by xangelix** [comment]
> > are the `customizations.vscode.settings` and `customizations.vscode.extensions` fields planned to be supported? I believe this is all that is needed for gitpod feature parity other than user-level environment variables which are unrelated to devcontainers.
> 
> @xangelix Couldn't you just use the dotfile capability that already exists to inject user level env vars among other things?

kind of, but also kind of not
a lot of the variables I'm thinking of would be user-level secrets that gitpod allows you to set in your user settings, similar to a CI/CD

afaik all of the secret management options in coder right now are not well suited to more ephemeral devcontainer/envbuilder templates

**Comment by Shocktrooper** [comment]
@xangelix If you can use a terraform datasource to grab secrets from an external system that could work.  I plan to do that with hashicorp vault.

**Comment by juanbits** [comment]
i try to use devcontainer in my selfhosted sso, but it appers not continue, keeps on the line 13 as shown 
![Screenshot_2023-07-29_00-49-56](https://github.com/coder/coder/assets/5168033/bf62b35a-1095-4e40-8262-07dd254c5cf2)

**Comment by kylecarbs** [comment]
@juanbits super odd. Could you check to see if the container is dying early for some reason? In that case, the logs may not appear there.

**Comment by juanbits** [comment]
@kylecarbs this are the container logs:
```
envbuilder - Build development environments from repositories in a container
#1: 📦 Cloning https://github.com/myrepo to /workspaces/python-gunicorn-django-devcontainer...
#1: 📦 The repository already exists! [28.678452ms]
#2: 🏗️ Building image...
#2: Retrieving image manifest codercom/enterprise-base:ubuntu
#2: Retrieving image codercom/enterprise-base:ubuntu from registry index.docker.io
#2: Built cross stage deps: map[]
#2: Retrieving image manifest codercom/enterprise-base:ubuntu
#2: Returning cached image manifest
#2: Executing 0 build triggers
#2: Building stage 'codercom/enterprise-base:ubuntu' [idx: '0', base-idx: '-1']
#2: Initializing snapshotter ...
#2: Taking snapshot of full filesystem...
fatal error: runtime: out of memory

runtime stack:
runtime.throw({0x1b72a82?, 0x0?})
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/panic.go:1047 +0x5d fp=0x7ffca9a67428 sp=0x7ffca9a673f8 pc=0x4391bd
runtime.sysMapOS(0xc035400000, 0x20000000?)
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/mem_linux.go:187 +0x11b fp=0x7ffca9a67470 sp=0x7ffca9a67428 pc=0x41849b
runtime.sysMap(0x2b92620?, 0xc3ffffffff?, 0x2ba27b8?)
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/mem.go:142 +0x35 fp=0x7ffca9a674a0 sp=0x7ffca9a67470 pc=0x417e75
runtime.(*mheap).grow(0x2b92620, 0x10000?)
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/mheap.go:1522 +0x252 fp=0x7ffca9a67518 sp=0x7ffca9a674a0 pc=0x429f52
runtime.(*mheap).allocSpan(0x2b92620, 0x10000, 0x0, 0x46?)
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/mheap.go:1243 +0x1b7 fp=0x7ffca9a675b0 sp=0x7ffca9a67518 pc=0x429697
runtime.(*mheap).alloc.func1()
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/mheap.go:961 +0x65 fp=0x7ffca9a675f8 sp=0x7ffca9a675b0 pc=0x429145
runtime.systemstack()
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/asm_amd64.s:496 +0x49 fp=0x7ffca9a67600 sp=0x7ffca9a675f8 pc=0x46bb09

goroutine 1 [running]:
runtime.systemstack_switch()
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/asm_amd64.s:463 fp=0xc000900258 sp=0xc000900250 pc=0x46baa0
runtime.(*mheap).alloc(0x20000000?, 0x10000?, 0x8?)
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/mheap.go:955 +0x65 fp=0xc0009002a0 sp=0xc000900258 pc=0x429085
runtime.(*mcache).allocLarge(0x8000?, 0x20000000, 0x1)
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/mcache.go:234 +0x85 fp=0xc0009002e8 sp=0xc0009002a0 pc=0x416f05
runtime.mallocgc(0x20000000, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/malloc.go:1053 +0x4fe fp=0xc000900350 sp=0xc0009002e8 pc=0x40dc1e
runtime.growslice(0x0, 0xc0178d9308?, 0x0?, 0x156?, 0x41770d?)
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/slice.go:266 +0x4a8 fp=0xc0009003b0 sp=0xc000900350 pc=0x451008
bytes.growSlice({0xc025080000, 0x10000000, 0x8000?}, 0xc000900490?)
	/opt/hostedtoolcache/go/1.20.5/x64/src/bytes/buffer.go:240 +0x9b fp=0xc000900430 sp=0xc0009003b0 pc=0x4b563b
bytes.(*Buffer).grow(0xc0187261e0, 0x8000)
	/opt/hostedtoolcache/go/1.20.5/x64/src/bytes/buffer.go:142 +0x14f fp=0xc000900468 sp=0xc000900430 pc=0x4b502f
bytes.(*Buffer).Write(0xc0187261e0, {0xc00211a000, 0x8000, 0x7f68ca599178?})
	/opt/hostedtoolcache/go/1.20.5/x64/src/bytes/buffer.go:170 +0x66 fp=0xc000900498 sp=0xc000900468 pc=0x4b5226
archive/tar.(*regFileWriter).Write(0xc0020c88b8, {0xc00211a000?, 0x8000, 0xc002e81b00?})
	/opt/hostedtoolcache/go/1.20.5/x64/src/archive/tar/writer.go:500 +0x69 fp=0xc0009004d0 sp=0xc000900498 pc=0xa31e89
archive/tar.(*Writer).Write(0xc017dabc00, {0xc00211a000?, 0xc017dabc00?, 0x7f68ca59fbb8?})
	/opt/hostedtoolcache/go/1.20.5/x64/src/archive/tar/writer.go:438 +0x4a fp=0xc000900518 sp=0xc0009004d0 pc=0xa31c0a
io.copyBuffer({0x1e32060, 0xc017dabc00}, {0x1e37e20, 0xc0020c88d0}, {0x0, 0x0, 0x0})
	/opt/hostedtoolcache/go/1.20.5/x64/src/io/io.go:429 +0x204 fp=0xc000900598 sp=0xc000900518 pc=0x4adae4
io.Copy(...)
	/opt/hostedtoolcache/go/1.20.5/x64/src/io/io.go:386
io.CopyN({0x1e32060, 0xc017dabc00}, {0x1e32040?, 0xc002e81b00}, 0xbb0bd0)
	/opt/hostedtoolcache/go/1.20.5/x64/src/io/io.go:362 +0x9a fp=0xc0009005e8 sp=0xc000900598 pc=0x4ad79a
github.com/google/go-containerregistry/pkg/v1/mutate.layerTime({0x1e54528?, 0xc000f35500?}, {0x2bab540?, 0x40d59e?, 0x0?})
	/home/runner/go/pkg/mod/github.com/google/go-containerregistry@v0.14.0/pkg/v1/mutate/mutate.go:481 +0x487 fp=0xc000900718 sp=0xc0009005e8 pc=0x121d047
github.com/google/go-containerregistry/pkg/v1/mutate.Time({0x1e5a850, 0xc0004a60e0}, {0xc0004a6070?, 0xc00017ac00?, 0x0?})
	/home/runner/go/pkg/mod/github.com/google/go-containerregistry@v0.14.0/pkg/v1/mutate/mutate.go:387 +0x207 fp=0xc0009008e8 sp=0xc000900718 pc=0x121c387
github.com/google/go-containerregistry/pkg/v1/mutate.Canonical({0x1e5a850?, 0xc0004a60e0?})
	/home/runner/go/pkg/mod/github.com/google/go-containerregistry@v0.14.0/pkg/v1/mutate/mutate.go:509 +0x2d fp=0xc000900940 sp=0xc0009008e8 pc=0x121d76d
github.com/GoogleContainerTools/kaniko/pkg/executor.DoBuild(0xc00041d680)
	/home/runner/go/pkg/mod/github.com/coder/kaniko@v0.0.0-20230630144655-c825422ea1d2/pkg/executor/build.go:704 +0xee5 fp=0xc000900f10 sp=0xc000900940 pc=0x152fde5
github.com/coder/envbuilder.Run.func7()
	/home/runner/work/envbuilder/envbuilder/envbuilder.go:484 +0x525 fp=0xc0009011a8 sp=0xc000900f10 pc=0x16fac85
github.com/coder/envbuilder.Run({_, _}, {{0x0, 0x0}, {0xc00005c00c, 0x60e}, {0x1b5219d, 0x7}, {0x0, 0x0}, ...})
	/home/runner/work/envbuilder/envbuilder/envbuilder.go:522 +0x221f fp=0xc000901a40 sp=0xc0009011a8 pc=0x16f83df
main.main.func1(0xc0004d8900, {0x1b4e6c3?, 0x0?, 0x0?})
	/home/runner/work/envbuilder/envbuilder/cmd/envbuilder/main.go:71 +0x498 fp=0xc000901d38 sp=0xc000901a40 pc=0x17135d8
github.com/spf13/cobra.(*Command).execute(0xc0004d8900, {0xc0000502c0, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x862 fp=0xc000901e70 sp=0xc000901d38 pc=0x1705bc2
github.com/spf13/cobra.(*Command).ExecuteC(0xc0004d8900)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd fp=0xc000901f28 sp=0xc000901e70 pc=0x170643d
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
	/home/runner/work/envbuilder/envbuilder/cmd/envbuilder/main.go:78 +0x54 fp=0xc000901f80 sp=0xc000901f28 pc=0x17130d4
runtime.main()
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/proc.go:250 +0x207 fp=0xc000901fe0 sp=0xc000901f80 pc=0x43bba7
runtime.goexit()
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000901fe8 sp=0xc000901fe0 pc=0x46db81

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/proc.go:381 +0xd6 fp=0xc000076fb0 sp=0xc000076f90 pc=0x43bfd6
runtime.goparkunlock(...)
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/proc.go:387
runtime.forcegchelper()
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/proc.go:305 +0xb0 fp=0xc000076fe0 sp=0xc000076fb0 pc=0x43be10
runtime.goexit()
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000076fe8 sp=0xc000076fe0 pc=0x46db81
created by runtime.init.6
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/proc.go:293 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/proc.go:381 +0xd6 fp=0xc000077780 sp=0xc000077760 pc=0x43bfd6
runtime.goparkunlock(...)
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/proc.go:387
runtime.bgsweep(0x0?)
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/mgcsweep.go:319 +0xde fp=0xc0000777c8 sp=0xc000077780 pc=0x425f9e
runtime.gcenable.func1()
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/mgc.go:178 +0x26 fp=0xc0000777e0 sp=0xc0000777c8 pc=0x41b206
runtime.goexit()
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000777e8 sp=0xc0000777e0 pc=0x46db81
created by runtime.gcenable
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x3bf1fba0071fe?, 0x185e614?, 0x0?, 0x0?, 0x0?)
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/proc.go:381 +0xd6 fp=0xc000077f70 sp=0xc000077f50 pc=0x43bfd6
runtime.goparkunlock(...)
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/proc.go:387
runtime.(*scavengerState).park(0x2b6ea80)
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/mgcscavenge.go:400 +0x53 fp=0xc000077fa0 sp=0xc000077f70 pc=0x423e73
runtime.bgscavenge(0x0?)
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/mgcscavenge.go:633 +0x65 fp=0xc000077fc8 sp=0xc000077fa0 pc=0x424465
runtime.gcenable.func2()
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/mgc.go:179 +0x26 fp=0xc000077fe0 sp=0xc000077fc8 pc=0x41b1a6
runtime.goexit()
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000077fe8 sp=0xc000077fe0 pc=0x46db81
created by runtime.gcenable
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/mgc.go:179 +0xaa

goroutine 5 [finalizer wait]:
runtime.gopark(0x0?, 0xc0007759e0?, 0x10?, 0xc2?, 0x1000000010?)
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/proc.go:381 +0xd6 fp=0xc00019ce28 sp=0xc00019ce08 pc=0x43bfd6
runtime.runfinq()
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/mfinal.go:193 +0x107 fp=0xc00019cfe0 sp=0xc00019ce28 pc=0x41a1c7
runtime.goexit()
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00019cfe8 sp=0xc00019cfe0 pc=0x46db81
created by runtime.createfing
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/mfinal.go:163 +0x45

goroutine 6 [select]:
runtime.gopark(0xc000078790?, 0x2?, 0x1?, 0x0?, 0xc000078774?)
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/proc.go:381 +0xd6 fp=0xc0000785f8 sp=0xc0000785d8 pc=0x43bfd6
runtime.selectgo(0xc000078790, 0xc000078770, 0x0?, 0x0, 0x0?, 0x1)
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/select.go:327 +0x7be fp=0xc000078738 sp=0xc0000785f8 pc=0x44bffe
github.com/golang/glog.(*fileSink).flushDaemon(0x2b6e778)
	/home/runner/go/pkg/mod/github.com/golang/glog@v1.1.0/glog_file.go:345 +0xcd fp=0xc0000787c8 sp=0xc000078738 pc=0x98f88d
github.com/golang/glog.init.1.func1()
	/home/runner/go/pkg/mod/github.com/golang/glog@v1.1.0/glog_file.go:163 +0x26 fp=0xc0000787e0 sp=0xc0000787c8 pc=0x98e8e6
runtime.goexit()
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000787e8 sp=0xc0000787e0 pc=0x46db81
created by github.com/golang/glog.init.1
	/home/runner/go/pkg/mod/github.com/golang/glog@v1.1.0/glog_file.go:163 +0x17f

goroutine 7 [GC worker (idle)]:
runtime.gopark(0x3bf22e8ba2cd4?, 0x0?, 0x0?, 0x0?, 0x0?)
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/proc.go:381 +0xd6 fp=0xc000078f50 sp=0xc000078f30 pc=0x43bfd6
runtime.gcBgMarkWorker()
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/mgc.go:1275 +0xf1 fp=0xc000078fe0 sp=0xc000078f50 pc=0x41cf71
runtime.goexit()
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000078fe8 sp=0xc000078fe0 pc=0x46db81
created by runtime.gcBgMarkStartWorkers
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/mgc.go:1199 +0x25

goroutine 14 [select]:
runtime.gopark(0xc0005bde98?, 0x4?, 0x80?, 0xf1?, 0xc0005bdd00?)
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/proc.go:381 +0xd6 fp=0xc0005bdad8 sp=0xc0005bdab8 pc=0x43bfd6
runtime.selectgo(0xc0005bde98, 0xc0005bdcf8, 0xc0002b2150?, 0x0, 0x19d1620?, 0x1)
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/select.go:327 +0x7be fp=0xc0005bdc18 sp=0xc0005bdad8 pc=0x44bffe
github.com/coder/coder/codersdk/agentsdk.StartupLogsSender.func1()
	/home/runner/go/pkg/mod/github.com/coder/coder@v0.24.2-0.20230630184129-6015319e9d30/codersdk/agentsdk/logs.go:126 +0x28a fp=0xc0005bdfe0 sp=0xc0005bdc18 pc=0xf14e2a
runtime.goexit()
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0005bdfe8 sp=0xc0005bdfe0 pc=0x46db81
created by github.com/coder/coder/codersdk/agentsdk.StartupLogsSender
	/home/runner/go/pkg/mod/github.com/coder/coder@v0.24.2-0.20230630184129-6015319e9d30/codersdk/agentsdk/logs.go:104 +0x19e

goroutine 15 [select]:
runtime.gopark(0xc0005bef28?, 0x2?, 0x0?, 0x0?, 0xc0005bef0c?)
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/proc.go:381 +0xd6 fp=0xc0005bed88 sp=0xc0005bed68 pc=0x43bfd6
runtime.selectgo(0xc0005bef28, 0xc0005bef08, 0x0?, 0x0, 0x0?, 0x1)
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/select.go:327 +0x7be fp=0xc0005beec8 sp=0xc0005bed88 pc=0x44bffe
io.(*pipe).read(0xc000499ce0, {0xc0005befa8, 0x1000, 0x0?})
	/opt/hostedtoolcache/go/1.20.5/x64/src/io/pipe.go:57 +0xb1 fp=0xc0005bef58 sp=0xc0005beec8 pc=0x4af0f1
io.(*PipeReader).Read(...)
	/opt/hostedtoolcache/go/1.20.5/x64/src/io/pipe.go:136
github.com/coder/envbuilder.Run.func2()
	/home/runner/work/envbuilder/envbuilder/envbuilder.go:268 +0x78 fp=0xc0005bffe0 sp=0xc0005bef58 pc=0x16fb798
runtime.goexit()
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0005bffe8 sp=0xc0005bffe0 pc=0x46db81
created by github.com/coder/envbuilder.Run
	/home/runner/work/envbuilder/envbuilder/envbuilder.go:265 +0xc9b

goroutine 118 [select]:
runtime.gopark(0xc0005c5f18?, 0x6?, 0x9a?, 0x0?, 0xc0005c5df4?)
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/proc.go:381 +0xd6 fp=0xc0005c5c18 sp=0xc0005c5bf8 pc=0x43bfd6
runtime.selectgo(0xc0005c5f18, 0xc0005c5de8, 0x1b508c9?, 0x0, 0xc0005c5dc0?, 0x1)
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/select.go:327 +0x7be fp=0xc0005c5d58 sp=0xc0005c5c18 pc=0x44bffe
net/http.(*http2clientStream).writeRequest(0xc01831e180, 0xc0002e7900)
	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/h2_bundle.go:8399 +0xa67 fp=0xc0005c5f90 sp=0xc0005c5d58 pc=0x6e7267
net/http.(*http2clientStream).doRequest(0xc0005c5fd0?, 0x11f36a4?)
	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/h2_bundle.go:8261 +0x1e fp=0xc0005c5fc0 sp=0xc0005c5f90 pc=0x6e67be
net/http.(*http2ClientConn).RoundTrip.func3()
	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/h2_bundle.go:8190 +0x2a fp=0xc0005c5fe0 sp=0xc0005c5fc0 pc=0x6e676a
runtime.goexit()
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0005c5fe8 sp=0xc0005c5fe0 pc=0x46db81
created by net/http.(*http2ClientConn).RoundTrip
	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/h2_bundle.go:8190 +0x34a

goroutine 49 [IO wait]:
runtime.gopark(0xfe56ff111465eee2?, 0xb?, 0x0?, 0x0?, 0x9?)
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/proc.go:381 +0xd6 fp=0xc0000f1608 sp=0xc0000f15e8 pc=0x43bfd6
runtime.netpollblock(0x4842e5?, 0x40482f?, 0x0?)
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/netpoll.go:527 +0xf7 fp=0xc0000f1640 sp=0xc0000f1608 pc=0x434497
internal/poll.runtime_pollWait(0x7f68cae06cc8, 0x72)
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/netpoll.go:306 +0x89 fp=0xc0000f1660 sp=0xc0000f1640 pc=0x467809
internal/poll.(*pollDesc).wait(0xc00041fe80?, 0xc000948000?, 0x0)
	/opt/hostedtoolcache/go/1.20.5/x64/src/internal/poll/fd_poll_runtime.go:84 +0x32 fp=0xc0000f1688 sp=0xc0000f1660 pc=0x529772
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.20.5/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc00041fe80, {0xc000948000, 0xc000, 0xc000})
	/opt/hostedtoolcache/go/1.20.5/x64/src/internal/poll/fd_unix.go:167 +0x299 fp=0xc0000f1720 sp=0xc0000f1688 pc=0x52ab59
net.(*netFD).Read(0xc00041fe80, {0xc000948000?, 0xc00094c07f?, 0x2019?})
	/opt/hostedtoolcache/go/1.20.5/x64/src/net/fd_posix.go:55 +0x29 fp=0xc0000f1768 sp=0xc0000f1720 pc=0x5decc9
net.(*conn).Read(0xc000012ff0, {0xc000948000?, 0x7f81?, 0xc00094c077?})
	/opt/hostedtoolcache/go/1.20.5/x64/src/net/net.go:183 +0x45 fp=0xc0000f17b0 sp=0xc0000f1768 pc=0x5f23c5
net.(*TCPConn).Read(0xc0000f1848?, {0xc000948000?, 0xc0020c9170?, 0x18?})
	<autogenerated>:1 +0x29 fp=0xc0000f17e0 sp=0xc0000f17b0 pc=0x604c69
crypto/tls.(*atLeastReader).Read(0xc0020c9170, {0xc000948000?, 0xc0020c9170?, 0x0?})
	/opt/hostedtoolcache/go/1.20.5/x64/src/crypto/tls/conn.go:788 +0x3d fp=0xc0000f1828 sp=0xc0000f17e0 pc=0x64899d
bytes.(*Buffer).ReadFrom(0xc00001d090, {0x1e32420, 0xc0020c9170})
	/opt/hostedtoolcache/go/1.20.5/x64/src/bytes/buffer.go:202 +0x98 fp=0xc0000f1880 sp=0xc0000f1828 pc=0x4b5498
crypto/tls.(*Conn).readFromUntil(0xc00001ce00, {0x1e380c0?, 0xc000012ff0}, 0x7f8e?)
	/opt/hostedtoolcache/go/1.20.5/x64/src/crypto/tls/conn.go:810 +0xe5 fp=0xc0000f18c0 sp=0xc0000f1880 pc=0x648b85
crypto/tls.(*Conn).readRecordOrCCS(0xc00001ce00, 0x0)
	/opt/hostedtoolcache/go/1.20.5/x64/src/crypto/tls/conn.go:617 +0x116 fp=0xc0000f1c20 sp=0xc0000f18c0 pc=0x646076
crypto/tls.(*Conn).readRecord(...)
	/opt/hostedtoolcache/go/1.20.5/x64/src/crypto/tls/conn.go:583
crypto/tls.(*Conn).Read(0xc00001ce00, {0xc0001c6000, 0x1000, 0xc0000f1cc0?})
	/opt/hostedtoolcache/go/1.20.5/x64/src/crypto/tls/conn.go:1316 +0x16f fp=0xc0000f1c90 sp=0xc0000f1c20 pc=0x64bf6f
bufio.(*Reader).Read(0xc0001c4060, {0xc0005ad0e0, 0x9, 0x2000?})
	/opt/hostedtoolcache/go/1.20.5/x64/src/bufio/bufio.go:237 +0x1bb fp=0xc0000f1cc8 sp=0xc0000f1c90 pc=0x6838fb
io.ReadAtLeast({0x1e32140, 0xc0001c4060}, {0xc0005ad0e0, 0x9, 0x9}, 0x9)
	/opt/hostedtoolcache/go/1.20.5/x64/src/io/io.go:332 +0x9a fp=0xc0000f1d10 sp=0xc0000f1cc8 pc=0x4ad5da
io.ReadFull(...)
	/opt/hostedtoolcache/go/1.20.5/x64/src/io/io.go:351
net/http.http2readFrameHeader({0xc0005ad0e0?, 0x9?, 0xc00216ab40?}, {0x1e32140?, 0xc0001c4060?})
	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/h2_bundle.go:1567 +0x6e fp=0xc0000f1d60 sp=0xc0000f1d10 pc=0x6c7e6e
net/http.(*http2Framer).ReadFrame(0xc0005ad0a0)
	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/h2_bundle.go:1831 +0x95 fp=0xc0000f1e10 sp=0xc0000f1d60 pc=0x6c86b5
net/http.(*http2clientConnReadLoop).run(0xc0000f1f98)
	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/h2_bundle.go:9187 +0x12e fp=0xc0000f1f60 sp=0xc0000f1e10 pc=0x6ebc8e
net/http.(*http2ClientConn).readLoop(0xc000003980)
	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/h2_bundle.go:9082 +0x6f fp=0xc0000f1fc8 sp=0xc0000f1f60 pc=0x6eb1af
net/http.(*http2Transport).newClientConn.func1()
	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/h2_bundle.go:7779 +0x26 fp=0xc0000f1fe0 sp=0xc0000f1fc8 pc=0x6e3da6
runtime.goexit()
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000f1fe8 sp=0xc0000f1fe0 pc=0x46db81
created by net/http.(*http2Transport).newClientConn
	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/h2_bundle.go:7779 +0xc3c

```

**Comment by kylecarbs** [comment]
An OOM! How much memory does your container have? I'm not sure we have a great answer when an OOM occurs, because we can't even send logs.

**Comment by juanbits** [comment]
@kylecarbs its a VPS, it have 2GB RAM

**Comment by ammario** [comment]
Let's take the OOM discussion to #8892
