### ISSUE TITLE
Connection issues with VS Code Remote SSH

### ISSUE THREAD

**Issue by NiklasRosenstein** [coder/coder#6112]
I'm unsure if this should rather be an issue in the Remote SSH extension, but I believe this is only an issue when connecting to a Coder workspace.

I often have issues connecting to my Coder Workspace via VS Code. For example just now, what finally prompted me to create this issue, I had one VS Code window connected to the workspace and it was working perfectly fine. I opened another window using `code ~/git/terraform/enginfra` and now both windows are stuck with load bars at the top left.

<img width="575" alt="image" src="https://user-images.githubusercontent.com/1318438/217605701-f26e65af-802a-4bf1-b4b2-05d88d556475.png">

In other instances, connecting to the workspace right after starting it again fails with an "Unable to resolve" error in the Remote SSH logs (whether that is connecting directly via the Remote SSH plugin or via the "VS Code Desktop" button/the Coder extension). The next time I encounter this I'll be sure to save the log. This particular issue seems to have been resolved by restarting my desktop, so it may have been a separate issue that has to do with VS Code + Remote SSH + Tailscale (we use a Tailscale VPN where the Coder service is reachable).

After the restart, and also in the case described above with the screenshot, leaving VS Code in the "Connecting" state seems to eventually work out successfully. In any of these cases, connecting to the Coder workspace via the Browser Terminal, via `ssh coder.dev` or `coder ssh dev` works just fine.

Any ideas to debug this are highly appreciated.

**Comment by NiklasRosenstein** [comment]
I just started getting the Resolve error again after I ran `code -a ../another-project`. The error message in the Remote SSH logs is:

```
[18:47:50.904] > local-server-1> Running ssh connection command: "-v -T -D 58462 -F /Users/niklas.rosenstein/.ssh/config coder.dev"
[18:47:50.931] > local-server-1> Spawned ssh, pid=15732
[18:47:50.935] stderr> OpenSSH_9.0p1, LibreSSL 3.3.6
[18:48:07.841] Terminating local server
[18:48:07.853] Resolver error: Error: Connecting with SSH timed out
	at g.Timeout (/Users/niklas.rosenstein/.vscode/extensions/ms-vscode-remote.remote-ssh-0.96.0/out/extension.js:1:584273)
	at Timeout._onTimeout (/Users/niklas.rosenstein/.vscode/extensions/ms-vscode-remote.remote-ssh-0.96.0/out/extension.js:1:629573)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)
[18:48:07.861] Local server exit: 15
[18:48:07.863] ------
```

But again, `ssh coder.dev` works just fine. Also replicating the same command that VS Code tries to run appears to run fine.

```
ssh -v -T -D 58462 -F /Users/niklas.rosenstein/.ssh/config coder.dev
```

**Comment by NiklasRosenstein** [comment]
Trying again now I get the following Remote SSH logs (without restarting my desktop as I did before when I encountered this Resolve error), and it eventually succeeds but it takes quite some time (> 2 minutes) to finish successfully.

```
[18:50:53.454] Spawned 17998
[18:50:53.532] > local-server-1> Running ssh connection command: "-v -T -D 58723 -F /Users/niklas.rosenstein/.ssh/config coder.dev"
[18:50:53.562] > local-server-1> Spawned ssh, pid=18302
[18:50:53.566] stderr> OpenSSH_9.0p1, LibreSSL 3.3.6
[18:50:54.230] stderr> debug1: Server host key: ssh-rsa SHA256:J3j7ZgmoPLOuEit+2ZCJbFK5wDtZdb6b0DeJuUgPEjw
[18:50:54.230] stderr> Warning: Permanently added 'coder.dev' (RSA) to the list of known hosts.
[18:50:54.270] stderr> Authenticated to coder.dev (via proxy) using "none".
[18:50:54.313] > ready: ce2639ecf548
[18:50:54.332] > Linux 5.4.0-1098-azure #104~18.04.2-Ubuntu SMP Tue Nov 29 12:13:35 UTC 2022
[18:50:54.332] Platform: linux
[18:50:54.352] > /bin/bash
[18:50:54.352] Shell: bash
[18:50:54.352] Creating bash subshell inside "bash"
[18:50:54.374] > bash version:  5.0.17(1)-release
[18:50:57.507] > ce2639ecf548: running
[18:50:57.522] > Acquiring lock on /home/coder/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/vscode-remote-lock.coder.e2816fe719a4026ffa1ee0189dc89bdfdbafb164
[18:50:57.524] > Found existing installation at /home/coder/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164...
> Checking /home/coder/.vscode-server/.e2816fe719a4026ffa1ee0189dc89bdfdbafb164.log and /home/coder/.vscode-server/.e2816fe719a4026ffa1ee0189dc89bdfdbafb164.pid for a running server
[18:50:57.525] > Looking for server with pid: 13774
[18:50:57.530] > Found running server...
[18:50:57.530] >  
> *
> * Visual Studio Code Server
[18:50:57.530] > *
> * By using the software, you agree to
> * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
> * the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
> *
>  
[ ... ]

[18:50:57.540] Remote server is listening on 45521
[18:50:57.540] Parsed server configuration: {"serverConfiguration":{"remoteListeningOn":{"port":45521},"osReleaseId":"ubuntu","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","display":"","tmpDir":"/tmp","platform":"linux","connectionToken":"111111aa-1a11-1111-a111-111111111a11"},"installUnpackCode":""}
[18:50:57.541] Persisting server connection details to /Users/niklas.rosenstein/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-61e4bf9b-e2816fe719a4026ffa1ee0189dc89bdfdbafb164-0.96.0/data.json
[18:50:57.543] Starting forwarding server. localPort 58733 -> socksPort 58723 -> remotePort 45521
[18:50:57.543] Forwarding server listening on 58733
[18:50:57.543] Waiting for ssh tunnel to be ready
[18:50:57.544] [Forwarding server 58733] Got connection 0
[18:50:57.544] Tunneled 45521 to local port 58733
[18:50:57.545] Resolved "ssh-remote+coder.dev" to "127.0.0.1:58733"
[18:50:57.549] ------




[18:50:57.556] [Forwarding server 58733] Got connection 1
[18:50:57.606] [Forwarding server 58733] Got connection 2
[18:50:58.006] [Forwarding server 58733] Got connection 3
```

**Comment by NiklasRosenstein** [comment]
We have Coder deployed in Kubernetes, and after some digging I hypothesized that our NGINX Ingress could be overloaded. Scaling that up and remediating some performance warnings caused by other services in the cluster, I think this has not been the root of the issue given that the issue persists.

**Comment by NiklasRosenstein** [comment]
Just upgraded from Coder 0.1.52 to 0.17.1 but the behavior stays the same.

**Comment by kylecarbs** [comment]
@NiklasRosenstein so sorry I missed this! Investigating now.

**Comment by kylecarbs** [comment]
@NiklasRosenstein try upgrading to 0.17.3... there was an issue in our networking code under high CPU load that caused a race condition where nodes might not be sent. I'm not sure why that'd specifically occur for your case, but it's worth a shot!

**Comment by NiklasRosenstein** [comment]
Hey @kylecarbs , thanks for your response! Early tests seem to indicate that the issue is fixed indeed in the latest version. 😃 Thanks!

**Comment by kylecarbs** [comment]
Wonderful!

**Comment by NiklasRosenstein** [comment]
Hey @kylecarbs  I don't understand why but the issue resurfaced again for me today. I've tried upgrading from 0.17.3 to 0.17.4, partially to see also if the restart of the Coder server did the trick, but to no avail.

Related to #6279 #6277 I suppose?

**Comment by NiklasRosenstein** [comment]
I created a _new_ Workspace and was able to connect to it via VS Code. So something must be wrong in my existing Workspace?

The Workspace showed as connected on the Coder UI though:

<img width="278" alt="image" src="https://user-images.githubusercontent.com/1318438/220634093-a131aa6f-b555-4555-8cba-ce01703f06ae.png">

Also to clarify; The upgrade to 0.17.4 is only on our staging instance so far, and after I upgraded I create a new workspace as well and it didn't work.. Now I created a new workspace on our production Coder instance (still running 0.17.3) and it worked.

In either version I sometimes see this in the Browser console, maybe it's related as it could indicate connection issues?

<img width="1100" alt="image" src="https://user-images.githubusercontent.com/1318438/220634690-02baf694-614c-4aba-92ef-bc7898e722ab.png">

**Comment by NiklasRosenstein** [comment]
It seems that stopping and starting my original workspace on production with Coder 0.17.3 solved the issue.

**Comment by NiklasRosenstein** [comment]
Connections to the workspace over `coder port-forward` seem pretty slow, too. And trying to run `coder speedtest` gives

<img width="1142" alt="image" src="https://user-images.githubusercontent.com/1318438/221188285-e563c74b-bbc9-4dd7-8387-d6adbed74b44.png">

Could there still be an issue in the networking code in Coder @kylecarbs ?

**Comment by kylecarbs** [comment]
@NiklasRosenstein the speed-test has some flakiness in it... even if used without Coder (it's from Tailscale), I've seen some problems.

**Comment by kylecarbs** [comment]
@NiklasRosenstein I'll take a look at this today!

**Comment by bilby91** [comment]
Not sure if I'm facing the same issue here. 

Some context:

-  ssh coder.flytest is working
- coder ssh flytest is working
- Browser code-server working
- VS Code extension not working

I'm not sure why it's trying to resolve `coder-vscode--bilby91--flytest`. My username in coder is `bilby91`.

```
[00:01:25.066] Log Level: 2
[00:01:25.079] VS Code version: 1.76.0
[00:01:25.079] Remote-SSH version: remote-ssh@0.98.0
[00:01:25.079] darwin arm64
[00:01:26.569] SSH Resolver called for "ssh-remote+coder-vscode--bilby91--flytest", attempt 1
[00:01:26.571] "remote.SSH.useLocalServer": true
[00:01:26.572] "remote.SSH.path": undefined
[00:01:26.572] "remote.SSH.configFile": ~/.ssh/config
[00:01:26.572] "remote.SSH.useFlock": true
[00:01:26.573] "remote.SSH.lockfilesInTmp": false
[00:01:26.573] "remote.SSH.localServerDownload": auto
[00:01:26.574] "remote.SSH.remoteServerListenOnSocket": false
[00:01:26.574] "remote.SSH.showLoginTerminal": false
[00:01:26.574] "remote.SSH.defaultExtensions": ["gitpod.gitpod-remote-ssh"]
[00:01:26.574] "remote.SSH.loglevel": 2
[00:01:26.575] "remote.SSH.enableDynamicForwarding": true
[00:01:26.575] "remote.SSH.enableRemoteCommand": false
[00:01:26.575] "remote.SSH.serverPickPortsFromRange": {}
[00:01:26.575] "remote.SSH.serverInstallPath": {}
[00:01:26.581] SSH Resolver called for host: coder-vscode--bilby91--flytest
[00:01:26.581] Setting up SSH remote "coder-vscode--bilby91--flytest"
[00:01:26.585] Acquiring local install lock: /var/folders/jw/vm0pwjz57qg5kjppxxss28k00000gn/T/vscode-remote-ssh-46659c96-install.lock
[00:01:26.586] Looking for existing server data file at /Users/bilby91/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-46659c96-92da9481c0904c6adfe372c12da3b7748d74bdcb-0.98.0/data.json
[00:01:26.587] Using commit id "92da9481c0904c6adfe372c12da3b7748d74bdcb" and quality "stable" for server
[00:01:26.592] Install and start server if needed
[00:01:26.596] PATH: /Users/bilby91/.asdf/shims:/opt/homebrew/opt/asdf/libexec/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/opt/homebrew/opt/fzf/bin
[00:01:26.596] Checking ssh with "ssh -V"
[00:01:26.601] > OpenSSH_9.0p1, LibreSSL 3.3.6

[00:01:26.602] Using SSH config file "/Users/bilby91/.ssh/config"
[00:01:26.602] askpass server listening on /var/folders/jw/vm0pwjz57qg5kjppxxss28k00000gn/T/vscode-ssh-askpass-28b9bdf32fc90f0bc34f52afa8b0f79cee64028c.sock
[00:01:26.603] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/jw/vm0pwjz57qg5kjppxxss28k00000gn/T/vscode-ssh-askpass-00c909c084eebeda627f08bbc4a0a71315b16d4b.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","62830","-o","ConnectTimeout=60","-F","/Users/bilby91/.ssh/config","coder-vscode--bilby91--flytest","bash"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/bilby91/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-46659c96-92da9481c0904c6adfe372c12da3b7748d74bdcb-0.98.0/data.json"}
[00:01:26.603] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.MY3d68CeTz/Listeners","SHELL":"/bin/zsh","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/bilby91/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/bilby91/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/jw/vm0pwjz57qg5kjppxxss28k00000gn/T/vscode-ssh-askpass-28b9bdf32fc90f0bc34f52afa8b0f79cee64028c.sock"}
[00:01:26.603] Spawned 40248
[00:01:26.669] > local-server-1> Running ssh connection command: "-v -T -D 62830 -o ConnectTimeout=60 -F /Users/bilby91/.ssh/config coder-vscode--bilby91--flytest bash"
[00:01:26.671] > local-server-1> Spawned ssh, pid=40255
[00:01:26.673] stderr> OpenSSH_9.0p1, LibreSSL 3.3.6
[00:01:26.675] stderr> ssh: Could not resolve hostname coder-vscode--bilby91--flytest: nodename nor servname provided, or not known
[00:01:26.676] > local-server-1> ssh child died, shutting down
[00:01:26.677] Local server exit: 0
[00:01:26.677] Received install output: local-server-1> Running ssh connection command: "-v -T -D 62830 -o ConnectTimeout=60 -F /Users/bilby91/.ssh/config coder-vscode--bilby91--flytest bash"
local-server-1> Spawned ssh, pid=40255
OpenSSH_9.0p1, LibreSSL 3.3.6
ssh: Could not resolve hostname coder-vscode--bilby91--flytest: nodename nor servname provided, or not known
local-server-1> ssh child died, shutting down

[00:01:26.678] Resolver error: Error: Could not resolve hostname
	at m.Offline (/Users/bilby91/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:584439)
	at /Users/bilby91/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:581669
	at t.handleInstallOutput (/Users/bilby91/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:582037)
	at Object.e [as tryInstallWithLocalServer] (/Users/bilby91/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:623670)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Users/bilby91/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:643639
	at async t.withShowDetailsEvent (/Users/bilby91/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:647359)
	at async /Users/bilby91/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:622142
	at async C (/Users/bilby91/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:618648)
	at async t.resolveWithLocalServer (/Users/bilby91/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:621757)
	at async t.resolve (/Users/bilby91/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:644967)
	at async /Users/bilby91/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:720839
[00:01:26.681] ------
```

**Comment by bilby91** [comment]
I removed the `gitpod` extension in case it could be conflicting stuff. Still same issue.

**Comment by NiklasRosenstein** [comment]
Hey @kylecarbs , I haven't experienced this issue in a while! Seems like 0.18+ is stable.
