### ISSUE TITLE
Cannot establish remote connection.

### ISSUE THREAD

**Issue by djarbz** [coder/coder#6277]
I have Coder OSS on a remote Fedora host on the same subnet as my Windows PC.
I created a workspace using the `Develop code-server in Docker` template.
I installed the Coder extension in VSCode and click the `VS Code Desktop` button on the workspace.
It tries to connect, but I get an error message that it `Could not establish connection to "coder-vscode--djarbz--NFTZBF".`

Here is the log output:
```
[21:18:39.767] Log Level: 2
[21:18:39.821] VS Code version: 1.75.1
[21:18:39.821] Remote-SSH version: remote-ssh@0.96.0
[21:18:39.821] win32 x64
[21:18:43.506] SSH Resolver called for "ssh-remote+coder-vscode--djarbz--NFTZBF", attempt 1
[21:18:43.507] "remote.SSH.useLocalServer": false
[21:18:43.508] "remote.SSH.showLoginTerminal": false
[21:18:43.508] "remote.SSH.remotePlatform": {"coder-vscode--djarbz--NFTZBF":"linux"}
[21:18:43.508] "remote.SSH.path": undefined
[21:18:43.509] "remote.SSH.configFile": undefined
[21:18:43.509] "remote.SSH.useFlock": true
[21:18:43.509] "remote.SSH.lockfilesInTmp": false
[21:18:43.510] "remote.SSH.localServerDownload": auto
[21:18:43.510] "remote.SSH.remoteServerListenOnSocket": false
[21:18:43.510] "remote.SSH.showLoginTerminal": false
[21:18:43.510] "remote.SSH.defaultExtensions": []
[21:18:43.511] "remote.SSH.loglevel": 2
[21:18:43.511] "remote.SSH.enableDynamicForwarding": true
[21:18:43.511] "remote.SSH.enableRemoteCommand": false
[21:18:43.512] "remote.SSH.serverPickPortsFromRange": {}
[21:18:43.512] "remote.SSH.serverInstallPath": {}
[21:18:43.523] SSH Resolver called for host: coder-vscode--djarbz--NFTZBF
[21:18:43.523] Setting up SSH remote "coder-vscode--djarbz--NFTZBF"
[21:18:43.530] Using commit id "441438abd1ac652551dbe4d408dfcec8a499b8bf" and quality "stable" for server
[21:18:43.537] Install and start server if needed
[21:18:43.544] Checking ssh with "ssh -V"
[21:18:43.603] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[21:18:43.610] Running script with connection command: ssh -T -D 22669 "coder-vscode--djarbz--NFTZBF" bash
[21:18:43.615] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[21:18:43.910] > ]0;C:\WINDOWS\System32\cmd.exe
[21:18:43.910] Got some output, clearing connection timeout
[21:18:43.918] > Bad owner or permissions on C:\\Users\\djarbz/.ssh/config
> The process tried to write to a nonexistent pipe.
>       
[21:18:45.184] "install" terminal command done
[21:18:45.185] Install terminal quit with output:       
[21:18:45.185] Received install output:       
[21:18:45.187] Resolver error: Error: 
	at g.Create (c:\Users\djarbz\.vscode\extensions\ms-vscode-remote.remote-ssh-0.96.0\out\extension.js:1:584147)
	at c:\Users\djarbz\.vscode\extensions\ms-vscode-remote.remote-ssh-0.96.0\out\extension.js:1:581988
	at t.handleInstallOutput (c:\Users\djarbz\.vscode\extensions\ms-vscode-remote.remote-ssh-0.96.0\out\extension.js:1:582683)
	at t.tryInstall (c:\Users\djarbz\.vscode\extensions\ms-vscode-remote.remote-ssh-0.96.0\out\extension.js:1:680758)
	at async c:\Users\djarbz\.vscode\extensions\ms-vscode-remote.remote-ssh-0.96.0\out\extension.js:1:643114
	at async t.withShowDetailsEvent (c:\Users\djarbz\.vscode\extensions\ms-vscode-remote.remote-ssh-0.96.0\out\extension.js:1:646432)
	at async t.resolve (c:\Users\djarbz\.vscode\extensions\ms-vscode-remote.remote-ssh-0.96.0\out\extension.js:1:644164)
	at async c:\Users\djarbz\.vscode\extensions\ms-vscode-remote.remote-ssh-0.96.0\out\extension.js:1:721750
[21:18:45.202] ------
```

**Comment by kylecarbs** [comment]
Seems like the permissions of your SSH config are incorrect... did you have an SSH config before? Or did Coder create it? It'd be helpful if you pasted the contents.

**Comment by djarbz** [comment]
I won't be in front of that machine for a while, but I did look at it last night and everything in it was demarked as created by coder.

I tried updating the permissions to 600 via Git-Bash, but they would not change.

**Comment by djarbz** [comment]
I should also add, if it makes any difference, I am using Traefik as a reverse proxy on a different host, still on the same subnet however.

My end goal is to be able to connect from LAN or WAN to my workspaces.

**Comment by kylecarbs** [comment]
Ahh, I believe it's _probably_ an issue in our extension. Checking!

**Comment by kylecarbs** [comment]
@djarbz the permissions wouldn't change on the file with Git-Bash? I wonder if there's something up with your system in that case... is there any way you can get the file permissions to change?

**Comment by djarbz** [comment]
```bash
djarbz@WinDesk MINGW64 ~/.ssh
$ ls -lah
total 45K
drwxr-xr-x 1 djarbz 1049089    0 Feb 14 22:04 ./
drwxr-xr-x 1 djarbz 1049089    0 Jan 17 07:34 ../
-rw-r--r-- 1 djarbz 1049089 2.8K Feb 18 21:18 config
-rw-r--r-- 1 djarbz 1049089 2.6K Sep 18  2020 id_rsa
-rw-r--r-- 1 djarbz 1049089  568 Sep 18  2020 id_rsa.pub
-rw-r--r-- 1 djarbz 1049089 2.0K Jul 29  2022 known_hosts
-rw-r--r-- 1 djarbz 1049089 1.1K Apr  7  2022 known_hosts.old

djarbz@WinDesk MINGW64 ~/.ssh
$ chmod 600 config

djarbz@WinDesk MINGW64 ~/.ssh
$ ls -lah
total 45K
drwxr-xr-x 1 djarbz 1049089    0 Feb 14 22:04 ./
drwxr-xr-x 1 djarbz 1049089    0 Jan 17 07:34 ../
-rw-r--r-- 1 djarbz 1049089 2.8K Feb 18 21:18 config
-rw-r--r-- 1 djarbz 1049089 2.6K Sep 18  2020 id_rsa
-rw-r--r-- 1 djarbz 1049089  568 Sep 18  2020 id_rsa.pub
-rw-r--r-- 1 djarbz 1049089 2.0K Jul 29  2022 known_hosts
-rw-r--r-- 1 djarbz 1049089 1.1K Apr  7  2022 known_hosts.old

djarbz@WinDesk MINGW64 ~/.ssh
$ sudo chmod 600 config
bash: sudo: command not found
```

**Comment by djarbz** [comment]
Also, here is my config file as requested.
```
# ------------START-CODER-----------
# This section is managed by coder. DO NOT EDIT.
#
# You should not hand-edit this section unless you are removing it, all
# changes will be lost when running "coder config-ssh".
#
Host coder.Custom-Goland
        HostName coder.Custom-Goland
        ConnectTimeout=0
        StrictHostKeyChecking=no
        UserKnownHostsFile=/dev/null
        LogLevel ERROR
        ProxyCommand C:\Users\djarbz\AppData\Local\Temp\coder-windows-amd64-v0.17.1+4827d9e.exe --global-config C:\Users\djarbz\AppData\Roaming\coderv2 ssh --stdio Custom-Goland
Host coder.Custom-Goland.main
        HostName coder.Custom-Goland.main
        ConnectTimeout=0
        StrictHostKeyChecking=no
        UserKnownHostsFile=/dev/null
        LogLevel ERROR
        ProxyCommand C:\Users\djarbz\AppData\Local\Temp\coder-windows-amd64-v0.17.1+4827d9e.exe --global-config C:\Users\djarbz\AppData\Roaming\coderv2 ssh --stdio Custom-Goland.main
Host coder.GolandTest
        HostName coder.GolandTest
        ConnectTimeout=0
        StrictHostKeyChecking=no
        UserKnownHostsFile=/dev/null
        LogLevel ERROR
        ProxyCommand C:\Users\djarbz\AppData\Local\Temp\coder-windows-amd64-v0.17.1+4827d9e.exe --global-config C:\Users\djarbz\AppData\Roaming\coderv2 ssh --stdio GolandTest
Host coder.GolandTest.main
        HostName coder.GolandTest.main
        ConnectTimeout=0
        StrictHostKeyChecking=no
        UserKnownHostsFile=/dev/null
        LogLevel ERROR
        ProxyCommand C:\Users\djarbz\AppData\Local\Temp\coder-windows-amd64-v0.17.1+4827d9e.exe --global-config C:\Users\djarbz\AppData\Roaming\coderv2 ssh --stdio GolandTest.main
Host coder.KASMworkspace
        HostName coder.KASMworkspace
        ConnectTimeout=0
        StrictHostKeyChecking=no
        UserKnownHostsFile=/dev/null
        LogLevel ERROR
        ProxyCommand C:\Users\djarbz\AppData\Local\Temp\coder-windows-amd64-v0.17.1+4827d9e.exe --global-config C:\Users\djarbz\AppData\Roaming\coderv2 ssh --stdio KASMworkspace
Host coder.KASMworkspace.main
        HostName coder.KASMworkspace.main
        ConnectTimeout=0
        StrictHostKeyChecking=no
        UserKnownHostsFile=/dev/null
        LogLevel ERROR
        ProxyCommand C:\Users\djarbz\AppData\Local\Temp\coder-windows-amd64-v0.17.1+4827d9e.exe --global-config C:\Users\djarbz\AppData\Roaming\coderv2 ssh --stdio KASMworkspace.main
# ------------END-CODER------------

# --- START CODER VSCODE ---
Host coder-vscode--*
  ProxyCommand "c:\Users\djarbz\AppData\Roaming\Code\User\globalStorage\coder.coder-remote\bin\coder-windows-amd64.exe" vscodessh --network-info-dir "c:\Users\djarbz\AppData\Roaming\Code\User\globalStorage\coder.coder-remote\net" --session-token-file "c:\Users\djarbz\AppData\Roaming\Code\User\globalStorage\coder.coder-remote\session_token" --url-file "c:\Users\djarbz\AppData\Roaming\Code\User\globalStorage\coder.coder-remote\url" %h
  ConnectTimeout 0
  StrictHostKeyChecking no
  UserKnownHostsFile /dev/null
  LogLevel ERROR
# --- END CODER VSCODE ---
```

**Comment by kylecarbs** [comment]
Your command failed to run... try removing the `sudo` in front.

Those files aren't permission 600 actually, I believe they are 644.

**Comment by djarbz** [comment]
I ran it twice, didn't change without sudo and sudo doesn't exist.

The files are currently 644, which typically .ssh requires 600.

**Comment by kylecarbs** [comment]
Hmm, we certainly write those files as `600`, so I'm not sure what's going on...

Can you try running the following?
```
chmod 600 ~/.ssh/config
```
and post the output

**Comment by djarbz** [comment]
```bash
austin@WinDesk MINGW64 ~/.ssh
$ chmod 600 ~/.ssh/config

djarbz@WinDesk MINGW64 ~/.ssh
$ ls -lah
total 45K
drwxr-xr-x 1 djarbz 1049089    0 Feb 14 22:04 ./
drwxr-xr-x 1 djarbz 1049089    0 Jan 17 07:34 ../
-rw-r--r-- 1 djarbz 1049089 2.8K Feb 18 21:18 config
-rw-r--r-- 1 djarbz 1049089 2.6K Sep 18  2020 id_rsa
-rw-r--r-- 1 djarbz 1049089  568 Sep 18  2020 id_rsa.pub
-rw-r--r-- 1 djarbz 1049089 2.0K Jul 29  2022 known_hosts
-rw-r--r-- 1 djarbz 1049089 1.1K Apr  7  2022 known_hosts.old
```

**Comment by djarbz** [comment]
It is definitely an issue with that particular PC, my laptop connects just fine.

**Comment by kylecarbs** [comment]
Try this: https://superuser.com/questions/1296024/windows-ssh-permissions-for-private-key-are-too-open

**Comment by djarbz** [comment]
That worked!
Thank you.

Now I just need to figure out how to program the workspace to clone a repo on creation and then open VS Code to that folder.

**Comment by matifali** [comment]
> That worked! Thank you.
> 
> Now I just need to figure out how to program the workspace to clone a repo on creation and then open VS Code to that folder.

Cloning can be done in the `startup_script` and for starting VS Code Desktop in a specific folder open or search for an issue [here](https://github.com/coder/vscode-coder)
For code-server web, you can already change the `url` property of the respective `coder_app` to open in a specific folder.
