### ISSUE TITLE
VS Code - Doesn't connect

### ISSUE THREAD

**Issue by BijSvenNL** [coder/coder#6279]
The process tried to write to a nonexistent pipe.
]0;C:\WINDOWS\System32\cmd.exe
[13:06:35.778] Got some output, clearing connection timeout
[13:06:37.053] "install" terminal command done
[13:06:37.054] Install terminal quit with output: ]0;C:\WINDOWS\System32\cmd.exe
[13:06:37.054] Received install output: ]0;C:\WINDOWS\System32\cmd.exe
[13:06:37.055] Failed to parse remote port from server output
[13:06:37.056] Resolver error: Error: 
    at g.Create (c:\Users\sven-.vscode\extensions\ms-vscode-remote.remote-ssh-0.96.0\out\extension.js:1:584147)
    at t.handleInstallOutput (c:\Users\sven-.vscode\extensions\ms-vscode-remote.remote-ssh-0.96.0\out\extension.js:1:582761)
    at t.tryInstall (c:\Users\sven-.vscode\extensions\ms-vscode-remote.remote-ssh-0.96.0\out\extension.js:1:680758)
    at async c:\Users\sven-.vscode\extensions\ms-vscode-remote.remote-ssh-0.96.0\out\extension.js:1:643114
    at async t.withShowDetailsEvent (c:\Users\sven-.vscode\extensions\ms-vscode-remote.remote-ssh-0.96.0\out\extension.js:1:646432)
    at async t.resolve (c:\Users\sven-.vscode\extensions\ms-vscode-remote.remote-ssh-0.96.0\out\extension.js:1:644164)
    at async c:\Users\sven-.vscode\extensions\ms-vscode-remote.remote-ssh-0.96.0\out\extension.js:1:721750
[13:06:37.065] ------

-- ERROR LOGS --

https://cdn.discordapp.com/attachments/1076519983812726794/1076836818332430437/image.png
https://cdn.discordapp.com/attachments/1076519983812726794/1076836790784249908/image.png

-- PHOTOS --

Setup: Nginx Proxy Manager + Portainer + Docker-compose Coder

**Comment by matifali** [comment]
Please share your nginx config.

**Comment by CodebySven** [comment]
Okay

**Comment by CodebySven** [comment]
Where can i find that?

**Comment by matifali** [comment]
Also, for Nginx Proxy Manager, enable WebSocket support
as shown here![npm](https://blog.gurucomputing.com.au/doing-more-with-docker/05-Reverse-Proxies-with-Nginx-Proxy-Manager-11.png)

**Comment by matifali** [comment]
@bpmct close this as completed. I have guided the user on discord DM.

**Comment by matifali** [comment]
Please reopen the issue seems to persist @kylecarbs @bpmct

**Comment by CodebySven** [comment]
Okay

**Comment by CodebySven** [comment]
Again didnt work

**Comment by matifali** [comment]
Hi @BijSvenNL do you still face this?

**Comment by BijSvenNL** [comment]
No, I don't work in a team anymore :(

**Comment by matifali** [comment]
I am closing this as resolved. Please create a new issue if you face this again.
