### ISSUE TITLE
Better error when database OOM or fails to connect (or other cases for cannot read properties of undefined: authMethods)

### ISSUE THREAD

**Issue by bpmct** [coder/coder#6983]
I ran into a scenario where my database was significantly under-resourced (and would OOM). This is the error I see from Coder:
![Screenshot 2023-04-03 at 12 09 56 PM](https://user-images.githubusercontent.com/22407953/229579814-c4e0cc10-4fb1-4d2b-8172-ef16238cc69e.png)

```sh
======================= STACK TRACE ========================
Cannot read properties of undefined (reading 'authMethods')
    at j0e (https://coder-production-400f.up.railway.app/assets/index.3c840117.js:193:32841)
    at tx (https://coder-production-400f.up.railway.app/assets/index.3c840117.js:46:19556)
    at WR (https://coder-production-400f.up.railway.app/assets/index.3c840117.js:48:44429)
    at zR (https://coder-production-400f.up.railway.app/assets/index.3c840117.js:48:40066)
    at tF (https://coder-production-400f.up.railway.app/assets/index.3c840117.js:48:39994)
    at Wp (https://coder-production-400f.up.railway.app/assets/index.3c840117.js:48:39847)
    at jy (https://coder-production-400f.up.railway.app/assets/index.3c840117.js:48:36179)
    at MR (https://coder-production-400f.up.railway.app/assets/index.3c840117.js:48:35125)
    at S (https://coder-production-400f.up.railway.app/assets/index.3c840117.js:33:1544)
    at MessagePort.A (https://coder-production-400f.up.railway.app/assets/index.3c840117.js:33:1903)
============================================================
```

Any idea how this happened? I deployed Coder using [railway]() which @matifali is working on. Instructions [here](https://github.com/coder/blogs/pull/11)

**Comment by kylecarbs** [comment]
Seems like a p0?

**Comment by bpmct** [comment]
Doing some tests to see what happened or if it's exclusive to railway. I'm not even sure Railway deployed the latest version.

**Comment by kylecarbs** [comment]
Kk

**Comment by bpmct** [comment]
Can't reproduce it locally. The steps I did:

- Set up user
- Add AWS template
- Build kinda fails
- I retry, I retry again
- It gets stuck and I have to delete cookies to log in again

**Comment by bpmct** [comment]
Now testing whether this is a new issue or exclusive to railway. I'll also test on Kubernetes

**Comment by bpmct** [comment]
Ok this doesn't happen on other platforms and seems to occur when the builtin postgres database runs into a OOM error. We should display a better error here.

**Comment by bpmct** [comment]
This may occur on other scenarios besides a database OOM but that is certainly one case. We should pretty much never show this specific issue and instead show info relevant to the Coder admin
