### ISSUE TITLE
potential bug: Coder shows free disk space when workspace is full

### ISSUE THREAD

**Issue by matroscoe** [coder/coder#7476]
When trying to open an existing stored connection or create a new one while using the Gateway plugin (version `2.3.0` and `2.2.1` both have the issue) I am getting the following exception after the "Starting the remote IDE Backend" window is open then closes. 

We are running coder server `0.23.0`. The workspaces are running on EC2 instances.

```shell
==== FAILURES ====

The following exception failed the deployment
com.jetbrains.gateway.ssh.deploy.DeployException: 

Details:
An error occurred while executing command: 'host-status --ide-path=/home/ubuntu/.cache/JetBrains/RemoteDev/dist/2c9042c6fbb42_pycharm-professional-2023.1.1 --project-path=/home/ubuntu/source-code/<git-repo-based-project>'
Exit code: 1
	at com.jetbrains.gateway.ssh.DeployFlowUtil$fullDeployCycleImpl$2.invokeSuspend(DeployFlowUtil.kt:257)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.intellij.openapi.rd.util.CoroutineProgressContext$Companion$create$task$1$3.invokeSuspend(BackgroundProgressCoroutineUtil.kt:172)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.intellij.openapi.rd.util.CoroutineProgressContext$Companion$create$task$1.invoke(BackgroundProgressCoroutineUtil.kt:168)
	at com.intellij.openapi.rd.util.CoroutineProgressContext$Companion$create$task$1.invoke(BackgroundProgressCoroutineUtil.kt:158)
	at com.intellij.openapi.rd.util.CoroutineProgressContext$Companion$createModal$1$1.run(BackgroundProgressCoroutineUtil.kt:203)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$9(CoreProgressManager.java:513)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:84)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.jetbrains.gateway.ssh.deploy.DeployException: 

Details:
An error occurred while executing command: 'host-status --ide-path=/home/ubuntu/.cache/JetBrains/RemoteDev/dist/2c9042c6fbb42_pycharm-professional-2023.1.1 --project-path=/home/ubuntu/source-code/<git-repo-based-project>'
Exit code: 1
	at com.jetbrains.gateway.ssh.DeployFlowUtil$fullDeployCycleImpl$2.invokeSuspend(DeployFlowUtil.kt:252)
	... 35 more
Caused by: com.jetbrains.gateway.ssh.deploy.DeployException: 

Details:
An error occurred while executing command: 'host-status --ide-path=/home/ubuntu/.cache/JetBrains/RemoteDev/dist/2c9042c6fbb42_pycharm-professional-2023.1.1 --project-path=/home/ubuntu/source-code/<git-repo-based-project>'
Exit code: 1
	at com.jetbrains.gateway.ssh.DeployFlowUtil$fullDeployCycleImpl$2.invokeSuspend(DeployFlowUtil.kt:250)
	... 35 more
Caused by: com.jetbrains.gateway.ssh.RemoteCommandException: 

Details:
An error occurred while executing command: 'host-status --ide-path=/home/ubuntu/.cache/JetBrains/RemoteDev/dist/2c9042c6fbb42_pycharm-professional-2023.1.1 --project-path=/home/ubuntu/source-code/<git-repo-based-project>'
Exit code: 1
	at com.jetbrains.gateway.ssh.GoHighLevelHostAccessor.anErrorOccurred(GoHighLevelHostAccessor.kt:187)
	at com.jetbrains.gateway.ssh.GoHighLevelHostAccessor.callAndReportError(GoHighLevelHostAccessor.kt:176)
	at com.jetbrains.gateway.ssh.GoHighLevelHostAccessor.access$callAndReportError(GoHighLevelHostAccessor.kt:32)
	at com.jetbrains.gateway.ssh.GoHighLevelHostAccessor$callAndReportError$1.invokeSuspend(GoHighLevelHostAccessor.kt)
	... 35 more



==== ENVIRONMENT ====

INSTALLED PRODUCTS

	PyCharm	231.8770.66


AVAILABLE MEMORY

	7.57GB



==== DIAGNOSTIC ERRORS ====

Could not get host jstack: 

Details:
An error occurred while executing command: 'get-jstack --ide-path=/home/ubuntu/.cache/JetBrains/RemoteDev/dist/2c9042c6fbb42_pycharm-professional-2023.1.1 --project-path=/home/ubuntu/source-code/<git-repo-based-project>'
Exit code: 1
```

**Comment by matroscoe** [comment]
NOT an issue with coder (or may have been but was cleared with an upgrade to server `0.23.2` and increasing disk space on the worker). 

I am not closing right now because the host workspace was reporting 4GB+ of free space and it seemed to be seeing there being enough free space but something thought there was not enough free space on system to operate properly. 

I am **NOT** saying this is an issue with coder but asking if this is possibly something coder (the jetbrains plugin) could better report on.

**Comment by bpmct** [comment]
Thanks for circling back, glad to hear you fixed it!

> the host workspace was reporting 4GB+ of free space

Were you seeing this 4GB+ free space from the Gateway plugin or via agent metadata on the dashboard? Sadly, the Gateway plugin reports data from the host node and not the container itself, we have an internal issue tracking this and will make it public as soon as we open-source our plugin!

**Comment by matroscoe** [comment]
@bpmct I was seeing it reported by the OS (Ubuntu 22.04)

```shell
❯_: df -h
Filesystem       Size  Used Avail Use% Mounted on
tmpfs            775M  1.1M  774M   1% /run
/dev/nvme0n1p1    49G   34G   15G  70% /
tmpfs            3.8G     0  3.8G   0% /dev/shm
tmpfs            5.0M     0  5.0M   0% /run/lock
/dev/nvme0n1p15  105M  6.1M   99M   6% /boot/efi
``` 

in my case `/` was listed as 4.5(ish) GB. Even the error as you can see from the original post had nothing to do with disk space it was totally unrelated and only because I had seen some issues before with the deployer from JetBrains not having enough space to deploy an IDE and I figured it might be the same issue but in disguise.

**Comment by matroscoe** [comment]
Side note unless there is something you want to do with this ticket I am okay to close it as a resolved issue as it wasn't really a problem with Coder or your plugin.

**Comment by matifali** [comment]
@bpmct Do we need to to anything here?
