### ISSUE TITLE
flake: TestPortForward_None hangs

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder#7643]
```
=== Failed
=== FAIL: cli  (0.00s)
panic: test timed out after 7m0s
running tests:
	TestPortForward_None (6m52s)

goroutine 51017 [running]:
testing.(*M).startAlarm.func1()
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/testing/testing.go:2241 +0x3c5
created by time.goFunc
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/time/sleep.go:176 +0x32

goroutine 1 [chan receive, 6 minutes]:
testing.tRunner.func1()
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/testing/testing.go:1542 +0x4a5
testing.tRunner(0xc0003b1520, 0xc0009bfb20)
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/testing/testing.go:1582 +0x144
testing.runTests(0xc0001a8c80?, {0x7ff631c31be0, 0x49, 0x49}, {0xc00083f8c0?, 0x27d3916cf58?, 0x7ff634201860?})
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/testing/testing.go:2034 +0x489
testing.(*M).Run(0xc0001a8c80)
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/testing/testing.go:1906 +0x63a
go.uber.org/goleak.VerifyTestMain({0x7ff63308ba00?, 0xc0001a8c80?}, {0xc001485e88, 0x3, 0x3})
	C:/Users/runneradmin/go/pkg/mod/go.uber.org/goleak@v1.2.1/testmain.go:53 +0x6b
github.com/coder/coder/cli.TestMain(0xffffffffffffffff?)
	C:/a/coder/coder/cli/root_internal_test.go:70 +0x1d3
main.main()
	_testmain.go:195 +0x1d3

goroutine 98 [semacquire, 6 minutes]:
internal/poll.runtime_Semacquire(0x478?)
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/sema.go:67 +0x27
internal/poll.(*FD).Close(0xc0015a6280)
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/internal/poll/fd_windows.go:393 +0x87
os.(*file).close(0xc0015a6280)
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/os/file_windows.go:200 +0x85
os.(*File).Close(...)
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/os/file_posix.go:25
github.com/coder/coder/pty.(*ptyWindows).Close(0xc001b87860)
	C:/a/coder/coder/pty/pty_windows.go:164 +0xed
github.com/coder/coder/pty/ptytest.(*PTY).Close(0xc000c68e00)
	C:/a/coder/coder/pty/ptytest/ptytest.go:323 +0x39
github.com/coder/coder/pty/ptytest.New.func1()
	C:/a/coder/coder/pty/ptytest/ptytest.go:39 +0x1d
testing.(*common).Cleanup.func1()
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/testing/testing.go:1150 +0x11f
testing.(*common).runCleanup(0xc000a7c9c0, 0xc000ba4368?)
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/testing/testing.go:1328 +0xe2
testing.tRunner.func2()
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/testing/testing.go:1570 +0x29
testing.tRunner(0xc000a7c9c0, 0x7ff632ce64c0)
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/testing/testing.go:1582 +0x135
created by testing.(*T).Run
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/testing/testing.go:1629 +0x3ea

goroutine 290 [syscall, 6 minutes]:
os/signal.signal_recv()
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/sigqueue.go:152 +0x2f
os/signal.loop()
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/os/signal/signal_unix.go:23 +0x19
created by os/signal.Notify.func1.1
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/os/signal/signal.go:151 +0x2a

goroutine 3343 [select, 6 minutes]:
github.com/coder/coder/coderd/autobuild/executor.(*Executor).Run.func1()
	C:/a/coder/coder/coderd/autobuild/executor/lifecycle_executor.go:63 +0x1e9
created by github.com/coder/coder/coderd/autobuild/executor.(*Executor).Run
	C:/a/coder/coder/coderd/autobuild/executor/lifecycle_executor.go:61 +0x56

goroutine 293 [chan receive, 6 minutes]:
gopkg.in/natefinch/lumberjack%2ev2.(*Logger).millRun(0xc000c44300)
	C:/Users/runneradmin/go/pkg/mod/gopkg.in/natefinch/lumberjack.v2@v2.2.1/lumberjack.go:379 +0x45
created by gopkg.in/natefinch/lumberjack%2ev2.(*Logger).mill.func1
	C:/Users/runneradmin/go/pkg/mod/gopkg.in/natefinch/lumberjack.v2@v2.2.1/lumberjack.go:390 +0x96

goroutine 3715 [syscall, 6 minutes, locked to thread]:
syscall.SyscallN(0x1000000000000?, {0xc000cd7c88?, 0x2?, 0x27d5ec045d8?})
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/syscall_windows.go:557 +0x109
syscall.Syscall6(0x7ff62fd85285?, 0x7ff63427ef20?, 0x7ff62fd6f45e?, 0x27d5ec045d8?, 0x10000c000cd7dcc?, 0x0?, 0x7ff62fd766a5?, 0xc000cd7d18?)
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/syscall_windows.go:501 +0x50
syscall.readFile(0xc000fad2d0?, {0xc00078e000?, 0x8000, 0x27d39160a28?}, 0x500?, 0x800000?)
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/syscall/zsyscall_windows.go:1024 +0x94
syscall.ReadFile(...)
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/syscall/syscall_windows.go:404
syscall.Read(0xc0015a6280?, {0xc00078e000?, 0x4fe?, 0xc000cd7de0?})
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/syscall/syscall_windows.go:383 +0x33
internal/poll.(*FD).Read(0xc0015a6280, {0xc00078e000, 0x8000, 0x8000})
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/internal/poll/fd_windows.go:422 +0x1c5
os.(*File).read(...)
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/os/file_posix.go:31
os.(*File).Read(0xc000ba4360, {0xc00078e000?, 0x2?, 0xc000c5c4f0?})
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/os/file.go:118 +0x5e
github.com/coder/coder/pty.ReadWriter.Read(...)
	C:/a/coder/coder/pty/pty.go:130
io.copyBuffer({0x7ff63308ade0, 0xc000c310b0}, {0x7ff63308c420, 0xc000c5c480}, {0x0, 0x0, 0x0})
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/io/io.go:427 +0x1b2
io.Copy(...)
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/io/io.go:386
github.com/coder/coder/pty/ptytest.newExpecter.func3()
	C:/a/coder/coder/pty/ptytest/ptytest.go:119 +0x97
created by github.com/coder/coder/pty/ptytest.newExpecter
	C:/a/coder/coder/pty/ptytest/ptytest.go:117 +0x86c

goroutine 26814 [chan receive, 6 minutes]:
gopkg.in/natefinch/lumberjack%2ev2.(*Logger).millRun(0xc00564bf80)
	C:/Users/runneradmin/go/pkg/mod/gopkg.in/natefinch/lumberjack.v2@v2.2.1/lumberjack.go:379 +0x45
created by gopkg.in/natefinch/lumberjack%2ev2.(*Logger).mill.func1
	C:/Users/runneradmin/go/pkg/mod/gopkg.in/natefinch/lumberjack.v2@v2.2.1/lumberjack.go:390 +0x96

goroutine 3716 [select, 6 minutes]:
io.(*pipe).read(0xc001284de0, {0xc0015d34fe, 0xb02, 0x50?})
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/io/pipe.go:57 +0xb1
io.(*PipeReader).Read(0x7ff62fd6d647?, {0xc0015d34fe?, 0x7ff631de5d40?, 0xc00192e801?})
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/io/pipe.go:136 +0x25
bufio.(*Scanner).Scan(0xc000e7df48)
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/bufio/scan.go:214 +0x876
github.com/coder/coder/pty/ptytest.newExpecter.func4()
	C:/a/coder/coder/pty/ptytest/ptytest.go:130 +0x134
created by github.com/coder/coder/pty/ptytest.newExpecter
	C:/a/coder/coder/pty/ptytest/ptytest.go:127 +0x8ec

goroutine 3344 [IO wait, 6 minutes]:
internal/poll.runtime_pollWait(0x27d5f7a8f78, 0x72)
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0x0?, 0x0?, 0x0)
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.execIO(0xc0005ae018, 0xc001997c00)
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/internal/poll/fd_windows.go:175 +0xf7
internal/poll.(*FD).acceptOne(0xc0005ae000, 0x548, {0xc0006d42d0?, 0xc001049c00?, 0x7ff632cec288?}, 0xc001997d10?)
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/internal/poll/fd_windows.go:936 +0x6d
internal/poll.(*FD).Accept(0xc0005ae000, 0xc001997dd8)
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/internal/poll/fd_windows.go:970 +0x1d6
net.(*netFD).accept(0xc0005ae000)
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/net/fd_windows.go:139 +0x65
net.(*TCPListener).accept(0xc0012fe648)
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/net/tcpsock_posix.go:148 +0x25
net.(*TCPListener).Accept(0xc0012fe648)
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/net/tcpsock.go:297 +0x3d
net/http.(*Server).Serve(0xc000ed51d0, {0x7ff63309e7e0, 0xc0012fe648})
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/net/http/server.go:3059 +0x385
net/http/httptest.(*Server).goServe.func1()
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/net/http/httptest/server.go:310 +0x6a
created by net/http/httptest.(*Server).goServe
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/net/http/httptest/server.go:308 +0x6a

goroutine 28366 [chan receive, 6 minutes]:
gopkg.in/natefinch/lumberjack%2ev2.(*Logger).millRun(0xc0079abbc0)
	C:/Users/runneradmin/go/pkg/mod/gopkg.in/natefinch/lumberjack.v2@v2.2.1/lumberjack.go:379 +0x45
created by gopkg.in/natefinch/lumberjack%2ev2.(*Logger).mill.func1
	C:/Users/runneradmin/go/pkg/mod/gopkg.in/natefinch/lumberjack.v2@v2.2.1/lumberjack.go:390 +0x96

goroutine 3481 [select, 6 minutes]:
github.com/coder/coder/coderd/metricscache.(*Cache).run(0xc0019b3740, {0x7ff6330a1f58, 0xc001b86460}, {0x7ff6322b2251, 0xd}, 0xc001c08ba0?, 0xc001f77fb8)
	C:/a/coder/coder/coderd/metricscache/metricscache.go:281 +0x32d
github.com/coder/coder/coderd/metricscache.New.func1.1()
	C:/a/coder/coder/coderd/metricscache/metricscache.go:69 +0x90
created by github.com/coder/coder/coderd/metricscache.New.func1
	C:/a/coder/coder/coderd/metricscache/metricscache.go:67 +0x13c

goroutine 15261 [chan receive, 6 minutes]:
gopkg.in/natefinch/lumberjack%2ev2.(*Logger).millRun(0xc002861f20)
	C:/Users/runneradmin/go/pkg/mod/gopkg.in/natefinch/lumberjack.v2@v2.2.1/lumberjack.go:379 +0x45
created by gopkg.in/natefinch/lumberjack%2ev2.(*Logger).mill.func1
	C:/Users/runneradmin/go/pkg/mod/gopkg.in/natefinch/lumberjack.v2@v2.2.1/lumberjack.go:390 +0x96

goroutine 3482 [select, 2 minutes]:
github.com/coder/coder/coderd/metricscache.(*Cache).run(0xc0019b3740, {0x7ff6330a1f58, 0xc001b86460}, {0x7ff6322c3210, 0x10}, 0x3f0?, 0xc001bc9fb8)
	C:/a/coder/coder/coderd/metricscache/metricscache.go:281 +0x32d
github.com/coder/coder/coderd/metricscache.New.func1.2()
	C:/a/coder/coder/coderd/metricscache/metricscache.go:74 +0x90
created by github.com/coder/coder/coderd/metricscache.New.func1
	C:/a/coder/coder/coderd/metricscache/metricscache.go:72 +0x1dc

goroutine 3345 [IO wait, 6 minutes]:
internal/poll.runtime_pollWait(0x27d5f7a89d8, 0x72)
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0xc0005ae518?, 0x7ff6330afab0?, 0x0)
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.execIO(0xc0005ae518, 0x7ff632ceb6e0)
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/internal/poll/fd_windows.go:175 +0xf7
internal/poll.(*FD).ReadFromInet4(0xc0005ae500, {0xc0018a8000, 0x7ff62fdddd91?, 0xc001941d98?}, 0xc001941db8)
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/internal/poll/fd_windows.go:604 +0x150
net.(*netFD).readFromInet4(0xc0005ae500, {0xc0018a8000?, 0x27d5f86e558?, 0x0?}, 0xc001941dd8?)
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/net/fd_posix.go:66 +0x29
net.(*UDPConn).readFrom(0x30?, {0xc0018a8000?, 0xc0014b05a0?, 0x0?}, 0xc0014b05a0)
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/net/udpsock_posix.go:52 +0x1b8
net.(*UDPConn).readFromUDP(0xc000cb5828, {0xc0018a8000?, 0x7ff62fd6ffc7?, 0x10000?}, 0x7ff631e03d60?)
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/net/udpsock.go:149 +0x31
net.(*UDPConn).ReadFrom(0xc001941f30?, {0xc0018a8000, 0x10000, 0x10000})
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/net/udpsock.go:158 +0x50
tailscale.com/net/stun/stuntest.runSTUN({0x7ff6330b7e20, 0xc000a7c9c0}, {0x7ff6330aad20, 0xc000cb5828}, 0xc000ff41c8, 0xc0013f2000?)
	C:/Users/runneradmin/go/pkg/mod/github.com/coder/tailscale@v0.0.0-20230522123520-74712221d00f/net/stun/stuntest/stuntest.go:59 +0xc6
created by tailscale.com/net/stun/stuntest.ServeWithPacketListener
	C:/Users/runneradmin/go/pkg/mod/github.com/coder/tailscale@v0.0.0-20230522123520-74712221d00f/net/stun/stuntest/stuntest.go:47 +0x26a

goroutine 3326 [semacquire, 6 minutes]:
sync.runtime_Semacquire(0xc0014d26c0?)
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/runtime/sema.go:62 +0x27
sync.(*WaitGroup).Wait(0xc000f121a0?)
	C:/hostedtoolcache/windows/go/1.20.3/x64/src/sync/waitgroup.go:116 +0x4b
github.com/coder/coder/coderd/metricscache.New.func1()
	C:/a/coder/coder/coderd/metricscache/metricscache.go:76 +0x1e6
created by github.com/coder/coder/coderd/metricscache.New
	C:/a/coder/coder/coderd/metricscache/metricscache.go:63 +0x1f3

goroutine 16198 [chan receive, 6 minutes]:
gopkg.in/natefinch/lumberjack%2ev2.(*Logger).millRun(0xc003a7d620)
	C:/Users/runneradmin/go/pkg/mod/gopkg.in/natefinch/lumberjack.v2@v2.2.1/lumberjack.go:379 +0x45
created by gopkg.in/natefinch/lumberjack%2ev2.(*Logger).mill.func1
	C:/Users/runneradmin/go/pkg/mod/gopkg.in/natefinch/lumberjack.v2@v2.2.1/lumberjack.go:390 +0x96

goroutine 27346 [chan receive, 6 minutes]:
gopkg.in/natefinch/lumberjack%2ev2.(*Logger).millRun(0xc004d83620)
	C:/Users/runneradmin/go/pkg/mod/gopkg.in/natefinch/lumberjack.v2@v2.2.1/lumberjack.go:379 +0x45
created by gopkg.in/natefinch/lumberjack%2ev2.(*Logger).mill.func1
	C:/Users/runneradmin/go/pkg/mod/gopkg.in/natefinch/lumberjack.v2@v2.2.1/lumberjack.go:390 +0x96

goroutine 28130 [chan receive, 6 minutes]:
gopkg.in/natefinch/lumberjack%2ev2.(*Logger).millRun(0xc008b86420)
	C:/Users/runneradmin/go/pkg/mod/gopkg.in/natefinch/lumberjack.v2@v2.2.1/lumberjack.go:379 +0x45
created by gopkg.in/natefinch/lumberjack%2ev2.(*Logger).mill.func1
	C:/Users/runneradmin/go/pkg/mod/gopkg.in/natefinch/lumberjack.v2@v2.2.1/lumberjack.go:390 +0x96

goroutine 28284 [chan receive, 6 minutes]:
gopkg.in/natefinch/lumberjack%2ev2.(*Logger).millRun(0xc00564b320)
	C:/Users/runneradmin/go/pkg/mod/gopkg.in/natefinch/lumberjack.v2@v2.2.1/lumberjack.go:379 +0x45
created by gopkg.in/natefinch/lumberjack%2ev2.(*Logger).mill.func1
	C:/Users/runneradmin/go/pkg/mod/gopkg.in/natefinch/lumberjack.v2@v2.2.1/lumberjack.go:390 +0x96
FAIL	github.com/coder/coder/cli	441.656s

=== FAIL: cli TestPortForward_None (unknown)
    t.go:85: 2023-05-23 04:47:02.282 [debu]  metrics_cache: deployment stats metrics refreshed  took=0s  interval=5m0s
    t.go:85: 2023-05-23 04:47:02.287 [debu]  metrics_cache: template daus metrics refreshed  took=4.9043ms  interval=1h0m0s
    t.go:85: 2023-05-23 04:47:02.617 [debu]  POST  host=localhost:57746  path=/api/v2/users/first  proto=HTTP/1.1  remote_addr=127.0.0.1  took=4.0081ms  status_code=201  latency_ms=4  request_id=cdb55aa3-b3f2-4c93-a54b-9b9baff141ef
    t.go:85: 2023-05-23 04:47:02.621 [debu]  POST  host=localhost:57746  path=/api/v2/users/login  proto=HTTP/1.1  remote_addr=127.0.0.1  took=3.6844ms  status_code=201  latency_ms=3  request_id=4c26b981-27fc-4bcc-b596-a37e79842cd0
    clitest.go:67: invoking command: coder --global-config C:\Users\RUNNER~1\AppData\Local\Temp\TestPortForward_None4217154825\002 port-forward blah
    t.go:85: 2023-05-23 04:47:02.741 [debu]  GET  host=localhost:57746  path=/api/v2/entitlements  proto=HTTP/1.1  remote_addr=127.0.0.1  took=0s  status_code=404  latency_ms=0  request_id=59631ae3-84fa-49c5-9b45-73312925b464
    t.go:85: 2023-05-23 04:47:02.741 [debu]  GET  host=localhost:57746  path=/api/v2/buildinfo  proto=HTTP/1.1  remote_addr=127.0.0.1  took=0s  status_code=200  latency_ms=0  request_id=322fb0e6-c35e-4c6b-90ba-f6fef3186910
    ptytest.go:131: 2023-05-23 04:47:02.746: cmd: "Usage: coder port-forward [flags] <workspace>"
    ptytest.go:131: 2023-05-23 04:47:02.746: cmd: ""
    ptytest.go:131: 2023-05-23 04:47:02.746: cmd: "Forward ports from machine to a workspace"
    ptytest.go:131: 2023-05-23 04:47:02.746: cmd: ""
    ptytest.go:131: 2023-05-23 04:47:02.746: cmd: "Aliases: tunnel"
    ptytest.go:131: 2023-05-23 04:47:02.746: cmd: ""
    ptytest.go:131: 2023-05-23 04:47:02.746: cmd: "- Port forward a single TCP port from 1234 in the workspace to port [567](https://github.com/coder/coder/actions/runs/5053242100/jobs/9066907367#step:9:568)8 on   "
    ptytest.go:131: 2023-05-23 04:47:02.746: cmd: "    your local machine:                                                         "
    ptytest.go:131: 2023-05-23 04:47:02.746: cmd: ""
    ptytest.go:131: 2023-05-23 04:47:02.746: cmd: "      $ coder port-forward <workspace> --tcp 5[678](https://github.com/coder/coder/actions/runs/5053242100/jobs/9066907367#step:9:679):1234 "
    ptytest.go:131: 2023-05-23 04:47:02.[746](https://github.com/coder/coder/actions/runs/5053242100/jobs/9066907367#step:9:747): cmd: ""
    ptytest.go:131: 2023-05-23 04:47:02.746: cmd: "  - Port forward a single UDP port from port 9000 to port 9000 on your local    "
    ptytest.go:131: 2023-05-23 04:47:02.746: cmd: "    machine:                                                                    "
    ptytest.go:131: 2023-05-23 04:47:02.746: cmd: ""
    ptytest.go:131: 2023-05-23 04:47:02.746: cmd: "      $ coder port-forward <workspace> --udp 9000 "
    ptytest.go:131: 2023-05-23 04:47:02.746: cmd: ""
    ptytest.go:131: 2023-05-23 04:47:02.746: cmd: "  - Port forward multiple TCP ports and a UDP port:                             "
    ptytest.go:131: 2023-05-23 04:47:02.746: cmd: ""
    ptytest.go:131: 2023-05-23 04:47:02.746: cmd: "      $ coder port-forward <workspace> --tcp [808](https://github.com/coder/coder/actions/runs/5053242100/jobs/9066907367#step:9:809)0:8080 --tcp 9000:3000 --udp 5353:53 "
    ptytest.go:131: 2023-05-23 04:47:02.746: cmd: ""
    ptytest.go:131: 2023-05-23 04:47:02.746: cmd: "  - Port forward multiple ports (TCP or UDP) in condensed syntax:               "
    ptytest.go:131: 2023-05-23 04:47:02.746: cmd: ""
    ptytest.go:131: 2023-05-23 04:47:02.746: cmd: "      $ coder port-forward <workspace> --tcp 8080,9000:3000,9090-9092,10000-10002:10010-10012"
    ptytest.go:131: 2023-05-23 04:47:02.746: cmd: ""
    ptytest.go:131: 2023-05-23 04:47:02.746: cmd: "Options"
    ptytest.go:131: 2023-05-23 04:47:02.746: cmd: "  -p, --tcp string-array, $CODER_PORT_FORWARD_TCP"
    ptytest.go:131: 2023-05-23 04:47:02.746: cmd: "          Forward TCP port(s) from the workspace to the local machine."
    ptytest.go:131: 2023-05-23 04:47:02.746: cmd: ""
    ptytest.go:131: 2023-05-23 04:47:02.746: cmd: "      --udp string-array, $CODER_PORT_FORWARD_UDP"
    ptytest.go:131: 2023-05-23 04:47:02.746: cmd: "          Forward UDP port(s) from the workspace to the local machine. The UDP"
    ptytest.go:131: 2023-05-23 04:47:02.746: cmd: "          connection has TCP-like semantics to support stateful UDP protocols."
    ptytest.go:131: 2023-05-23 04:47:02.746: cmd: ""
    ptytest.go:131: 2023-05-23 04:47:02.746: cmd: "---"
    ptytest.go:131: 2023-05-23 04:47:02.746: cmd: "Run `coder --help` for a list of global options."
    portforward_test.go:40: 2023-05-23 04:47:02.746: cmd: matched "port-forward <workspace>" = "Usage: coder port-forward [flags] <workspace>\n\nForward ports from machine to a workspace\n\nAliases: tunnel\n\n- Port forward a single TCP port from 1234 in the workspace to port 5678 on   \n    your local machine:                                                         \n\n      $ coder port-forward <workspace>"
    t.go:85: 2023-05-23 04:52:02.293 [debu]  metrics_cache: deployment stats metrics refreshed  took=0s  interval=5m0s
```
c.f. https://github.com/coder/coder/actions/runs/5053242100/attempts/1

**Comment by coadler** [comment]
Combed through Datadog and this hasn't flaked in at minimum the past 3 months.
