### ISSUE TITLE
Improve errors for invalid character '<' across the CLI

### ISSUE THREAD

**Issue by bashirsouid** [coder/coder#8297]
# Overview
This may be an unsupported usage edge case. As a hobbyist combining lots of tools together, I tend to find lots of edge cases where software doesn't work. Feel free to close if not in scope but I thought I would share this error case if it matters to anyone else.

If you use Coder with Cloudflared Zero Trust application access policies you get an error with `coder login` and also when trying to connect VS Code Remote Server. Codespaces continues to work normally and web based terminal works normally.
 
You could say "why bother?" since Coder already has built-in authentication so you probably dont really need another layer of CloudFlare authentication unless you want to further restrict access in a way unsupported by coder like by IP addresses and/or with hardware keys. I am mostly just trying it to see what is possible. But I could imagine an enterprise might want to do something like this if they are already securing lots of other things with CloudFlared Zero Trust?
 
# OS Information
OS: MacOS 12 and Debian 11
Architecture: Intel x86_64
Coder v0.24.1+2c843f4 Wed Jun 14 11:52:01 UTC 2023
https://github.com/coder/coder/commit/2c843f4011430ef5bbefc76460af20393a317350

# Steps to Reproduce
- Run Coder in docker container, or potentially on bare metal. I am using the container from LinuxServer.io.
- Setup a CloudFlared Zero Trust application tunnel pointing a public subdomain to your VM instance
- Login to your Coder instance from the web. Note that everything still works at this point. For example, try VS Code Remote attach.
- Turn on access control policies in CloudFlared Zero Trust portal. Restrict access in any way you like, I used a single specific email account to allow access.
- Leave CORS and Cookie settings as defaults (basically no CORS settings set and cookie only restricted as HTTP)
- Open terminal and do `coder login URL` and note the error showing up, yet it still opens the browser window which shows a token to copy and paste into the terminal.
- Go ahead and try to copy and paste the token into the terminal but it never accepts it. Always says invalid token.
- Go back to your coder workspace page and try to do VS Code Remote again, this time it will fail with same error.

```
[22:59:54.103] Log Level: 2
[22:59:54.193] VS Code version: 1.79.2
[22:59:54.193] Remote-SSH version: remote-ssh@0.102.0
[22:59:54.193] darwin x64
[22:59:59.699] SSH Resolver called for "ssh-remote+coder-vscode--bashirs--test-docker", attempt 1
[22:59:59.700] "remote.SSH.useLocalServer": true
[22:59:59.701] "remote.SSH.path": undefined
[22:59:59.701] "remote.SSH.configFile": undefined
[22:59:59.701] "remote.SSH.useFlock": true
[22:59:59.701] "remote.SSH.lockfilesInTmp": false
[22:59:59.702] "remote.SSH.localServerDownload": auto
[22:59:59.702] "remote.SSH.remoteServerListenOnSocket": false
[22:59:59.702] "remote.SSH.showLoginTerminal": false
[22:59:59.702] "remote.SSH.defaultExtensions": []
[22:59:59.702] "remote.SSH.loglevel": 2
[22:59:59.702] "remote.SSH.enableDynamicForwarding": true
[22:59:59.703] "remote.SSH.enableRemoteCommand": false
[22:59:59.703] "remote.SSH.serverPickPortsFromRange": {}
[22:59:59.703] "remote.SSH.serverInstallPath": {}
[22:59:59.722] SSH Resolver called for host: coder-vscode--bashirs--test-docker
[22:59:59.722] Setting up SSH remote "coder-vscode--bashirs--test-docker"
[22:59:59.725] Acquiring local install lock: /var/folders/ww/2__blfkx6mv2zkf2p1dq_x100000gn/T/vscode-remote-ssh-ddb29482-install.lock
[22:59:59.729] Looking for existing server data file at /Users/bashirs/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-ddb29482-695af097c7bd098fbf017ce3ac85e09bbc5dda06-0.102.0/data.json
[22:59:59.732] Using commit id "695af097c7bd098fbf017ce3ac85e09bbc5dda06" and quality "stable" for server
[22:59:59.736] Install and start server if needed
[22:59:59.748] PATH: /Users/bashirs/.nvm/versions/node/v18.16.0/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
[22:59:59.748] Checking ssh with "ssh -V"
[22:59:59.765] > OpenSSH_9.0p1, LibreSSL 3.3.6

[22:59:59.774] askpass server listening on /var/folders/ww/2__blfkx6mv2zkf2p1dq_x100000gn/T/vscode-ssh-askpass-a2a4618e207cc8c12c26264d18702a45ed10c4a0.sock
[22:59:59.775] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/ww/2__blfkx6mv2zkf2p1dq_x100000gn/T/vscode-ssh-askpass-e56b6297b210313fb9287cce7dfed6aee771019a.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","52495","-o","ConnectTimeout=15","coder-vscode--bashirs--test-docker","bash"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/bashirs/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-ddb29482-695af097c7bd098fbf017ce3ac85e09bbc5dda06-0.102.0/data.json"}
[22:59:59.775] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.zJnOHg9Ox5/Listeners","SHELL":"/bin/zsh","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/bashirs/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/bashirs/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/ww/2__blfkx6mv2zkf2p1dq_x100000gn/T/vscode-ssh-askpass-a2a4618e207cc8c12c26264d18702a45ed10c4a0.sock"}
[22:59:59.778] Spawned 70050
[22:59:59.960] > local-server-1> Running ssh connection command: "-v -T -D 52495 -o ConnectTimeout=15 coder-vscode--bashirs--test-docker bash"
[22:59:59.964] > local-server-1> Spawned ssh, pid=70056
[22:59:59.972] stderr> OpenSSH_9.0p1, LibreSSL 3.3.6
[23:00:00.837] stderr> running command "coder vscodessh": find workspace:                        
[23:00:00.837] stderr>     github.com/coder/coder/cli.(*RootCmd).vscodeSSH.func1                 
[23:00:00.837] stderr>         /home/runner/actions-runner/_work/coder/coder/cli/vscodessh.go:100
[23:00:00.837] stderr>   - invalid character '<' looking for beginning of value                  
[23:00:00.841] stderr> kex_exchange_identification: Connection closed by remote host
[23:00:00.841] stderr> Connection closed by UNKNOWN port 65535
[23:00:00.843] > local-server-1> ssh child died, shutting down
[23:00:00.847] Local server exit: 0
[23:00:00.848] Received install output: local-server-1> Running ssh connection command: "-v -T -D 52495 -o ConnectTimeout=15 coder-vscode--bashirs--test-docker bash"
local-server-1> Spawned ssh, pid=70056
OpenSSH_9.0p1, LibreSSL 3.3.6
running command "coder vscodessh": find workspace:                        
    github.com/coder/coder/cli.(*RootCmd).vscodeSSH.func1                 
        /home/runner/actions-runner/_work/coder/coder/cli/vscodessh.go:100
  - invalid character '<' looking for beginning of value                  
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535
local-server-1> ssh child died, shutting down

[23:00:00.849] Failed to parse remote port from server output
[23:00:00.851] Resolver error: Error: 
	at m.Create (/Users/bashirs/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:584145)
	at t.handleInstallOutput (/Users/bashirs/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:582705)
	at Object.e [as tryInstallWithLocalServer] (/Users/bashirs/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:623656)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Users/bashirs/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:643708
	at async t.withShowDetailsEvent (/Users/bashirs/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:647428)
	at async /Users/bashirs/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:622128
	at async C (/Users/bashirs/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:618634)
	at async t.resolveWithLocalServer (/Users/bashirs/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:621743)
	at async t.resolve (/Users/bashirs/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:645036)
	at async /Users/bashirs/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:720916
[23:00:00.882] ------
```

# Expected

Able to do `coder login` normally even with Cloudflared access policies enabled.

# Actual

invalid character '<' looking for beginning of value

# Screenshot(s)
<img width="1506" alt="image" src="https://github.com/coder/coder/assets/2036949/b189b160-f093-4060-910e-570c2972ecd7">
<img width="575" alt="image" src="https://github.com/coder/coder/assets/2036949/98e1fe8b-be39-4323-b9b0-6515ed76c74e">
<img width="1679" alt="image" src="https://github.com/coder/coder/assets/2036949/0306140a-6ce4-4185-b606-303aa8be39e3">

**Comment by kylecarbs** [comment]
Could you pass the Cloudflare authentication token header to get past this?

**Comment by moltra** [comment]
I am getting the same error when I am trying to login on either of my two machines.  One Linux and the other windows 11.  Coder is running in a docker container on the Linux computer.

**Comment by matifali** [comment]
Hi @moltra, can you update to v0.26.0 and check if it still exists?

**Comment by moltra** [comment]
User docker image for V0.26.0+bf8af90

**Comment by bpmct** [comment]
Ah, so we have a [--header flag](https://coder.com/docs/v2/latest/cli#--header) that can also be set with `CODER_HEADER`. This should allow you to pass authentication data to CloudFlare. Have you tried this?

**Comment by moltra** [comment]
I cannot even type or paste into the field or if it is, nothing is showing.
Still getting this with 26.1

**Comment by bpmct** [comment]
@moltra are you running Coder behind Cloudflare access? If not, when you type `coder login <url>` does it fix it?

**Comment by moltra** [comment]
> @moltra are you running Coder behind Cloudflare access or some other identity-aware proxy? If not, when you type `coder login <url>` does it fix it?

I am running traefik2 as a reverse proxy with Cloudflare.  I am using the url from traefik2 to access coder.

**Comment by bpmct** [comment]
So does the Coder URL require special authentication before you see the Coder login page? The `<` error means it is getting an invalid HTML response from the server (as if you were to curl it) versus JSON.

**Comment by bpmct** [comment]
I used the GitLab CLI the other day and it has the same behavior when the URL is invalid or returning a HTML response
