### ISSUE TITLE
Occasional "panic serving http request"

### ISSUE THREAD

**Issue by sthdev** [coder/coder#8351]
After updating to Coder 0.25.0, I get the following error from time to with no obvious cause. Accessing Coder returns HTTP 500 with the following error message: 

`{"message":"An internal server error occurred."}`

The Coder pod's log contains this error:
```
2023-07-06 14:11:40.632 [warn]  coderd: panic serving http request (recovered)  panic="runtime error: invalid memory address or nil pointer dereference" ...
    stack= goroutine 909 [running]:
           runtime/debug.Stack()
           	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/debug/stack.go:24 +0x65
           github.com/coder/coder/coderd/httpmw.Recover.func1.1.1()
           	/home/runner/actions-runner/_work/coder/coder/coderd/httpmw/recover.go:28 +0x105
           panic({0x2397be0, 0xb91fae0})
           	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/panic.go:884 +0x213
           github.com/coder/coder/coderd/httpmw.ExtractAPIKey({0xa53ba50?, 0xc0115007d0?}, 0xc01150ca00, {{0xa5d57e0, 0xc000f25f00}, 0x0, 0x0, 0x0, 0x1, 0x0})
           	/home/runner/actions-runner/_work/coder/coder/coderd/httpmw/apikey.go:245 +0xace
           github.com/coder/coder/site.(*Handler).renderHTMLWithState(0xc000f1ed70, {0xa53ba50, 0xc0115007d0}, 0xc01150ca00, {0xc000864f54, 0x0}, {{{0xc000824fc0, 0x58}}, {0xc0000387e0, 0xe0}, ...})
           	/home/runner/actions-runner/_work/coder/coder/site/site.go:292 +0x185
           github.com/coder/coder/site.(*Handler).serveHTML(0xc000ecbfc0?, {0xa53ba50, 0xc0115007d0}, 0x20?, {0xc000864f54, 0x0}, {{{0xc000824fc0, 0x58}}, {0xc0000387e0, 0xe0}, ...})
           	/home/runner/actions-runner/_work/coder/coder/site/site.go:267 +0x7e
           github.com/coder/coder/site.(*Handler).ServeHTTP(0xc000f1ed70, {0xa53ba50, 0xc0115007d0}, 0xc01150ca00)
           	/home/runner/actions-runner/_work/coder/coder/site/site.go:172 +0x145
           github.com/go-chi/chi/v5/middleware.(*Compressor).Handler.func1({0xa53b7b0?, 0xc000a954c0}, 0xc01150ca00)
           	/home/runner/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.8/middleware/compress.go:213 +0x271
           net/http.HandlerFunc.ServeHTTP(0x2564fe0?, {0xa53b7b0?, 0xc000a954c0?}, 0x17?)
           	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
           github.com/coder/coder/coderd/httpmw.CSPHeaders.func1.1({0xa53b7b0, 0xc000a954c0}, 0xc01150ca00)
           	/home/runner/actions-runner/_work/coder/coder/coderd/httpmw/csp.go:123 +0xcc7
           net/http.HandlerFunc.ServeHTTP(0xc00033c768?, {0xa53b7b0?, 0xc000a954c0?}, 0xc000f3aa60?)
           	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
           net/http.HandlerFunc.ServeHTTP(...)
           	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122
           github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc000d528a0, {0xa53b7b0, 0xc000a954c0}, 0xc01150ca00)
           	/home/runner/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.8/mux.go:450 +0x1f4
           net/http.HandlerFunc.ServeHTTP(0xc0000c4000?, {0xa53b7b0?, 0xc000a954c0?}, 0x21?)
           	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
           github.com/justinas/nosurf.(*CSRFHandler).handleSuccess(...)
           	/home/runner/go/pkg/mod/github.com/justinas/nosurf@v1.1.1/handler.go:187
           github.com/justinas/nosurf.(*CSRFHandler).ServeHTTP(0xc00098e120, {0xa53b7b0, 0xc000a954c0}, 0x16?)
           	/home/runner/go/pkg/mod/github.com/justinas/nosurf@v1.1.1/handler.go:144 +0x634
           github.com/coder/coder/coderd.New.func4.1({0xa53b7b0, 0xc000a954c0}, 0xc000c73610?)
           	/home/runner/actions-runner/_work/coder/coder/coderd/coderd.go:448 +0x128
           net/http.HandlerFunc.ServeHTTP(0x0?, {0xa53b7b0?, 0xc000a954c0?}, 0x15?)
           	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
           github.com/coder/coder/coderd.New.func3.1({0xa53b7b0, 0xc000a954c0}, 0xc000922fc0?)
           	/home/runner/actions-runner/_work/coder/coder/coderd/coderd.go:438 +0x133
           net/http.HandlerFunc.ServeHTTP(0xc000b5c1e0?, {0xa53b7b0?, 0xc000a954c0?}, 0xc01150c900?)
           	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
           github.com/go-chi/cors.(*Cors).Handler.func1({0xa53b7b0, 0xc000a954c0}, 0xc01150c900)
           	/home/runner/go/pkg/mod/github.com/go-chi/cors@v1.2.1/cors.go:228 +0x1bd
           net/http.HandlerFunc.ServeHTTP(0xc000056119?, {0xa53b7b0?, 0xc000a954c0?}, 0x1c?)
           	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
           github.com/coder/coder/coderd/workspaceapps.(*Server).parseHostname(0xc0003c0000, {0xa53b7b0, 0xc000a954c0}, 0x0?, {0xa52f900, 0xc000d4c460}, {0xc01151c060, 0x1c})
           	/home/runner/actions-runner/_work/coder/coder/coderd/workspaceapps/proxy.go:409 +0x122
           github.com/coder/coder/coderd/workspaceapps.(*Server).HandleSubdomain.func1.1({0xa53b7b0, 0xc000a954c0}, 0xc01150c900)
           	/home/runner/actions-runner/_work/coder/coder/coderd/workspaceapps/proxy.go:360 +0x245
           net/http.HandlerFunc.ServeHTTP(0x0?, {0xa53b7b0?, 0xc000a954c0?}, 0x0?)
           	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
           github.com/coder/coder/coderd/httpmw.Prometheus.func1.1({0xa53b7b0?, 0xc000a954c0}, 0xc01150c900)
           	/home/runner/actions-runner/_work/coder/coder/coderd/httpmw/prometheus.go:90 +0x2f2
           net/http.HandlerFunc.ServeHTTP(0xc0008650d0?, {0xa53b7b0?, 0xc000a954c0?}, 0xc000e491b8?)
           	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
           github.com/coder/coder/coderd/httpmw.Logger.func1.1({0xa53b7b0?, 0xc000a954c0?}, 0xc01150c900)
           	/home/runner/actions-runner/_work/coder/coder/coderd/httpmw/logger.go:31 +0x41d
           net/http.HandlerFunc.ServeHTTP(0xc0008650c0?, {0xa53b7b0?, 0xc000a954c0?}, 0xb9d5778?)
           	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
           github.com/coder/coder/coderd/httpmw.ExtractRealIP.func1.1({0xa53b7b0, 0xc000a954c0}, 0xc01150c800)
           	/home/runner/actions-runner/_work/coder/coder/coderd/httpmw/realip.go:50 +0x21d
           net/http.HandlerFunc.ServeHTTP(0x2564fe0?, {0xa53b7b0?, 0xc000a954c0?}, 0x12?)
           	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
           github.com/coder/coder/coderd/httpmw.AttachRequestID.func1({0xa53b7b0, 0xc000a954c0}, 0xc01150c700)
           	/home/runner/actions-runner/_work/coder/coder/coderd/httpmw/requestid.go:33 +0x39c
           net/http.HandlerFunc.ServeHTTP(0x0?, {0xa53b7b0?, 0xc000a954c0?}, 0x0?)
           	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
           github.com/coder/coder/coderd/tracing.Middleware.func1.1({0xa53b7b0?, 0xc000a954c0?}, 0xc01150c700?)
           	/home/runner/actions-runner/_work/coder/coder/coderd/tracing/httpmw.go:40 +0x622
           net/http.HandlerFunc.ServeHTTP(0x0?, {0xa53b7b0?, 0xc000a954c0?}, 0x0?)
           	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
           github.com/coder/coder/coderd/tracing.StatusWriterMiddleware.func1({0xa540520?, 0xc0001be7e0}, 0xc000a44810?)
           	/home/runner/actions-runner/_work/coder/coder/coderd/tracing/status_writer.go:31 +0x93
           net/http.HandlerFunc.ServeHTTP(0xc000a44850?, {0xa540520?, 0xc0001be7e0?}, 0xa539c68?)
           	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
           github.com/coder/coder/coderd/httpmw.Recover.func1.1({0xa540520?, 0xc0001be7e0?}, 0x23381c0?)
           	/home/runner/actions-runner/_work/coder/coder/coderd/httpmw/recover.go:44 +0xd0
           net/http.HandlerFunc.ServeHTTP(0xc000d59860?, {0xa540520?, 0xc0001be7e0?}, 0xc000a44920?)
           	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
           github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc000d528a0, {0xa540520, 0xc0001be7e0}, 0xc01150c700)
           	/home/runner/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.8/mux.go:73 +0x355
           github.com/go-chi/chi/v5.(*Mux).Mount.func1({0xa540520, 0xc0001be7e0}, 0xc01150c700)
           	/home/runner/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.8/mux.go:316 +0x1c4
           net/http.HandlerFunc.ServeHTTP(0x2378ec0?, {0xa540520?, 0xc0001be7e0?}, 0xc000864f54?)
           	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
           github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc000811ce0, {0xa540520, 0xc0001be7e0}, 0xc01150c700)
           	/home/runner/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.8/mux.go:444 +0x216
           net/http.HandlerFunc.ServeHTTP(0xa543c78?, {0xa540520?, 0xc0001be7e0?}, 0xb91f370?)
           	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
           github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc000811ce0, {0xa540520, 0xc0001be7e0}, 0xc01150c600)
           	/home/runner/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.8/mux.go:90 +0x310
           net/http.serverHandler.ServeHTTP({0xc000d594d0?}, {0xa540520, 0xc0001be7e0}, 0xc01150c600)
           	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2936 +0x316
           net/http.(*conn).serve(0xc000878cf0, {0xa543d20, 0xc0009b9ce0})
           	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:1995 +0x612
           created by net/http.(*Server).Serve
           	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:3089 +0x5ed
```

Restarting the browser or deleting Coder's cookies resolves the problem.

**Comment by Emyrk** [comment]
Looks like this is trying to access the OIDC config because a user logged in with OIDC, but oidc is no longer configured? It happens if the OIDC is expired and we are trying to refresh the token.

Did you setup OIDC and then remove it?

I wonder what the behavior should be :thinking:. Should we block the login if OIDC is no longer configured?

**Comment by Emyrk** [comment]
I can make the oauth refresh fail, and the login fail in this case

**Comment by sthdev** [comment]
> Looks like this is trying to access the OIDC config because a user logged in with OIDC, but oidc is no longer configured? It happens if the OIDC is expired and we are trying to refresh the token.
> 
> Did you setup OIDC and then remove it?

I have set up OIDC via Keycloak but I did not change the configuration when I updated from 0.24.1 to 0.25.0. With 0.24.1, Coder showed an error message about an invalid session token when the token expired. After hitting refresh, Coder 0.24.1 redirected to the login screen in this case.

**Comment by smolinari** [comment]
I ran into this issue too. 

Any chance to get a quick patch release to get the fix?

Scott

**Comment by Emyrk** [comment]
Huh, I am going to reopen this because my fix just prevents the nil panic deref. This would force a reauth as it redirects to `/login`, but I am not sure if it will fix the underlying issue?

**Comment by Emyrk** [comment]
If deleting your cookie and logging back in fixes this, then my patch will fix it.

**Comment by mh013370** [comment]
This happened to me again after a long period of idle & clearing my browser cache again resolved it. It definitely seems like a oidc token refresh issue. Is any special configuration now needed for token refresh? 

The odd thing is that this didn't happen prior to 0.25.0, but looking through the merged PRs it's not obvious what could have caused it.

**Comment by waza-ari** [comment]
Same issue here also with Keycloak OIDC. I had another issue before where the refresh token did expire and Coder did not recognise this, leading to clients being broken after access token timespan.

**Comment by cfouche3005** [comment]
Same problem with Authentik :
```
2023-07-08 10:25:26.043 [warn]  coderd: panic serving http request (recovered)  panic="runtime error: invalid memory address or nil pointer dereference" ...
    stack= goroutine 390 [running]:
           runtime/debug.Stack()
           	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/debug/stack.go:24 +0x65
           github.com/coder/coder/coderd/httpmw.Recover.func1.1.1()
           	/home/runner/actions-runner/_work/coder/coder/coderd/httpmw/recover.go:28 +0x105
           panic({0x2397be0, 0xb91fae0})
           	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/panic.go:884 +0x213
           github.com/coder/coder/coderd/httpmw.ExtractAPIKey({0xa53ba50?, 0xc000f17c20?}, 0xc0006c8f00, {{0xa5d57e0, 0xc000c0ee80}, 0x0, 0x0, 0x0, 0x1, 0x0})
           	/home/runner/actions-runner/_work/coder/coder/coderd/httpmw/apikey.go:245 +0xace
           github.com/coder/coder/site.(*Handler).renderHTMLWithState(0xc0002c0140, {0xa53ba50, 0xc000f17c20}, 0xc0006c8f00, {0xc000ede304, 0x0}, {{{0xc000f9a960, 0x58}}, {0xc000572a80, 0xe0}, ...})
           	/home/runner/actions-runner/_work/coder/coder/site/site.go:292 +0x185
           github.com/coder/coder/site.(*Handler).serveHTML(0xc0112f9fc0?, {0xa53ba50, 0xc000f17c20}, 0x20?, {0xc000ede304, 0x0}, {{{0xc000f9a960, 0x58}}, {0xc000572a80, 0xe0}, ...})
           	/home/runner/actions-runner/_work/coder/coder/site/site.go:267 +0x7e
           github.com/coder/coder/site.(*Handler).ServeHTTP(0xc0002c0140, {0xa53ba50, 0xc000f17c20}, 0xc0006c8f00)
           	/home/runner/actions-runner/_work/coder/coder/site/site.go:172 +0x145
           github.com/go-chi/chi/v5/middleware.(*Compressor).Handler.func1({0xa53b7b0?, 0xc000ece580}, 0xc0006c8f00)
           	/home/runner/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.8/middleware/compress.go:213 +0x271
           net/http.HandlerFunc.ServeHTTP(0x2564fe0?, {0xa53b7b0?, 0xc000ece580?}, 0x17?)
           	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
           github.com/coder/coder/coderd/httpmw.CSPHeaders.func1.1({0xa53b7b0, 0xc000ece580}, 0xc0006c8f00)
           	/home/runner/actions-runner/_work/coder/coder/coderd/httpmw/csp.go:123 +0xcc7
           net/http.HandlerFunc.ServeHTTP(0xc00033e428?, {0xa53b7b0?, 0xc000ece580?}, 0xc00034a7f0?)
           	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
           net/http.HandlerFunc.ServeHTTP(...)
           	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122
           github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc000df0d20, {0xa53b7b0, 0xc000ece580}, 0xc0006c8f00)
           	/home/runner/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.8/mux.go:450 +0x1f4
           net/http.HandlerFunc.ServeHTTP(0xc0000c6000?, {0xa53b7b0?, 0xc000ece580?}, 0x21?)
           	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
           github.com/justinas/nosurf.(*CSRFHandler).handleSuccess(...)
           	/home/runner/go/pkg/mod/github.com/justinas/nosurf@v1.1.1/handler.go:187
           github.com/justinas/nosurf.(*CSRFHandler).ServeHTTP(0xc00094d320, {0xa53b7b0, 0xc000ece580}, 0x16?)
           	/home/runner/go/pkg/mod/github.com/justinas/nosurf@v1.1.1/handler.go:144 +0x634
           github.com/coder/coder/coderd.New.func4.1({0xa53b7b0, 0xc000ece580}, 0xc000dfccb0?)
           	/home/runner/actions-runner/_work/coder/coder/coderd/coderd.go:448 +0x128
           net/http.HandlerFunc.ServeHTTP(0x0?, {0xa53b7b0?, 0xc000ece580?}, 0x15?)
           	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
           github.com/coder/coder/coderd.New.func3.1({0xa53b7b0, 0xc000ece580}, 0xc0006ba620?)
           	/home/runner/actions-runner/_work/coder/coder/coderd/coderd.go:438 +0x133
           net/http.HandlerFunc.ServeHTTP(0xc00093c780?, {0xa53b7b0?, 0xc000ece580?}, 0xc0006c8e00?)
           	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
           github.com/go-chi/cors.(*Cors).Handler.func1({0xa53b7b0, 0xc000ece580}, 0xc0006c8e00)
           	/home/runner/go/pkg/mod/github.com/go-chi/cors@v1.2.1/cors.go:228 +0x1bd
           net/http.HandlerFunc.ServeHTTP(0xc00005a019?, {0xa53b7b0?, 0xc000ece580?}, 0x15?)
           	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
           github.com/coder/coder/coderd/workspaceapps.(*Server).parseHostname(0xc00063ca00, {0xa53b7b0, 0xc000ece580}, 0x0?, {0xa52f900, 0xc000632040}, {0xc00064a738, 0x15})
           	/home/runner/actions-runner/_work/coder/coder/coderd/workspaceapps/proxy.go:409 +0x122
           github.com/coder/coder/coderd/workspaceapps.(*Server).HandleSubdomain.func1.1({0xa53b7b0, 0xc000ece580}, 0xc0006c8e00)
           	/home/runner/actions-runner/_work/coder/coder/coderd/workspaceapps/proxy.go:360 +0x245
           net/http.HandlerFunc.ServeHTTP(0x0?, {0xa53b7b0?, 0xc000ece580?}, 0x0?)
           	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
           github.com/coder/coder/coderd/httpmw.Prometheus.func1.1({0xa53b7b0?, 0xc000ece580}, 0xc0006c8e00)
           	/home/runner/actions-runner/_work/coder/coder/coderd/httpmw/prometheus.go:90 +0x2f2
           net/http.HandlerFunc.ServeHTTP(0xc000ede3c5?, {0xa53b7b0?, 0xc000ece580?}, 0xc000eb51b8?)
           	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
           github.com/coder/coder/coderd/httpmw.Logger.func1.1({0xa53b7b0?, 0xc000ece580?}, 0xc0006c8e00)
           	/home/runner/actions-runner/_work/coder/coder/coderd/httpmw/logger.go:31 +0x41d
           net/http.HandlerFunc.ServeHTTP(0xc000ede410?, {0xa53b7b0?, 0xc000ece580?}, 0xb9d5778?)
           	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
           github.com/coder/coder/coderd/httpmw.ExtractRealIP.func1.1({0xa53b7b0, 0xc000ece580}, 0xc0006c8d00)
           	/home/runner/actions-runner/_work/coder/coder/coderd/httpmw/realip.go:50 +0x21d
           net/http.HandlerFunc.ServeHTTP(0x2564fe0?, {0xa53b7b0?, 0xc000ece580?}, 0x12?)
           	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
           github.com/coder/coder/coderd/httpmw.AttachRequestID.func1({0xa53b7b0, 0xc000ece580}, 0xc0006c8c00)
           	/home/runner/actions-runner/_work/coder/coder/coderd/httpmw/requestid.go:33 +0x39c
           net/http.HandlerFunc.ServeHTTP(0x0?, {0xa53b7b0?, 0xc000ece580?}, 0x0?)
           	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
           github.com/coder/coder/coderd/tracing.Middleware.func1.1({0xa53b7b0?, 0xc000ece580?}, 0xc0006c8c00?)
           	/home/runner/actions-runner/_work/coder/coder/coderd/tracing/httpmw.go:40 +0x622
           net/http.HandlerFunc.ServeHTTP(0x0?, {0xa53b7b0?, 0xc000ece580?}, 0x416270?)
           	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
           github.com/coder/coder/coderd/tracing.StatusWriterMiddleware.func1({0xa540520?, 0xc000ebc380}, 0xc000d70810?)
           	/home/runner/actions-runner/_work/coder/coder/coderd/tracing/status_writer.go:31 +0x93
           net/http.HandlerFunc.ServeHTTP(0xbf?, {0xa540520?, 0xc000ebc380?}, 0x7fabb30e4ba0?)
           	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
           github.com/coder/coder/coderd/httpmw.Recover.func1.1({0xa540520?, 0xc000ebc380?}, 0x23381c0?)
           	/home/runner/actions-runner/_work/coder/coder/coderd/httpmw/recover.go:44 +0xd0
           net/http.HandlerFunc.ServeHTTP(0xc00097b950?, {0xa540520?, 0xc000ebc380?}, 0xc000d70920?)
           	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
           github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc000df0d20, {0xa540520, 0xc000ebc380}, 0xc0006c8c00)
           	/home/runner/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.8/mux.go:73 +0x355
           github.com/go-chi/chi/v5.(*Mux).Mount.func1({0xa540520, 0xc000ebc380}, 0xc0006c8c00)
           	/home/runner/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.8/mux.go:316 +0x1c4
           net/http.HandlerFunc.ServeHTTP(0x2378ec0?, {0xa540520?, 0xc000ebc380?}, 0xc000ede304?)
           	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
           github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc00098d1a0, {0xa540520, 0xc000ebc380}, 0xc0006c8c00)
           	/home/runner/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.8/mux.go:444 +0x216
           net/http.HandlerFunc.ServeHTTP(0xa543c78?, {0xa540520?, 0xc000ebc380?}, 0xb91f370?)
           	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2122 +0x2f
           github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc00098d1a0, {0xa540520, 0xc000ebc380}, 0xc0006c8b00)
           	/home/runner/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.8/mux.go:90 +0x310
           net/http.serverHandler.ServeHTTP({0xc00097b6e0?}, {0xa540520, 0xc000ebc380}, 0xc0006c8b00)
           	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:2936 +0x316
           net/http.(*conn).serve(0xc0005255f0, {0xa543d20, 0xc0007692c0})
           	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:1995 +0x612
           created by net/http.(*Server).Serve
           	/opt/hostedtoolcache/go/1.20.5/x64/src/net/http/server.go:3089 +0x5
```

**Comment by waza-ari** [comment]
Clearing cookies solves the issues for roughly 5 minutes, then they come back automatically. It's suspiciously close to the lifespan of an access token, so I'm suspecting some other issue.

@sthdev and @mh013370 , you're using Keycloak as well. Could we quickly compare the OIDC / Keycloak config to rule out any issues there?

On coder, I've only set these parameters:

```
    - name: CODER_OIDC_ISSUER_URL
      value: "https://sso.my-url.com/auth/realms/RealName"
    - name: CODER_OIDC_CLIENT_ID
      value: "coder"
    - name: CODER_OIDC_CLIENT_SECRET
      value: "my-secret"
```

On keycloak, it's a standard client without any special configuration. I was wondering if the offline token lifespan would be an issue?

**Comment by sthdev** [comment]
@waza-ari I have set up OIDC in the same way. However, I have increased the token lifespans and session timeouts in order to avoid too frequent re-authentications, which is annoying in some other applications that also use Keycloak for authentication.

**Comment by mh013370** [comment]
@waza-ari - that's the same configuration i have as well. It's the minimum necessary setup with no extra config.

**Comment by mafredri** [comment]
Release https://github.com/coder/coder/releases/tag/v0.26.0 is out now, which includes the fix for this issue. We couldn’t make a patch release since we had some breaking changes merged, although none of these should be user facing, so upgrading should be safe.

**Comment by mh013370** [comment]
I haven't seen this issue resurface since upgrading to v0.26.0. Thanks for the quick fix!

**Comment by sthdev** [comment]
Thank you for fixing this so quickly. However, either the bug was not fully resolved or 0.26.0 introduced a new problem. When the token is expired and I try to access the Coder root URL in Chrome, Coder returns the following content:

```
{"message":"Could not refresh expired Oauth token.","detail":"oauth2: \"invalid_grant\" \"Token is not active\""}
<!DOCTYPE html>

<!--
    ▄█▀    ▀█▄
     ▄▄ ▀▀▀  █▌   ██▀▀█▄          ▐█
 ▄▄██▀▀█▄▄▄  ██  ██      █▀▀█ ▐█▀▀██ ▄█▀▀█ █▀▀
█▌   ▄▌   ▐█ █▌  ▀█▄▄▄█▌ █  █ ▐█  ██ ██▀▀  █
     ██████▀▄█    ▀▀▀▀   ▀▀▀▀  ▀▀▀▀▀  ▀▀▀▀ ▀
  -->

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="theme-color" content="#17172E" />
  <meta name="application-name" content="Coder" />
  <meta property="og:type" content="website" />
  <meta property="csrf-token" content="gN1YE1KzPxTmRlfvnI0rDY+N5d1tO/GqB926fsyUUisdDjBm8E9/TdNYqrPOH9wBJiQF2wsGiUh9DzfrulDpvQ==" />
  <meta property="build-info" content="{&#34;external_url&#34;:&#34;https://github.com/coder/coder/commit/bf8af90d5af6f887bb6574b73307e5cfdd65afd5&#34;,&#34;version&#34;:&#34;v0.26.0+bf8af90&#34;,&#34;dashboard_url&#34;:&#34;&#34;,&#34;workspace_proxy&#34;:false}" />
  <meta property="user" content="" />
  <meta property="entitlements" content="" />
  <meta property="appearance" content="" />
  <meta property="experiments" content="" />
  <meta property="regions" content="" />
  <!-- We need to set data-react-helmet to be able to override it in the workspace page -->
  <link
    rel="alternate icon"
    type="image/png"
    href="/favicons/favicon.png"
    data-react-helmet="true"
  />
  <link
    rel="icon"
    type="image/svg+xml"
    href="/favicons/favicon.svg"
    data-react-helmet="true"
  />
  <script type="module" crossorigin src="/assets/index-db410224.js"></script>
  <link rel="stylesheet" href="/assets/index-9014df87.css">
</head>

<body>
  <div id="root"></div>
  
</body>
```

The error message is prepended to the HTML content, which is usually returned. But this makes Chrome show the response content as text and not render it as HTML.

**Comment by sthdev** [comment]
Again, deleting Coder's cookies resolves the issue.

**Comment by waza-ari** [comment]
For us it looks like the issue is fully resolved, I don’t see the issue described above. Had to login though after upgrade and added an additional oidc setting to request the offline_access scope

**Comment by sthdev** [comment]
> For us it looks like the issue is fully resolved, I don’t see the issue described above. Had to login though after upgrade and added an additional oidc setting to request the offline_access scope

Oops, I missed that part of the documentation. I will add the offline_scope.

**Comment by smolinari** [comment]
I have the `offline_access` scope in our coder Keycloak client (it is a "builtin" scope for OIDC) and I'm still getting the new error page. My understanding is the default mode is also "offline" in Coder i.e. I don't need to change anything in Coder. Is this true or rather is there anything else I need to do in Coder so this error won't pop up?

Scott

**Comment by waza-ari** [comment]
@smolinari there's two things in OIDC, its the `access_method` and then the scopes. `access_method` is set to `offline` by default by coder, but that doesn't automatically lead to the `offline_access` scope being applied.

I tried setting the scope to default like this, but for be that didn't help:

<img width="1365" alt="image" src="https://github.com/coder/coder/assets/4508976/1731c435-24d6-4a74-be83-f9b39a078a28">

What I've done instead now it to configure coder to request the `offline_access` scope during the initial request, since then it worked. For that I've set an additional environment variable:

```
    - name: CODER_OIDC_SCOPES
      value: "openid,profile,email,offline_access"
```

**Comment by smolinari** [comment]
I tried and added the `CODER_OIDC_SCOPES`, I ended up with 
```
{"message":"Cookie \"oauth_state\" must be provided."}
```
And any changes in the scopes provided in the value doesn't make any difference. 

And I also removed that envvar and I'm still getting that error.  So, I'm stuck now with a downed setup. :cry: 

Scott

**Comment by mafredri** [comment]
> Thank you for fixing this so quickly. However, either the bug was not fully resolved or 0.26.0 introduced a new problem. When the token is expired and I try to access the Coder root URL in Chrome, Coder returns the following content:
> [...]
> The error message is prepended to the HTML content, which is usually returned. But this makes Chrome show the response content as text and not render it as HTML.

Sorry you ran into this! It's a failure mode we missed, thanks for reporting it @sthdev! This should be fixed by #8450.

**Comment by mafredri** [comment]
@sthdev and anyone else affected by the last remaining issue, https://github.com/coder/coder/releases/tag/v0.26.1 is out now and contains the fix!

**Comment by smolinari** [comment]
Thanks, I'll be upgrading very soon. 

One question left open. With the OIDC `offling_access` scope in use and Coder looking for it, should the user never be logged out? Cause, after my token is expired, I could still access our Coder instance. This would also not be the behavior I'd be looking for. 

Edit: Ok. That is exactly what it is for. 

https://wjw465150.gitbooks.io/keycloak-documentation/content/server_admin/topics/sessions/offline.html

You learn something new every day, right? :grin: 

That being said, that shouldn't have been the solution to the newer error showing up. :shrug: :grin: 

Scott

**Comment by smolinari** [comment]
Now with 0.26.1, after the OIDC's refresh token is expired, I am getting the login page (which is good), but after hitting the "Log in with OIDC" button, I get this error. 

`{"message":"Could not refresh expired Oauth token.","detail":"oauth2: \"invalid_grant\" \"Token is not active\""}`

Once I delete all cookies, everything works as normal. 

Scott

**Comment by smolinari** [comment]
The error above happened again this morning. I'm thinking it is a bug, since everything is back to the way things were before 0.25 and when this issue started, yet I can't log in normally. I'll start a new issue. 

Scott
