### ISSUE TITLE
`Internal error fetching user's roles. unauthorized: evaluate rego: context canceled`

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#8928]
AKS deployment on `2.0.0`

This message appeared in the dashboard

![image](https://github.com/coder/coder/assets/2022166/38c5e487-e35c-46d1-99b5-a0c671844c5e)

![image](https://github.com/coder/coder/assets/2022166/90717e9c-1568-4285-a9fb-b01ed7e38595)

Stacktrace on subsequent refresh

```
TypeError: Cannot read properties of undefined (reading 'authMethods')
    at sve (https://aks-v2.demo.coder.com/assets/index-e49710db.js:299:27369)
    at Ib (https://aks-v2.demo.coder.com/assets/index-e49710db.js:54:19538)
    at f4 (https://aks-v2.demo.coder.com/assets/index-e49710db.js:56:44055)
    at u4 (https://aks-v2.demo.coder.com/assets/index-e49710db.js:56:39787)
    at V9 (https://aks-v2.demo.coder.com/assets/index-e49710db.js:56:39715)
    at Th (https://aks-v2.demo.coder.com/assets/index-e49710db.js:56:39568)
    at k1 (https://aks-v2.demo.coder.com/assets/index-e49710db.js:56:35933)
    at s4 (https://aks-v2.demo.coder.com/assets/index-e49710db.js:56:34882)
    at E (https://aks-v2.demo.coder.com/assets/index-e49710db.js:41:1544)
    at MessagePort.z (https://aks-v2.demo.coder.com/assets/index-e49710db.js:41:1903)
```

Subsequent dashboard refresh, things look fine.

![image](https://github.com/coder/coder/assets/2022166/f25a0afb-2d09-4f2b-9de2-e13786712164)

**Comment by bpmct** [comment]
Potentially related #6983

**Comment by smocherla-brex** [comment]
Ran into this as well on our setup after activating a Coder trial license. (we are using a built-in postgres server)

**Comment by NoOverflow** [comment]
Encountered this issue aswell when using a postgresql database setup using the helm chart. Moving to an external postgresql database running on a dedicated VM seems to have mitigated this. 

Note: I'm saying "mitigated" and not "resolved" as the "**Internal error fetching user's roles. unauthorized: evaluate rego: context canceled**" error kept showing up for a few minutes after install and licensing setup, but disappeared completely after (my guess is that the database is heavily used right after setup, and some requests may be hanging up or timing out)

**Comment by kylecarbs** [comment]
Closing for now. If we can get some additional info, we'll reopen, but this seems very rare.
