### ISSUE TITLE
bug(cli): `coder vscode-ssh` output is unclear when session is expired

### ISSUE THREAD

**Issue by phorcys420** [coder/coder#9257]
![image](https://github.com/coder/vscode-coder/assets/57866459/366b0ab8-f339-4a03-9de2-c92e1451c16b)

---

<details>
  <summary>Logs from VSCode "Output" tab</summary>
  <p>

  ```
  [22:10:53.391] Log Level: 2
  [22:10:53.420] VS Code version: 1.82.0-insider
  [22:10:53.421] Remote-SSH version: remote-ssh@0.105.1
  [22:10:53.421] win32 x64
  [22:10:57.265] SSH Resolver called for "ssh-remote+coder-vscode--phorcys420--catfood--dev", attempt 1
  [22:10:57.265] "remote.SSH.useLocalServer": false
  [22:10:57.265] "remote.SSH.showLoginTerminal": false
  [22:10:57.266] "remote.SSH.remotePlatform": {"coder-vscode--phorcys420--catfood":"linux","coder-vscode--phorcys420--catfood--dev":"linux"}
  [22:10:57.266] "remote.SSH.path": undefined
  [22:10:57.266] "remote.SSH.configFile": undefined
  [22:10:57.266] "remote.SSH.useFlock": true
  [22:10:57.266] "remote.SSH.lockfilesInTmp": false
  [22:10:57.266] "remote.SSH.localServerDownload": auto
  [22:10:57.266] "remote.SSH.remoteServerListenOnSocket": false
  [22:10:57.266] "remote.SSH.showLoginTerminal": false
  [22:10:57.266] "remote.SSH.defaultExtensions": []
  [22:10:57.267] "remote.SSH.loglevel": 2
  [22:10:57.267] "remote.SSH.enableDynamicForwarding": true
  [22:10:57.267] "remote.SSH.enableRemoteCommand": false
  [22:10:57.267] "remote.SSH.serverPickPortsFromRange": {}
  [22:10:57.267] "remote.SSH.serverInstallPath": {}
  [22:10:57.270] SSH Resolver called for host: coder-vscode--phorcys420--catfood--dev
  [22:10:57.270] Setting up SSH remote "coder-vscode--phorcys420--catfood--dev"
  [22:10:57.273] Using commit id "501baeb5e07b5a404f862d922bacb93771d91331" and quality "insider" for server
  [22:10:57.275] Install and start server if needed
  [22:10:57.277] Checking ssh with "C:\Program Files\Eclipse Adoptium\jdk-17.0.4.8-hotspot\bin\ssh.exe -V"
  [22:10:57.278] Got error from ssh: spawn C:\Program Files\Eclipse Adoptium\jdk-17.0.4.8-hotspot\bin\ssh.exe ENOENT
  [22:10:57.278] Checking ssh with "A:\Oculus\Support\oculus-runtime\ssh.exe -V"
  [22:10:57.279] Got error from ssh: spawn A:\Oculus\Support\oculus-runtime\ssh.exe ENOENT
  [22:10:57.279] Checking ssh with "C:\Program Files (x86)\Common Files\Oracle\Java\javapath\ssh.exe -V"
  [22:10:57.280] Got error from ssh: spawn C:\Program Files (x86)\Common Files\Oracle\Java\javapath\ssh.exe ENOENT
  [22:10:57.280] Checking ssh with "C:\Program Files\Eclipse Adoptium\jre-8.0.342.7-hotspot\bin\ssh.exe -V"
  [22:10:57.281] Got error from ssh: spawn C:\Program Files\Eclipse Adoptium\jre-8.0.342.7-hotspot\bin\ssh.exe ENOENT
  [22:10:57.281] Checking ssh with "C:\Program Files\Eclipse Adoptium\jre-11.0.16.8-hotspot\bin\ssh.exe -V"
  [22:10:57.282] Got error from ssh: spawn C:\Program Files\Eclipse Adoptium\jre-11.0.16.8-hotspot\bin\ssh.exe ENOENT
  [22:10:57.282] Checking ssh with "C:\Windows\system32\ssh.exe -V"
  [22:10:57.282] Got error from ssh: spawn C:\Windows\system32\ssh.exe ENOENT
  [22:10:57.283] Checking ssh with "C:\Windows\ssh.exe -V"
  [22:10:57.283] Got error from ssh: spawn C:\Windows\ssh.exe ENOENT
  [22:10:57.283] Checking ssh with "C:\Windows\System32\Wbem\ssh.exe -V"
  [22:10:57.284] Got error from ssh: spawn C:\Windows\System32\Wbem\ssh.exe ENOENT
  [22:10:57.284] Checking ssh with "C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe -V"
  [22:10:57.285] Got error from ssh: spawn C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
  [22:10:57.285] Checking ssh with "C:\Windows\System32\OpenSSH\ssh.exe -V"
  [22:10:57.307] > OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3

  [22:10:57.309] Running script with connection command: "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 53468 "coder-vscode--phorcys420--catfood--dev" bash
  [22:10:57.312] Terminal shell path: C:\WINDOWS\System32\cmd.exe
  [22:10:59.727] > running command "coder vscodessh": find workspace:
  >     github.com/coder/coder/v2/cli.(*RootCmd).vscodeSSH.func1
  >         /home/runner/actions-runner/_work/coder/coder/cli/vscodessh.go:103
  >   - invalid character '<' looking for beginning of value
  > kex_exchange_identification: Connection closed by remote host
  > Le processus a tenté d’écrire sur un canal inexistant.
  > ]0;C:\WINDOWS\System32\cmd.exe
  [22:10:59.727] Got some output, clearing connection timeout
  [22:11:00.984] "install" terminal command done
  [22:11:00.985] Install terminal quit with output: ]0;C:\WINDOWS\System32\cmd.exe
  [22:11:00.985] Received install output: ]0;C:\WINDOWS\System32\cmd.exe
  [22:11:00.985] Failed to parse remote port from server output
  [22:11:00.987] Resolver error: Error: 
    at m.Create (c:\Users\Phorcys\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.105.1\out\extension.js:2:618542)
    at t.handleInstallOutput (c:\Users\Phorcys\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.105.1\out\extension.js:2:617353)
    at t.tryInstall (c:\Users\Phorcys\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.105.1\out\extension.js:2:737415)
    at async c:\Users\Phorcys\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.105.1\out\extension.js:2:698164
    at async t.withShowDetailsEvent (c:\Users\Phorcys\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.105.1\out\extension.js:2:701260)
    at async A (c:\Users\Phorcys\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.105.1\out\extension.js:2:695050)
    at async t.resolve (c:\Users\Phorcys\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.105.1\out\extension.js:2:698813)
    at async c:\Users\Phorcys\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.105.1\out\extension.js:2:881993
  [22:11:00.991] ------
  ```

  </p>
</details>

---

<details>
  <summary>Contents of <code>.ssh/config</code></summary>
  <p>

  ```
  # --- START CODER VSCODE ---
  Host coder-vscode--*
    ConnectTimeout 0
    LogLevel ERROR
    ProxyCommand "c:\Users\Phorcys\AppData\Roaming\Code - Insiders\User\globalStorage\coder.coder-remote\bin\coder-windows-amd64.exe" vscodessh --network-info-dir "c:\Users\Phorcys\AppData\Roaming\Code - Insiders\User\globalStorage\coder.coder-remote\net" --session-token-file "c:\Users\Phorcys\AppData\Roaming\Code - Insiders\User\globalStorage\coder.coder-remote\session_token" --url-file "c:\Users\Phorcys\AppData\Roaming\Code - Insiders\User\globalStorage\coder.coder-remote\url" %h
    SetEnv  CODER_SSH_SESSION_TYPE=vscode
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null
  # --- END CODER VSCODE ---
  ```

  </p>
</details>

---

<details>
  <summary>Output of <code>ssh -vvvv -T -D 53544 "coder-vscode--phorcys420--catfood--dev" bash</code></summary>
  <p>

  ```
  OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3
  debug1: Reading configuration data C:\\Users\\Phorcys/.ssh/config
  debug1: C:\\Users\\Phorcys/.ssh/config line 2: Applying options for coder-vscode--*
  debug3: Failed to open file:C:/ProgramData/ssh/ssh_config error:2
  debug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling
  debug1: Executing proxy command: exec "c:\\Users\\Phorcys\\AppData\\Roaming\\Code - Insiders\\User\\globalStorage\\coder.coder-remote\\bin\\coder-windows-amd64.exe" vscodessh --network-info-dir "c:\\Users\\Phorcys\\AppData\\Roaming\\Code - Insiders\\User\\globalStorage\\coder.coder-remote\\net" --session-token-file "c:\\Users\\Phorcys\\AppData\\Roaming\\Code - Insiders\\User\\globalStorage\\coder.coder-remote\\session_token" --url-file "c:\\Users\\Phorcys\\AppData\\Roaming\\Code - Insiders\\User\\globalStorage\\coder.coder-remote\\url" coder-vscode--phorcys420--ca
  debug3: spawning "c:\\Users\\Phorcys\\AppData\\Roaming\\Code - Insiders\\User\\globalStorage\\coder.coder-remote\\bin\\coder-windows-amd64.exe" vscodessh --network-info-dir "c:\\Users\\Phorcys\\AppData\\Roaming\\Code - Insiders\\User\\globalStorage\\coder.coder-remote\\net" --session-token-file "c:\\Users\\Phorcys\\AppData\\Roaming\\Code - Insiders\\User\\globalStorage\\coder.coder-remote\\session_token" --url-file "c:\\Users\\Phorcys\\AppData\\Roaming\\Code - Insiders\\User\\globalStorage\\coder.coder-remote\\url" coder-vscode--phorcys420--catfood--dev as subprocess
  debug3: w32_getpeername ERROR: not sock :2
  debug1: identity file C:\\Users\\Phorcys/.ssh/id_rsa type 0
  debug3: Failed to open file:C:/Users/Phorcys/.ssh/id_rsa-cert error:2
  debug3: Failed to open file:C:/Users/Phorcys/.ssh/id_rsa-cert.pub error:2
  debug3: failed to open file:C:/Users/Phorcys/.ssh/id_rsa-cert error:2
  debug1: identity file C:\\Users\\Phorcys/.ssh/id_rsa-cert type -1
  debug3: Failed to open file:C:/Users/Phorcys/.ssh/id_dsa error:2
  debug3: Failed to open file:C:/Users/Phorcys/.ssh/id_dsa.pub error:2
  debug3: failed to open file:C:/Users/Phorcys/.ssh/id_dsa error:2
  debug1: identity file C:\\Users\\Phorcys/.ssh/id_dsa type -1
  debug3: Failed to open file:C:/Users/Phorcys/.ssh/id_dsa-cert error:2
  debug3: Failed to open file:C:/Users/Phorcys/.ssh/id_dsa-cert.pub error:2
  debug3: failed to open file:C:/Users/Phorcys/.ssh/id_dsa-cert error:2
  debug1: identity file C:\\Users\\Phorcys/.ssh/id_dsa-cert type -1
  debug3: Failed to open file:C:/Users/Phorcys/.ssh/id_ecdsa error:2
  debug3: Failed to open file:C:/Users/Phorcys/.ssh/id_ecdsa.pub error:2
  debug3: failed to open file:C:/Users/Phorcys/.ssh/id_ecdsa error:2
  debug1: identity file C:\\Users\\Phorcys/.ssh/id_ecdsa type -1
  debug3: Failed to open file:C:/Users/Phorcys/.ssh/id_ecdsa-cert error:2
  debug3: Failed to open file:C:/Users/Phorcys/.ssh/id_ecdsa-cert.pub error:2
  debug3: failed to open file:C:/Users/Phorcys/.ssh/id_ecdsa-cert error:2
  debug1: identity file C:\\Users\\Phorcys/.ssh/id_ecdsa-cert type -1
  debug3: Failed to open file:C:/Users/Phorcys/.ssh/id_ecdsa_sk error:2
  debug3: Failed to open file:C:/Users/Phorcys/.ssh/id_ecdsa_sk.pub error:2
  debug3: failed to open file:C:/Users/Phorcys/.ssh/id_ecdsa_sk error:2
  debug1: identity file C:\\Users\\Phorcys/.ssh/id_ecdsa_sk type -1
  debug3: Failed to open file:C:/Users/Phorcys/.ssh/id_ecdsa_sk-cert error:2
  debug3: Failed to open file:C:/Users/Phorcys/.ssh/id_ecdsa_sk-cert.pub error:2
  debug3: failed to open file:C:/Users/Phorcys/.ssh/id_ecdsa_sk-cert error:2
  debug1: identity file C:\\Users\\Phorcys/.ssh/id_ecdsa_sk-cert type -1
  debug3: Failed to open file:C:/Users/Phorcys/.ssh/id_ed25519 error:2
  debug3: Failed to open file:C:/Users/Phorcys/.ssh/id_ed25519.pub error:2
  debug3: failed to open file:C:/Users/Phorcys/.ssh/id_ed25519 error:2
  debug1: identity file C:\\Users\\Phorcys/.ssh/id_ed25519 type -1
  debug3: Failed to open file:C:/Users/Phorcys/.ssh/id_ed25519-cert error:2
  debug3: Failed to open file:C:/Users/Phorcys/.ssh/id_ed25519-cert.pub error:2
  debug3: failed to open file:C:/Users/Phorcys/.ssh/id_ed25519-cert error:2
  debug1: identity file C:\\Users\\Phorcys/.ssh/id_ed25519-cert type -1
  debug3: Failed to open file:C:/Users/Phorcys/.ssh/id_ed25519_sk error:2
  debug3: Failed to open file:C:/Users/Phorcys/.ssh/id_ed25519_sk.pub error:2
  debug3: failed to open file:C:/Users/Phorcys/.ssh/id_ed25519_sk error:2
  debug1: identity file C:\\Users\\Phorcys/.ssh/id_ed25519_sk type -1
  debug3: Failed to open file:C:/Users/Phorcys/.ssh/id_ed25519_sk-cert error:2
  debug3: Failed to open file:C:/Users/Phorcys/.ssh/id_ed25519_sk-cert.pub error:2
  debug3: failed to open file:C:/Users/Phorcys/.ssh/id_ed25519_sk-cert error:2
  debug1: identity file C:\\Users\\Phorcys/.ssh/id_ed25519_sk-cert type -1
  debug3: Failed to open file:C:/Users/Phorcys/.ssh/id_xmss error:2
  debug3: Failed to open file:C:/Users/Phorcys/.ssh/id_xmss.pub error:2
  debug3: failed to open file:C:/Users/Phorcys/.ssh/id_xmss error:2
  debug1: identity file C:\\Users\\Phorcys/.ssh/id_xmss type -1
  debug3: Failed to open file:C:/Users/Phorcys/.ssh/id_xmss-cert error:2
  debug3: Failed to open file:C:/Users/Phorcys/.ssh/id_xmss-cert.pub error:2
  debug3: failed to open file:C:/Users/Phorcys/.ssh/id_xmss-cert error:2
  debug1: identity file C:\\Users\\Phorcys/.ssh/id_xmss-cert type -1
  debug1: Local version string SSH-2.0-OpenSSH_for_Windows_8.6
  running command "coder vscodessh": find workspace:
      github.com/coder/coder/v2/cli.(*RootCmd).vscodeSSH.func1
          /home/runner/actions-runner/_work/coder/coder/cli/vscodessh.go:103
    - invalid character '<' looking for beginning of value
  kex_exchange_identification: Connection closed by remote host
  Connection closed by UNKNOWN port 65535
  ```

  </p>
</details>

---

| Software name                           | Version                  |
|-----------------------------------------|--------------------------|
| Coder Server (dogfood instance) | `v2.0.2-devel+7404ee9b2` |
| Coder CLI                        | `v2.1.1+306615c`         |
| Windows                          | `11 22621.2134`          |

---

While this does happen in VSCode, it is a Coder CLI issue.
I think this can simply be fixed by checking whether the CLI is logged in or not.

**Comment by phorcys420** [comment]
welp, it actually was a VSCode issue (I think), I'll close this one now.
