### ISSUE TITLE
test flake: test-e2e tests/createWorkspace.spec.ts:105:5 › create workspace and overwrite default parameters 

### ISSUE THREAD

**Issue by matifali** [coder/coder#9424]
seen in https://github.com/coder/coder/actions/runs/6015567350/job/16317708669#step:10:2912
<details>
<summary>Details</summary>

```console
1) [tests] › tests/createWorkspace.spec.ts:105:5 › create workspace and overwrite default parameters 

    Test timeout of 60000ms exceeded.

    Error: page.waitForSelector: Target closed
    =========================== logs ===========================
    waiting for locator('span[data-testid=\'build-status\']').locator('text=Running') to be visible
    ============================================================

       at helpers.ts:44

      42 |   await expect(page).toHaveURL("/@admin/" + name)
      43 |
    > 44 |   await page.waitForSelector(
         |              ^
      45 |     "span[data-testid='build-status'] >> text=Running",
      46 |     {
      47 |       state: "visible",

        at createWorkspace (/home/runner/actions-runner/_work/coder/coder/site/e2e/helpers.ts:44:14)
        at /home/runner/actions-runner/_work/coder/coder/site/e2e/tests/createWorkspace.spec.ts:116:25

    Pending operations:
      - page.waitForSelector at e2e/helpers.ts:44:14


    attachment #1: video (video/webm) ──────────────────────────────────────────────────────────────
    test-results/tests-createWorkspace-create-workspace-and-overwrite-default-parameters-tests/video.webm
    ────────────────────────────────────────────────────────────────────────────────────────────────
```
</details>

**Comment by mtojek** [comment]
Duplicate (same root cause): https://github.com/coder/coder/issues/9426
