### ISSUE TITLE
test flake: test-e2e tests/updateWorkspace.spec.ts:65:5 › update workspace, new required, mutable parameter added

### ISSUE THREAD

**Issue by matifali** [coder/coder#9425]
Seen in: https://github.com/coder/coder/actions/runs/6015567350/job/16317708669#step:10:2942
<details>
<summary>Logs</summary>

```console
 2) [tests] › tests/updateWorkspace.spec.ts:65:5 › update workspace, new required, mutable parameter added 

    Test timeout of 60000ms exceeded.

    Error: page.goto: net::ERR_ABORTED; maybe frame was detached?
    =========================== logs ===========================
    navigating to "http://localhost:3000/templates/855f3178/workspace", waiting until "networkidle"
    ============================================================

       at helpers.ts:31

      29 |   buildParameters: WorkspaceBuildParameter[] = [],
      30 | ): Promise<string> => {
    > 31 |   await page.goto("/templates/" + templateName + "/workspace", {
         |              ^
      32 |     waitUntil: "networkidle",
      33 |   })
      34 |   await expect(page).toHaveURL("/templates/" + templateName + "/workspace")

        at createWorkspace (/home/runner/actions-runner/_work/coder/coder/site/e2e/helpers.ts:31:14)
        at /home/runner/actions-runner/_work/coder/coder/site/e2e/tests/updateWorkspace.spec.ts:74:46

    Pending operations:
      - page.goto at e2e/helpers.ts:31:14


    attachment #1: video (video/webm) ──────────────────────────────────────────────────────────────
    test-results/tests-updateWorkspace-update-workspace-new-required-mutable-parameter-added-e41283-tests/video.webm
    ────────────────────────────────────────────────────────────────────────────────────────────────
```
</details>

**Comment by mtojek** [comment]
Duplicate (same root cause): https://github.com/coder/coder/issues/9426
