### ISSUE TITLE
test flake: test-e2e webServer is not accessible

### ISSUE THREAD

**Issue by matifali** [coder/coder#9426]
Seen in: https://github.com/coder/coder/actions/runs/6015567350/job/16317708669#step:10:2972
<details>
<summary>Details</summary>

```console
3) [tests] › tests/updateWorkspace.spec.ts:107:5 › update workspace with ephemeral parameter enabled 

    Test timeout of 60000ms exceeded.

    Error: page.goto: net::ERR_ABORTED; maybe frame was detached?
    =========================== logs ===========================
    navigating to "http://localhost:3000/templates/new", waiting until "networkidle"
    ============================================================

       at helpers.ts:123

      121 |   })
      122 |
    > 123 |   await page.goto("/templates/new", { waitUntil: "networkidle" })
          |              ^
      124 |   await expect(page).toHaveURL("/templates/new")
      125 |
      126 |   await page.getByTestId("file-upload").setInputFiles({

        at createTemplate (/home/runner/actions-runner/_work/coder/coder/site/e2e/helpers.ts:123:14)
        at /home/runner/actions-runner/_work/coder/coder/site/e2e/tests/updateWorkspace.spec.ts:109:20

    Pending operations:
      - page.goto at e2e/helpers.ts:123:14


    attachment #1: video (video/webm) ──────────────────────────────────────────────────────────────
    test-results/tests-updateWorkspace-update-workspace-with-ephemeral-parameter-enabled-tests/video.webm
    ────────────────────────────────────────────────────────────────────────────────────────────────
```

</details>

**Comment by mtojek** [comment]
If you look at build logs for `[update workspace, new required, mutable parameter added]` test, you will notice that requests:

```
2023-08-31T08:13:48.2380836Z [stdout] [update workspace, new required, mutable parameter added]: [onRequest] method=GET url=http://localhost:3000/api/v2/templateversions/00597065-da01-40ef-8720-31efd34c7e61 postData=

2023-08-31T08:14:15.3718556Z [stdout] [update workspace, new required, mutable parameter added]: [onRequest] method=GET url=http://localhost:3000/api/v2/deployment/stats postData=
```

are hanging due to uknown web server issue (possibly not responding?). The web server is started once per whole `playwright:test` run, so it is valid that it isn't available for later tests (blank, white screen).

We need to understand why the web server stops responding.

**Comment by matifali** [comment]
I was checking https://playwright.dev/docs/trace-viewer
Do you think enabling this trace can help us diagnose?
```ts
import { defineConfig } from '@playwright/test';
export default defineConfig({
  retries: 1,
  use: {
    trace: 'on-first-retry',
  },
});
```

**Comment by mtojek** [comment]
Provided that it works as in the video, in the long term it might be useful. Unfortunately in this case, something bad happens under the hood close to the web server, and we can't research it with traces.

**Comment by mtojek** [comment]
We spotted a deadlock happening in coderd: https://github.com/coder/coder/pull/9484
