### ISSUE TITLE
[VS Code Desktop] Unable to Establish Remote SSH Connection

### ISSUE THREAD

**Issue by RyousukeUchino** [coder/coder#9491]
## Version
- Coder: [v2.1.4+eb68684](https://github.com/coder/coder/commit/eb686843275605b4cc7153e9b418f7350098662b)
- VSCode: v1.81.1
- Coder Remote: v0.1.21
- Nginx Proxy Manager: v2.10.4
- Docker: v24.0.5, build ced0996
- Docker Compose: v2.20.2

## Configuration
- **Method of Installing Coder**: Docker Compose
- **Network Setup**: 
    - Client PC (Windows) <--CloudFlare DNS Proxy--> Nginx Proxy Manager <---proxy(npm_default)---> Coder

**CloudFlare Settings**
- **DNSSEC**: true
- **SSL/TLS encryption mode**: Full
- **Always Use HTTPS**: true
- **HTTP Strict Transport Security (HSTS)**: false
- **Minimum TLS Version**: TLS 1.0
- **Opportunistic Encryption**: true
- **TLS 1.3**: true
- **Automatic HTTPS Rewrites**: true
- **Bot Fight Mode**: true

![image](https://github.com/coder/coder/assets/60417723/9390b486-9bc8-4029-81ad-d2fe65c1ca04)

<details>
  <summary>
    compose.yml file
  </summary>
  <div>

```yml
version: "3.9"
services:
  coder:
    image: ghcr.io/coder/coder:latest
    group_add:
      - "998" # docker group on host
    env_file:
      - stack.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      database:
        condition: service_healthy
    networks:
      - coder_net
      - npm_default
  database:
    image: "postgres:14.2"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-username} # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password} # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: ${POSTGRES_DB:-coder} # The PostgreSQL default database (automatically created at first launch)
    volumes:
      - coder_data:/var/lib/postgresql/data # Use "docker volume rm coder_coder_data" to reset Coder
    env_file:
      - stack.env
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-username} -d ${POSTGRES_DB:-coder}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - coder_net
volumes:
  coder_data:
networks:
  coder_net:
  npm_default:
    external: true
```

  </div>
</details>

<details>
  <summary>
    stack.env file
  </summary>
  <div>

```env
CODER_PG_CONNECTION_URL="~~~"
CODER_ACCESS_URL=https://example.work
CODER_WILDCARD_ACCESS_URL=*.example.work
CODER_HTTP_ADDRESS=0.0.0.0:7080
CODER_TLS_ADDRESS=0.0.0.0:3443
CODER_TLS_CERT_FILE=
CODER_TLS_ENABLE=
CODER_TLS_KEY_FILE=
CODER_OAUTH2_GITHUB_ALLOW_SIGNUPS=false
CODER_OAUTH2_GITHUB_ALLOWED_ORGS=orgs
CODER_OAUTH2_GITHUB_CLIENT_ID=client_id
CODER_OAUTH2_GITHUB_CLIENT_SECRET=secret
```

  </div>
</details>

<details>
  <summary>
    Nginx Proxy Manager Setting
  </summary>
  <div>

![image](https://github.com/coder/coder/assets/60417723/54d1c1b2-c7e6-4a1a-a60e-8334dc728e84)

![image](https://github.com/coder/coder/assets/60417723/619f4afc-744c-4e12-8c1e-556579d52ef1)

  </div>
</details>

## Current Behavior
- **code-server**: Working as expected
- **Web Terminal**: Working as expected

## Error Logs
<details>
  <summary>
    Remote SSH log
  </summary>
  <div>

```powershell
[08:46:04.857] Log Level: 2
[08:46:04.888] VS Code version: 1.81.1
[08:46:04.888] Remote-SSH version: remote-ssh@0.102.0
[08:46:04.889] win32 x64
[08:46:07.085] SSH Resolver called for "ssh-remote+coder-vscode--r-uchino--test", attempt 1
[08:46:07.085] "remote.SSH.useLocalServer": false
[08:46:07.086] "remote.SSH.showLoginTerminal": false
[08:46:07.086] "remote.SSH.remotePlatform": {"coder-vscode--r-uchino--node-pnpm":"linux","coder-vscode--r-matoba--node-pnpm--main":"linux","coder-vscode--r-uchino--node-pnpm--main":"linux","coder-vscode--r-uchino--ec2-test":"linux","coder-vscode--r-uchino--volta-node":"linux","coder-vscode--r-uchino--ec2-medium":"linux","coder-vscode--r-uchino--test":"linux","coder-vscode--r-uchino--demand-link-dev":"linux","coder-vscode--r-uchino--demand-link-dev--main":"linux","coder-vscode--r-uchino--dl-dev":"linux","coder-vscode--r-uchino--test--main":"linux","coder-vscode--r-uchino--testa":"linux","coder-vscode--r-uchino--testa--main":"linux"}
[08:46:07.086] "remote.SSH.path": undefined
[08:46:07.086] "remote.SSH.configFile": undefined
[08:46:07.086] "remote.SSH.useFlock": true
[08:46:07.086] "remote.SSH.lockfilesInTmp": false
[08:46:07.087] "remote.SSH.localServerDownload": auto
[08:46:07.087] "remote.SSH.remoteServerListenOnSocket": false
[08:46:07.087] "remote.SSH.showLoginTerminal": false
[08:46:07.087] "remote.SSH.defaultExtensions": []
[08:46:07.087] "remote.SSH.loglevel": 2
[08:46:07.087] "remote.SSH.enableDynamicForwarding": true
[08:46:07.088] "remote.SSH.enableRemoteCommand": false
[08:46:07.088] "remote.SSH.serverPickPortsFromRange": {}
[08:46:07.088] "remote.SSH.serverInstallPath": {}
[08:46:07.093] SSH Resolver called for host: coder-vscode--r-uchino--test
[08:46:07.093] Setting up SSH remote "coder-vscode--r-uchino--test"
[08:46:07.097] Using commit id "6c3e3dba23e8fadc360aed75ce363ba185c49794" and quality "stable" for server
[08:46:07.101] Install and start server if needed
[08:46:07.104] Checking ssh with "C:\Windows\system32\ssh.exe -V"
[08:46:07.106] Got error from ssh: spawn C:\Windows\system32\ssh.exe ENOENT
[08:46:07.106] Checking ssh with "C:\Windows\ssh.exe -V"
[08:46:07.107] Got error from ssh: spawn C:\Windows\ssh.exe ENOENT
[08:46:07.107] Checking ssh with "C:\Windows\System32\Wbem\ssh.exe -V"
[08:46:07.108] Got error from ssh: spawn C:\Windows\System32\Wbem\ssh.exe ENOENT
[08:46:07.108] Checking ssh with "C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[08:46:07.109] Got error from ssh: spawn C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[08:46:07.109] Checking ssh with "C:\Windows\System32\OpenSSH\ssh.exe -V"
[08:46:07.146] > OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3

[08:46:07.152] Running script with connection command: "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 56965 "coder-vscode--r-uchino--test" bash
[08:46:07.154] Terminal shell path: C:\Windows\System32\cmd.exe
[08:46:24.172] Resolver error: Error: Connecting with SSH timed out
	at m.Timeout (c:\Users\r-uch\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:584271)
	at Timeout._onTimeout (c:\Users\r-uch\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:680601)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)
[08:46:24.180] ------
```

  </div>
</details>

## Additional Information
The Remote SSH connection appears to be timing out, making it look like it's unreachable. I'm unsure how to resolve this issue.

**Comment by matifali** [comment]
Hi, this is related to #9337, and a workaround for now is to turn off Cloudflare proxying (Oraneg cloud).

**Comment by RyousukeUchino** [comment]
> Hi, this is related to #9337, and a workaround for now is to turn off Cloudflare proxying (Oraneg cloud).

I have already tried that, and disabling the proxy did not resolve the issue.

**Comment by matifali** [comment]
@RyousukeUchino can you do `coder ssh <workspace>` from the client?

**Comment by RyousukeUchino** [comment]
@matifali 
I executed the following command but received no response. 
CloudFlare proxy has been disabled.

`"C:\Windows\System32\OpenSSH\ssh.exe" -T -D 50778 "coder-vscode--r-uchino--test" bash`

---

Also, this server is located on my home network and uses Bind9 for DNS resolution when the CloudFlare proxy is disabled. At this time, the terminal and code-server are functioning without issues on the Coder.

Do I need to install the Coder CLI for verification?

**Comment by matifali** [comment]
@RyousukeUchino Yes, you need coder cli to use `coder ssh`.

**Comment by RyousukeUchino** [comment]
@matifali 
Tried but no response as well.

![image](https://github.com/coder/coder/assets/60417723/23011593-8c22-48e4-a13f-f571b6deee7f)

**Comment by RyousukeUchino** [comment]
@matifali 
Ah, I'm really sorry. The issue was with our internal network's DNS and routing. I've managed to resolve it after trying various things. Sorry for the inconvenience caused.

**Comment by matifali** [comment]
@RyousukeUchino, just to be clear is Cloudflare proxying still on?

**Comment by RyousukeUchino** [comment]
@matifali 
The CloudFlare proxy is currently disabled; please give me a little time. I'll check to see if it functions properly even when the CloudFlare proxy is enabled, under the conditions of global access.

**Comment by RyousukeUchino** [comment]
@matifali 
I've tried it. I attempted to use VSCode Desktop through the CloudFlare proxy from an entirely different global network, and again, it resulted in an error.
I have been checking the IP queries and such using ping and dig.
After disabling the CloudFlare proxy again and checking with ping, I was able to connect normally when using VSCode Desktop.
It seems we can almost assert that 'Using the CloudFlare proxy will make Remote SSH unusable.

**Comment by matifali** [comment]
@RyousukeUchino Thank you for the testing and feedback. When the Cloudflare proxy is on, networking becomes a bit thicker. As a workaround, you can try two options.
1. Disable Cloudflare proxy (orange cloud)
2. Use Tailscale derp map as suggested [here](https://github.com/coder/coder/issues/9337#issuecomment-1703100467)

**Comment by RyousukeUchino** [comment]
@matifali 
Fantastic! Thanks to your help, I can now connect without any issues even with the CloudFlare proxy enabled. Thank you so much!
