### ISSUE TITLE
bug: panic in MultiAgent.UnsubscribeAgent with ExperimentSingleTailnet

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#9929]
Panic under rPTY traffic with single_tailnet enabled.

https://stats.dev.c8s.io/d/qLVSTR-Vz/coderv2-loadtest-dashboard?orgId=1&from=1695829564765&to=1695829732027

Logs: https://cloudlogging.app.goo.gl/bTGg3wyNM8iLf6nY7

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x137db65]

goroutine 286 [running]:
github.com/coder/coder/v2/tailnet.(*MultiAgent).UnsubscribeAgent(0xfd7a115ca1e04c18?, {0xa, 0xd1, 0x65, 0xf4, 0x9f, 0x48, 0x4c, 0x18, 0xac, ...})
	/home/runner/actions-runner/_work/coder/coder/tailnet/multiagent.go:104 +0xc5
github.com/coder/coder/v2/coderd.(*ServerTailnet).doExpireOldAgents(0xc0001af040, 0x1a3185c5000)
	/home/runner/actions-runner/_work/coder/coder/coderd/tailnet.go:205 +0x72f
github.com/coder/coder/v2/coderd.(*ServerTailnet).expireOldAgents(0xc0001af040)
	/home/runner/actions-runner/_work/coder/coder/coderd/tailnet.go:172 +0x92
created by github.com/coder/coder/v2/coderd.NewServerTailnet
	/home/runner/actions-runner/_work/coder/coder/coderd/tailnet.go:152 **+0xc9f**
```

**Comment by coadler** [comment]
Thanks for finding this @johnstcn!!

**Comment by johnstcn** [comment]
Don't thank me, thank Nessie for poking her head above the water 
![Screenshot 2023-09-29 at 11 08 35](https://github.com/coder/coder/assets/4949514/2096db6b-4241-4c79-995c-b9d7ec6e452f)
