### ISSUE TITLE
e2e test flake in createWorkspace.spec.ts

### ISSUE THREAD

**Issue by aslilac** [coder/coder#9956]
https://github.com/coder/coder/actions/runs/6358309656/job/17270423324?pr=9907

```
      '\x1B[2m  -   locator resolved to <html>…</html>\x1B[22m\n' +
      '\x1B[2m  -   unexpected value "http://localhost:3000/templates/new"\x1B[22m\n' +
      '\x1B[2m  -   locator resolved to <html>…</html>\x1B[22m\n' +
      '\x1B[2m  -   unexpected value "http://localhost:3000/templates/new"\x1B[22m\n' +
      '\x1B[2m  -   locator resolved to <html>…</html>\x1B[22m\n' +
      '\x1B[2m  -   unexpected value "http://localhost:3000/templates/new"\x1B[22m\n' +
      '\x1B[2m  -   locator resolved to <html>…</html>\x1B[22m\n' +
      '\x1B[2m  -   unexpected value "http://localhost:3000/templates/new"\x1B[22m\n' +
      '\x1B[2m  -   locator resolved to <html>…</html>\x1B[22m\n' +
      '\x1B[2m  -   unexpected value "http://localhost:3000/templates/new"\x1B[22m\n' +
      '\x1B[2m  -   locator resolved to <html>…</html>\x1B[22m\n' +
      '\x1B[2m  -   unexpected value "http://localhost:3000/templates/new"\x1B[22m\n' +
      '\x1B[2m  -   locator resolved to <html>…</html>\x1B[22m\n' +
      '\x1B[2m  -   unexpected value "http://localhost:3000/templates/new"\x1B[22m\n' +
      '\x1B[2m  -   locator resolved to <html>…</html>\x1B[22m\n' +
      '\x1B[2m  -   unexpected value "http://localhost:3000/templates/new"\x1B[22m\n' +
      '\x1B[2m  -   locator resolved to <html>…</html>\x1B[22m\n' +
      '\x1B[2m  -   unexpected value "http://localhost:3000/templates/new"\x1B[22m\n' +
      '\x1B[2m  -   locator resolved to <html>…</html>\x1B[22m\n' +
      '\x1B[2m  -   unexpected value "http://localhost:3000/templates/new"\x1B[22m\n' +
      '\x1B[2m  -   locator resolved to <html>…</html>\x1B[22m\n' +
      '\x1B[2m  -   unexpected value "http://localhost:3000/templates/new"\x1B[22m\n',
    stack: 'Error: \x1B[31mTimed out 30000ms waiting for \x1B[39m\x1B[2mexpect(\x1B[22m\x1B[31mreceived\x1B[39m\x1B[2m).\x1B[22mtoHaveURL\x1B[2m(\x1B[22m\x1B[32mexpected\x1B[39m\x1B[2m)\x1B[22m\n' +
      '\n' +
      'Expected string: \x1B[32m"http://localhost:3000/templates/\x1B[7m8de5f924\x1B[27m"\x1B[39m\n' +
      'Received string: \x1B[31m"http://localhost:3000/templates/\x1B[7mnew\x1B[27m"\x1B[39m\n' +
      'Call log:\n' +
      '  \x1B[2m- expect.toHaveURL with timeout 30000ms\x1B[22m\n' +
      "\x1B[2m  - waiting for locator(':root')\x1B[22m\n" +
      '\x1B[2m  -   locator resolved to <html>…</html>\x1B[22m\n' +
      '\x1B[2m  -   unexpected value "http://localhost:3000/templates/new"\x1B[22m\n' +
      '\x1B[2m  -   locator resolved to <html>…</html>\x1B[22m\n' +
      '\x1B[2m  -   unexpected value "http://localhost:3000/templates/new"\x1B[22m\n' +
      '\x1B[2m  -   locator resolved to <html>…</html>\x1B[22m\n' +
      '\x1B[2m  -   unexpected value "http://localhost:3000/templates/new"\x1B[22m\n' +
      '\x1B[2m  -   locator resolved to <html>…</html>\x1B[22m\n' +
      '\x1B[2m  -   unexpected value "http://localhost:3000/templates/new"\x1B[22m\n' +
      '\x1B[2m  -   locator resolved to <html>…</html>\x1B[22m\n' +
      '\x1B[2m  -   unexpected value "http://localhost:3000/templates/new"\x1B[22m\n' +
      '\x1B[2m  -   locator resolved to <html>…</html>\x1B[22m\n' +
      '\x1B[2m  -   unexpected value "http://localhost:3000/templates/new"\x1B[22m\n' +
      '\x1B[2m  -   locator resolved to <html>…</html>\x1B[22m\n' +
      '\x1B[2m  -   unexpected value "http://localhost:3000/templates/new"\x1B[22m\n' +
      '\x1B[2m  -   locator resolved to <html>…</html>\x1B[22m\n' +
      '\x1B[2m  -   unexpected value "http://localhost:3000/templates/new"\x1B[22m\n' +
      '\x1B[2m  -   locator resolved to <html>…</html>\x1B[22m\n' +
      '\x1B[2m  -   unexpected value "http://localhost:3000/templates/new"\x1B[22m\n' +
      '\x1B[2m  -   locator resolved to <html>…</html>\x1B[22m\n' +
      '\x1B[2m  -   unexpected value "http://localhost:3000/templates/new"\x1B[22m\n' +
      '\x1B[2m  -   locator resolved to <html>…</html>\x1B[22m\n' +
      '\x1B[2m  -   unexpected value "http://localhost:3000/templates/new"\x1B[22m\n' +
      '\x1B[2m  -   locator resolved to <html>…</html>\x1B[22m\n' +
      '\x1B[2m  -   unexpected value "http://localhost:3000/templates/new"\x1B[22m\n' +
      '\x1B[2m  -   locator resolved to <html>…</html>\x1B[22m\n' +
      '\x1B[2m  -   unexpected value "http://localhost:3000/templates/new"\x1B[22m\n' +
      '\x1B[2m  -   locator resolved to <html>…</html>\x1B[22m\n' +
      '\x1B[2m  -   unexpected value "http://localhost:3000/templates/new"\x1B[22m\n' +
      '\x1B[2m  -   locator resolved to <html>…</html>\x1B[22m\n' +
      '\x1B[2m  -   unexpected value "http://localhost:3000/templates/new"\x1B[22m\n' +
      '\x1B[2m  -   locator resolved to <html>…</html>\x1B[22m\n' +
      '\x1B[2m  -   unexpected value "http://localhost:3000/templates/new"\x1B[22m\n' +
      '\x1B[2m  -   locator resolved to <html>…</html>\x1B[22m\n' +
      '\x1B[2m  -   unexpected value "http://localhost:3000/templates/new"\x1B[22m\n' +
      '\x1B[2m  -   locator resolved to <html>…</html>\x1B[22m\n' +
      '\x1B[2m  -   unexpected value "http://localhost:3000/templates/new"\x1B[22m\n' +
      '\x1B[2m  -   locator resolved to <html>…</html>\x1B[22m\n' +
      '\x1B[2m  -   unexpected value "http://localhost:3000/templates/new"\x1B[22m\n' +
      '\x1B[2m  -   locator resolved to <html>…</html>\x1B[22m\n' +
      '\x1B[2m  -   unexpected value "http://localhost:3000/templates/new"\x1B[22m\n' +
      '\x1B[2m  -   locator resolved to <html>…</html>\x1B[22m\n' +
      '\x1B[2m  -   unexpected value "http://localhost:3000/templates/new"\x1B[22m\n' +
      '\x1B[2m  -   locator resolved to <html>…</html>\x1B[22m\n' +
      '\x1B[2m  -   unexpected value "http://localhost:3000/templates/new"\x1B[22m\n' +
      '\x1B[2m  -   locator resolved to <html>…</html>\x1B[22m\n' +
      '\x1B[2m  -   unexpected value "http://localhost:3000/templates/new"\x1B[22m\n' +
      '\x1B[2m  -   locator resolved to <html>…</html>\x1B[22m\n' +
      '\x1B[2m  -   unexpected value "http://localhost:3000/templates/new"\x1B[22m\n' +
      '\x1B[2m  -   locator resolved to <html>…</html>\x1B[22m\n' +
      '\x1B[2m  -   unexpected value "http://localhost:3000/templates/new"\x1B[22m\n' +
      '\x1B[2m  -   locator resolved to <html>…</html>\x1B[22m\n' +
      '\x1B[2m  -   unexpected value "http://localhost:3000/templates/new"\x1B[22m\n' +
      '\x1B[2m  -   locator resolved to <html>…</html>\x1B[22m\n' +
      '\x1B[2m  -   unexpected value "http://localhost:3000/templates/new"\x1B[22m\n' +
      '\x1B[2m  -   locator resolved to <html>…</html>\x1B[22m\n' +
      '\x1B[2m  -   unexpected value "http://localhost:3000/templates/new"\x1B[22m\n' +
      '\x1B[2m  -   locator resolved to <html>…</html>\x1B[22m\n' +
      '\x1B[2m  -   unexpected value "http://localhost:3000/templates/new"\x1B[22m\n' +
      '\x1B[2m  -   locator resolved to <html>…</html>\x1B[22m\n' +
      '\x1B[2m  -   unexpected value "http://localhost:3000/templates/new"\x1B[22m\n' +
      '\x1B[2m  -   locator resolved to <html>…</html>\x1B[22m\n' +
      '\x1B[2m  -   unexpected value "http://localhost:3000/templates/new"\x1B[22m\n' +
      '\x1B[2m  -   locator resolved to <html>…</html>\x1B[22m\n' +
      '\x1B[2m  -   unexpected value "http://localhost:3000/templates/new"\x1B[22m\n' +
      '\x1B[2m  -   locator resolved to <html>…</html>\x1B[22m\n' +
      '\x1B[2m  -   unexpected value "http://localhost:3000/templates/new"\x1B[22m\n' +
      '\x1B[2m  -   locator resolved to <html>…</html>\x1B[22m\n' +
      '\x1B[2m  -   unexpected value "http://localhost:3000/templates/new"\x1B[22m\n' +
      '\n' +
      '    at createTemplate (/home/runner/actions-runner/_work/coder/coder/site/e2e/helpers.ts:136:22)\n' +
      '    at /home/runner/actions-runner/_work/coder/coder/site/e2e/tests/createWorkspace.spec.ts:24:20',
    location: {
      file: '/home/runner/actions-runner/_work/coder/coder/site/e2e/helpers.ts',
      column: 22,
      line: 136
    },
    snippet: '   at helpers.ts:136\n' +
      '\n' +
      '  134 |   await page.getByLabel("Name *").fill(name);\n' +
      '  135 |   await page.getByTestId("form-submit").click();\n' +
      '> 136 |   await expect(page).toHaveURL("/templates/" + name, {\n' +
      '      |                      ^\n' +
      '  137 |     timeout: 30000,\n' +
      '  138 |   });\n' +
      '  139 |   return name;'
  }
```

**Comment by mtojek** [comment]
Root cause: https://github.com/coder/coder/issues/9986
